### ISSUE TITLE
missing ufrag

### ISSUE THREAD

**Issue by ekr** [rtcweb-wg/jsep#1008]
>   The IceCandidate object contains a field to indicate which ICE
   username fragment (ufrag) it is associated with, as defined in
   [RFC8839], Section 5.4.  This value is used to determine which
   session description (and thereby which gathering phase) this
   IceCandidate belongs to, which helps resolve ambiguities during ICE
   restarts.  If this field is absent in a received IceCandidate
   (perhaps when communicating with a non-JSEP endpoint), the most
   recently received session description is assumed.

Should this "perhaps" be "i.e.,". Can this happen with a JSEP endpoint?

**Comment by juberti** [comment]
Well, an app could always fail to serialize the ICE candidate properly.

**Comment by ekr** [comment]
OK.
