### ISSUE TITLE
Glare?

### ISSUE THREAD

**Issue by ekr** [rtcweb-wg/jsep#1009]
>    If (1) setRemoteDescription was previously called with an offer, (2)
   setLocalDescription is called with an answer (provisional or final),
   (3) the media directions are compatible, and (4) media is available
   to send, this will result in the starting of media transmission.

Point (2) seems a bit odd here. If you call it with an offer, then that's an error, right?

**Comment by juberti** [comment]
The idea is that both an offer and answer have been supplied; until that is the case, no media is sent.

**Comment by ekr** [comment]
Yeah, I agree with this. It just seemed like case (2) was enforced by the state machine. Anyway, if you think there's nothing to do here, I'm not going to fight it.

**Comment by juberti** [comment]
This text might be slightly redundant, but it's not wrong. I'd suggest keeping as-is.

**Comment by ekr** [comment]
Sold. Closing.
