### ISSUE TITLE
Profile names: TCP/DTLS/RTP/SAVPF and TCP/DTLS/SCTP

### ISSUE THREAD

**Issue by juberti** [rtcweb-wg/jsep#101]
As per discussion in mmusic, to make it abundantly clear that DTLS is to be used even when running over ICE-TCP, the profile name should be TCP/DTLS/RTP/SAVPF. We'll leave the UDP/TLS/RTP/SAVPF one alone, since that ship has sailed, and it's less ambiguous.

**Comment by juberti** [comment]
Need Suhas to update https://tools.ietf.org/html/draft-nandakumar-mmusic-proto-iana-registration-00 to reflect the above.

**Comment by juberti** [comment]
For SCTP, https://tools.ietf.org/html/draft-ietf-mmusic-sctp-sdp-12 has the correct UDP/DTLS/SCTP and TCP/DTLS/SCTP things that we want to refer to.

**Comment by ekr** [comment]
The action item here is to update this document to use the correct fields as agreed above as if draft-nandakumar was done, and then when that document is fixed we will be good.
