### ISSUE TITLE
can addIceCandidate be sent prior to setLD()

### ISSUE THREAD

**Issue by ekr** [rtcweb-wg/jsep#1010]
>  Otherwise, the new remote candidate or end-of-candidates indication
   is supplied to the ICE agent.  In the case of a new remote candidate,
   connectivity checks will be sent to the new candidate.

However, if you do this prior to setLD() this will not cause connectivity checks to be sent, right?

**Comment by juberti** [comment]
That is correct.

**Comment by ekr** [comment]
Do you think we should change the text to say that? Perhaps "In the case of a new remote candidate, connectivity checks will be sent to the new candidate as soon as setLD(answer) is called, or immediately if it has been called already."

**Comment by juberti** [comment]
Something like that seems like a good idea. It won't always be setLD with an answer though.

**Comment by juberti** [comment]
maybe just add ", assuming setLocalDescription has already been called to initialize the ICE gathering process."
