### ISSUE TITLE
Avoid SSRC collisions

### ISSUE THREAD

**Issue by ekr** [rtcweb-wg/jsep#1011]
>      If
         an SSRC has not already been chosen for this outgoing RTP
         stream, choose a random one.  If media is already being
         transmitted, the same SSRC SHOULD be used unless the clock rate
         of the new codec is different, in which case a new SSRC MUST be
         chosen, as specified in [RFC7160], Section 3.1.

Should the advice to choose a random SSRC ensure that there are no collisions?

**Comment by juberti** [comment]
Probably. Is there text we can point at?

**Comment by ekr** [comment]
Good question. @gloinul: ^^?

**Comment by juberti** [comment]
I looked at RFC 3550 and the text there is mostly around handling collisions that occur in the multicast case, so I'd suggest just saying that the SSRC must be random and unique.
