### ISSUE TITLE
JSEP should allow reoffering rtp extensions that were not used in the previous answer

### ISSUE THREAD

**Issue by docfaraday** [rtcweb-wg/jsep#1031]
Are we using this repo for work on JSEP bis?

See https://github.com/w3c/webrtc-extensions/issues/134

Note that browsers are already doing this.

**Comment by fippo** [comment]
In particular this affects the following statement from [Subsequent offers](https://www.rfc-editor.org/rfc/rfc8829.html#section-5.2.2):
> ...  The RTP header extensions MUST only include those that are present in the most recent answer.

**Comment by fippo** [comment]
See also https://github.com/w3c/webrtc-extensions/issues/60 and https://github.com/rtcweb-wg/jsep/issues/266#issuecomment-275023331
