### ISSUE TITLE
Add example to show bad interaction of not using different PTs with RTX/bundle

### ISSUE THREAD

**Issue by ekr** [rtcweb-wg/jsep#109]
From Magnus's comments.

> Section 5.3.1: Note that for simplicity, the answerer MAY use
> different payload types for codecs than the offerer, as it is not
> prohibited by Section 6.1.  I react to the word simplicity here. I
> never consider usage of different PTs per direction anything
> simple. But, yes it is allowed by RFC 3264.  But I kind of protest to
> encourage the usage.
> 
> JU: Clearly this needs more explanation. The basic issue is the fact
> that using the same payload types gets really hairy when using RTX and
> when bundling. We can add an example of the problem.

**Comment by juberti** [comment]
I looked up my notes on this, and the key issue is that if you echo the answerer PTs, you have to be smarter in how you assign them. For example, you might normally use PTs 96-99 for audio, and then have PTs 100-101 for video, with 101 as RTX that points to 100. 

However, if the remote side offers PTs 100-103 for audio, and you echo that, and then you later add video, your offer code needs to go through and assign different PTs for video (i.e. not 100-101). This means adjusting the apt=100 on the RTX codec too.

We did this so it is definitely doable, just kind of gross.

**Comment by juberti** [comment]
I don't really think this is something that I can really argue for being in the normative text. When creating a new offer, you have to assign PTs based on what's already in use, as opposed to having a static set of PTs, but that seems to fall short of the bar for contradicting 3264.

Work here is to remove the MAY identified by Magnus.
