### ISSUE TITLE
Describe how to reject a track

### ISSUE THREAD

**Issue by ekr** [rtcweb-wg/jsep#112]
HTA writes:
"I think we have agreement that returning a zero on the port number, or putting "a=recvonly", in a track's m-line in SDP can be considered "rejecting" an incoming track.

I think we have agreement that calling track.stop() on an incoming track causes the next createOffer or createAnswer to put zero in that port number or putting "a=recvonly" in for that m-line.
"

**Comment by juberti** [comment]
Agree with the text above. Where should this text go?

**Comment by martinthomson** [comment]
I'm not sure about the a=recvonly, given that it is analogous to a=inactive, the signal we use for "on hold".

Or, more to the point, I (still) don't know how to distinguish between a=inactive and port == 0.

**Comment by juberti** [comment]
See https://tools.ietf.org/html/draft-ietf-rtcweb-jsep-09#section-5.3.1, para 6 for how stopped tracks result in an answer with port 0.

**Comment by fluffy** [comment]
I think the draft has text that has this covered

**Comment by ekr** [comment]
Agreed.
