### ISSUE TITLE
How does the answer handle non-muxed offers when mux policy is require

### ISSUE THREAD

**Issue by ekr** [rtcweb-wg/jsep#114]
Cullen thinks it should accept and non-mux.

EKR and Justin currently believe it should reject the offer.

**Comment by ekr** [comment]
Original text: 
when acting as answerer will reject any m= section that does not provide an "a=rtcp-mux" attribute.

**Comment by juberti** [comment]
LGTM at IETF 92

**Comment by juberti** [comment]
open issue in text to be removed
