### ISSUE TITLE
Confusion about how many BUNDLE groups there are

### ISSUE THREAD

**Issue by ekr** [rtcweb-wg/jsep#119]
5.2.1 seems clear that there is one:
Once all m= sections have been generated, a session-level "a=group" attribute MUST be added as specified in [RFC5888]. This attribute MUST have semantics "BUNDLE", and MUST include the mid identifiers of each m= section. The effect of this is that the browser offers all m= sections as one BUNDLE group. However, whether the m= sections are bundle-only or not depends on the BUNDLE policy.

4.1.1 seems clear that "balanced" means >1
The application will BUNDLE all media streams of the same type together. That is, if there are multiple audio and multiple video MediaStreamTracks attached to a PeerConnection, all but the first audio and video tracks will be marked as bundle-only, and candidates will only be gathered for N media streams, where N is the number of distinct media types. When talking to a non-BUNDLE-aware endpoint, only the non-bundle-only streams will be negotiated. This policy balances desire to multiplex with the need to ensure basic audio and video still works in legacy cases. ***Data channels will be in a separate bundle group.***

Justin and EKR believe the number should always be 1. Need to fix the text to make this clear.

**Comment by juberti** [comment]
Right, seems like we need to change 4.1.1 to say the application will try to BUNDLE all media streams, but can fall back to the unbundled case where audio, video, and data are on separate transports.
We should also have a sentence somewhere that indicates that only a single bundle group is ever offered.

**Comment by juberti** [comment]
Control of # of bundle groups is left as something for the future; we would need an additional policy, or some other thing to frob, perhaps on rtpsender.

**Comment by fluffy** [comment]
First I think browsers need to be able to correctly respond to more than one bundle (which may mean rejecting the bundle), but I want to leave it open that an browser impelmetion is allowed to create more than one bundle. If you read the mux atributes draft you will see there are many cases where the browser might choose to create more than one bundle.

**Comment by juberti** [comment]
Which section?

**Comment by fluffy** [comment]
Well if you ever want to do any of things that are not allowed to be in the same bundle, you end up wanting two bundles.
