### ISSUE TITLE
add text to explain b=tias usage 

### ISSUE THREAD

**Issue by fluffy** [rtcweb-wg/jsep#122]

**Comment by juberti** [comment]
TIAS is the bandwidth of the media itself, without RTP/UDP/IP framing. Analogous to opus maxaveragebitrate. I think we should use TIAS like AS, that is, if present in the remote description, we limit our send rate to be less than the TIAS value.

Q: how should we convert AS values to TIAS values? It is a nontrivial calculation; should we simply insist on TIAS?

**Comment by fluffy** [comment]
I think we should support TIAS. But I think we also need to suppport AS. I agree the calulation of AS to TIAS is not trivial to get perfect but it's easy to get "good enough" and there is no need for it to be perfect.  I've got no problem with adding some non normative text that provides a simple algorithm that implementors might use to turn an AS into a TIAS

**Comment by juberti** [comment]
Can you propose an algorithm here?

**Comment by fluffy** [comment]
Is it reasonable to assume the browser knows the packet rate for the data where we are converting AS to TIAS or should that be considered unknown by the algorithm.  I'm assuming the browser know if it over v6 or v4 but perhaps I should not assume that (makes a 20 byte per packet difference which could be something like 25% in some cases)

**Comment by fluffy** [comment]
Proposed algorithm is roughly

as and tias in bits per second 

pps = max packets per second for the codec or if not known max( 50 , as/8000 )

 tias =  as * 0.95  - * pps * hdrSize 

The 0.95 is to give 5% to RTCP 

hdrSize is a constant compiled into the app which we might calculate by just measuring it for our usage but is an rough estimate of the size of the following:

IPv4 hdr (if we are on v6, the estimate was probably specced for v4 anyways) 
UDP HDR
RTP HDR
RTP Extension HDRs ( and we can just assume the default ones for WebRTC for this estimate)
CSRC list - probably assume empty

**Comment by juberti** [comment]
Prague: Proposed TIAS = AS * 0.95 - 50 * 40 * 8. If you want more accuracy, use TIAS.

**Comment by juberti** [comment]
This algorithm needs to be added to the handling a remote description section.
