### ISSUE TITLE
Decide how to handle JS mangling of m= line bungling

### ISSUE THREAD

**Issue by martinthomson** [rtcweb-wg/jsep#125]
If the application mutates the bundling (or the `a=rtcpmux` attributes) between `create(Offer|Answer)` and `setLocalDescription`, what happens?

**Comment by juberti** [comment]
obviously if you have rtcpmux set to require, something has to explode.
otherwise, I guess it could work

**Comment by fluffy** [comment]
I have a slight preference for allowing this type of change but I'm not the guy who has to implement it... I think the way it would be used it JS would ask for totally unbundled in offer than bundle some of it in the JS. Much harder to imagine how it would work to take something bundled and make it less bundled.

**Comment by alvestrand** [comment]
Unbundling interacts with candidates. You have to have candidates for everything that's taken out of a bundle. Does this mean that a=bundleonly media sections can't be unbundled?

**Comment by ekr** [comment]
Not generally because this is pre-setLocal.

You obviously can't unbundle things that are bundleonly if you're the answerer and the offerer made them bundleonly

**Comment by juberti** [comment]
Prague: No munging between createOffer and setLD of BUNDLE stuff. Remote description can obviously be munged.
