### ISSUE TITLE
Mapping between MediaStreamTrack and signaling

### ISSUE THREAD

**Issue by adam-be** [rtcweb-wg/jsep#132]
In a webrtc-pc PR [1], I use "media description" to refer to the piece of signaling that is used to initialize the attributes of a MediaStreamTrack. For example:

"
Initialize track's kind attribute to "audio" or "video" depending on the type of the media description
"

I noted that JSEP uses the wording "m= line", but that seems a bit rough for the W3C document. Should we use some other wording than "media description" in the W3C doc, or could we add some text to JSEP and use it as the reference for the term "media description"?

[1] https://github.com/w3c/webrtc-pc/pull/221

**Comment by alvestrand** [comment]
After reviewing RFC 4566 and seeing that it defined "media description"
but not "m-line", I have switched the MSID draft to using "media
description".

The trigger for reviewing it was someone asking if the term "m-line"
referred to just the line or the whole section.

**Comment by juberti** [comment]
I have thought of the whole thing as a "m= section", since "m= line" is clearly ambiguous. 

Media description is preferable to either though.

**Comment by juberti** [comment]
Is any action needed here?

**Comment by alvestrand** [comment]
Current jsep draft (both published version and repository) does not contain "m-line" or "m-section". suggest closing the issue.

**Comment by fluffy** [comment]
Adam, do you want us specifically say what we mean by the term ""media description" in JSEP so you can have a pointer to that in PC?

**Comment by juberti** [comment]
search for "m= line" or "m= section"

**Comment by ekr** [comment]
This seems to not need any change. Adam, please feel free to submit a PR if you have some change you would like.
