### ISSUE TITLE
Clarify m= section for "offerToReceive"

### ISSUE THREAD

**Issue by stefhak** [rtcweb-wg/jsep#140]
For the case where the offer should contain m-lines dedicated for incoming media (reconly lines), section 5.2.3.1 and 5.2.3.1 says nothing about what should be in those m= sections. Should be clarified.

**Comment by ekr** [comment]
Post Sapporo: remove OfferToReceive

**Comment by fluffy** [comment]
@stefhak - Can you have a look at this and decide if this bug should just be closed or if we still need some updates. Thanks

**Comment by stefhak** [comment]
@fluffy those sections (5.3.2.1 and 5.3.2.2) still just say ~"if N>M include N-M m-sections of type audio/video", but it says nothing about those m-sections apart from the type and the direction attribute (i.e. should a mid be included, ufrag, rtcp, ....). 

Perhaps 'the offer MUST include N non-rejected m= sections with media type "audio"' can be extended to 'the offer MUST include N non-rejected m= sections with media type "audio" according to section 5.2.1' or something, or what is mandatory to put in each m-section is lifted out to a separate section that can be referenced from 5.2.1, 5.2.2, 5.2.3.1 and 5.2.3.2)

**Comment by juberti** [comment]
This will all be resolved by adding transceivers (and removing OfferToReceiveX).

**Comment by stefhak** [comment]
that's right. Closing the issue.
