### ISSUE TITLE
Allow CreateOffer in remote-pranswer?

### ISSUE THREAD

**Issue by ekr** [rtcweb-wg/jsep#143]
Should you be allowed to do CreateOffer when in remote-pranswer?

**Comment by ekr** [comment]
@fluffy PTAL

**Comment by juberti** [comment]
Context for this issue: remote-pranswer means we have a remote description. Should it be used when generating the offer?

**Comment by fluffy** [comment]
No you can't create an second offer when you have not got a final answer. If you want to do that what you need to do is cancel the current offer by rolling back and now you are in a stable state and and do a new createOffer

**Comment by alvestrand** [comment]
Creating the second offer should be allowed. It gives you some SDP that you can inspect, and that can be useful - might even be useful in choosing between resetting the state or waiting for a final answer.
It would be pretty dumb to send the generated offer to your communication partner, and calling SetLD() with it would result in a failure.

**Comment by juberti** [comment]
Agree with alvestrand. No action needed, I think.

**Comment by fluffy** [comment]
and just to add more - my recollection of the folks in the room at IETF 93 was they agreed with HTA position

**Comment by ekr** [comment]
This is implicitly allowed by the spec. No action needed.

**Comment by juberti** [comment]
Need to remove open issue on this.
