### ISSUE TITLE
Should b= be ignored?

### ISSUE THREAD

**Issue by ekr** [rtcweb-wg/jsep#144]

**Comment by ekr** [comment]
@juberti The current text says that it should be basically ignored at session level. However the discussion at IETF 92 was contrary to this, I think:

```

#Slide b= SDP
Lengthy discussion on CT, AT and TIAS...
Magnus: TIAS only has declarative mean, no offer/answer semantic
Roni Even: what is important is the precision you need on the limit (as or TIAS may not be important except if you want precise values)
Justin: for audio bandwidth value in AS might be very higher than with TIAS.
Cullen: to answer Keith's question, I don't think we change the original spec, we just give more information on their use when a browser use them.
Mo : spec should make clear that CT is the sum of all (remote and local senders)
Jonathan: CT originally written for multicast, O/A changed that, CT means all the things
Magnus: I think it would 
Cullen: RFC 3264:  indicate the bandwidth the offerer the would like to receive
Most document should probably be all right.
Ted: 15' left. Should we continue on this or move to next topic?
Cullen, Justin: propose this text and see if people can refine it.
```

**Comment by ekr** [comment]
@juberti, I think this is your action

**Comment by juberti** [comment]
This was the proposal at IETF 92:
- AS at media level is the max bitrate the other side wants to receive for that m- line (recommended!)
- AS at session level is not well-defined, and MUST be treated as an error
- CT at session level is the max bitrate for the session, and browser can choose how to deal with this however it sees fit
- CT at media level MUST be treated as an error

Discussion (IIRC) indicated that TIAS should be used where possible. 
There was some discussion about AS at session level, but I forget how AS differed from CT when used that way. Do either of you recall?

**Comment by juberti** [comment]
Related to #124

**Comment by fluffy** [comment]
I thought the end of AS at session level was not useful but I did not go back to listen to recording

**Comment by hardie** [comment]
@gloinul can you look at the current JSEP draft to be sure the b= and other bandwidth control mentions are correct?

**Comment by juberti** [comment]
This would affect the handling-a-remote-description section.
