### ISSUE TITLE
Do other non a= lines need more than syntactic validation?

### ISSUE THREAD

**Issue by ekr** [rtcweb-wg/jsep#145]

**Comment by juberti** [comment]
IIRC the consensus from IETF 92 was that only b= (and m=, of course) needed this.

**Comment by fluffy** [comment]
It seems like the syntax MUST be correct for all the SDP stuff that is MTI. So things like the ICE candidates for example need to have a syntax that is section 15.1 of RFC 5245

**Comment by juberti** [comment]
Right, but ICE candidates etc are all done using a=. This bug is about whether there is anything besides b= or a= (and obviously m=) that JSEP needs to look at.

**Comment by fluffy** [comment]
sorry - lost the context that this was not about a= stuff

**Comment by juberti** [comment]
Now that we have decided to not act on c=, I think this is editor-ready.

**Comment by ekr** [comment]
Is there something more to do here than remove the TODO?

**Comment by fluffy** [comment]
seems like just remove it to me

**Comment by juberti** [comment]
Yep, I think we just need to remove the TODO.

**Comment by juberti** [comment]
This might have been resolved by #199.

**Comment by juberti** [comment]
No, this is still open.
