### ISSUE TITLE
Clarify CNAME for answer

### ISSUE THREAD

**Issue by stefhak** [rtcweb-wg/jsep#147]
While cname for offers is described quite clearly, the sections describing answers don't mention CNAME.

**Comment by juberti** [comment]
This should get handled in #135
 @fluffy

**Comment by stefhak** [comment]
I don't think that is the place. Looking at section 5.3.1. Initial answer, there is text saying
'If a local MediaStreamTrack has been associated, an "a=ssrc"  line, as specified in [RFC5576], Section 4.1, indicating the SSRC to be used for sending media.'
There should be something about cname here as well, just as it is for the corresponding part in section 5.2.1 Initial Offer.

**Comment by juberti** [comment]
Right, but #135 is making changes to 5.2.1, so that's probably the right place to change 5.3.1 as well.

**Comment by stefhak** [comment]
I saw Ekr updated #135 and closed this one. Makes sense.
