### ISSUE TITLE
Provide example of how to do an inactive stream

### ISSUE THREAD

**Issue by ekr** [rtcweb-wg/jsep#15]
S 4.1.4.1 reads:

"   Most web applications will not need to create answers using the
   "pranswer" type.  While it is good practice to send an immediate
   response to an "offer", in order to warm up the session transport and
   prevent media clipping, the preferred handling for a web application
   would be to create and send an "inactive" final answer immediately
   after receiving the offer.  Later, when the called user actually
   accepts the call, the application can create a new "sendrecv" offer
   to update the previous offer/answer pair and start the media flow.
   While this could also be done with an inactive "pranswer", followed
   by a sendrecv "answer", the initial "pranswer" leaves the offer-
   answer exchange open, which means the caller cannot send an updated
   offer during this time.
"

We need an example for this.

**Comment by alvestrand** [comment]
This was presented in Prague with #15 and title "Early Transport Warmup". It's not clear from the discussion that this issue matches the problem being discussed.

**Comment by juberti** [comment]
yes - this was the example that prompted the discussion

**Comment by juberti** [comment]
Prague: Example should be:
Caller: sendrecv offer
Callee: sendonly answer
Callee: sendrecv offer
Caller: sendrecv answer

**Comment by fluffy** [comment]
I think this is more or less fixed by https://github.com/rtcweb-wg/jsep/pull/136

**Comment by juberti** [comment]
Yes - once that lands this can be closed.

**Comment by juberti** [comment]
Note to self: this should be consistent with https://w3c.github.io/webrtc-pc/#simple-peer-to-peer-example-with-warm-up and https://docs.google.com/presentation/d/1PkQy1m47ivvchUkxawgzsqJ0HCh7LGBLVpXSx1qp0Uc/edit#slide=id.gc387eae7e_0_13.

**Comment by juberti** [comment]
Also - initial offer/answer should be relay-only candidates, followed by ice restart in reoffer.
