### ISSUE TITLE
Usage of picture aspect ratio in a=imageattr

### ISSUE THREAD

**Issue by gloinul** [rtcweb-wg/jsep#155]
B. Section 3.6.1:

   Otherwise, an "a=imageattr" attribute is created with "recv"
   direction, and the resulting resolution space formed by intersecting
   the decoder limits and constraints is used to specify its minimum and
   maximum x= and y= values.  If the intersection is the null set, i.e.,
   there are no resolutions that are permitted by both the decoder and
   the mandatory constraints, this SHOULD be represented by x=0 and y=0
   values.

   The rules here express a single set of preferences, and therefore,
   the "a=imageattr" q= value is not important.  It SHOULD be set to
   1.0.

What about end-points that can produce and consume different aspect ratios on its video. Such a system is likely to have different constraints on its min and max resolution in X and Y for 1:1, 4:3, 16:9 and 1:2.35 aspect ratios. It is unclear if that is allowed, and even recommend practice. And in this case there might be a usage for the q value.

**Comment by juberti** [comment]
We will only generate a single a=imageattr, but we might receive multiple, with different q=.

Need to decide how one should handle (for a native 720p stream)
a=imageattr:96 recv [x=1920, y=1080, q=1.1]
a=imageattr:96 recv [x=960, y=720, q=1.0]
a=imageattr:96 recv [x=640, y=360, q=0.9]
a=imageattr:96 recv [x=1280, y=720, q=0.8]

Six possibilities (there are doubtless more):
a) take highest preference; upscale/downscale to fit (q=1.1 above)
b) take highest preference that can be met without upscaling (q=1.0)
c) take highest preference that can be matched without scaling (q=0.8)
d) take highest preference; prefer matching aspect; upscale/downscale to fit (q=1.1)
e) take highest preference that can be met without upscaling; prefer matching aspect (q=0.9)
f) take highest preference that can be matched without scaling; prefer matching aspect (q=0.8)

b) or e) seem like the best chouices. @gloinul thoughts?

**Comment by gloinul** [comment]
First of all q= can only be between 0.00 and 1.00, see ABNF in RFC. 

When it comes to handling the choices I wonder if you need to be as explicit about the choices. I think avoiding upscaling is a good recommendation. The picture aspect ratio is not obvious to me. I think you need to discuss this on the mailing list and possibly meeting.

**Comment by alvestrand** [comment]
Non-orthogonal scaling (changing aspect ratio) will be a surprising transform for users. I think it should be avoided if possible. So i like e).

**Comment by juberti** [comment]
I need to go back and look at the minutes on this one...

**Comment by juberti** [comment]
Prague minutes sayeth:
Proposal: Implementations SHOULD pick imageattr with highest q= value that doesn't
require upscaling.
Outcome: The proposal was agreed, but SHOULD will be changed to MUST.
