### ISSUE TITLE
clarify a=imageattr example

### ISSUE THREAD

**Issue by gloinul** [rtcweb-wg/jsep#157]
C. Section 3.6.1:

   As an example, consider a system with a HD-capable, multiformat video
   decoder, where the application has constrained the received track to
   at most 360p.  In this case, the implemention would generate this
   attribute:

   a=imageattr:* recv [x=[16:640],y=[16:360],q=1.0]

Maybe this example should discuss the minimal aspect of this. What it really is expressing in that it can handle any resolution between 16x16 pixels up to 640x360 as the longest in respective side. No limitations to any picture aspect ratio. That the examples expresses this is missing in the example text.

**Comment by juberti** [comment]
I think this is a realistic example, so I suggest we just add more descriptive text.
