### ISSUE TITLE
a=imageattr limiations and image rotation using CVO

### ISSUE THREAD

**Issue by gloinul** [rtcweb-wg/jsep#158]
E. Section 3.6:

I am missing a discussion on how video orientation affects what one states. Taking the above example with a maximum resolution of 640x360, which gives a landscape 16:9 PAR. If one rotates this, then it is not clear if one is allowed to have 360x640 or are limited to 203x360. Or should one actually state the different orientations maximum resolution and consider that this is simply different PAR, as 16:9 (Landscape) is 9:16 (Portrait) two different picture aspect ratios. 

It needs to be clear if a=imageattr is the limiations of the video being encoded and transmitted or the video being captured/displayed.

**Comment by juberti** [comment]
Magnus looked into this and the proposed interpretation is fine, e.g. imageattr always refers to the unrotated video. However, this needs to be spelled out in the document.

**Comment by fluffy** [comment]
We probably also need to talk about how CVO support is signalled and if the far end does not support CVO then this is a bit different.

**Comment by juberti** [comment]
Right, that can happen. And in that case you would go from sending, say, 1280x720 to 720x1280. To minimize implementation complexity, I think the sender should act (regarding imageattr) as if the recipient supported CVO - that is, if the recipient says it can get 1280x720, we should also allow sending the portrait version (720x1280). Anything else just seems way too complicated.

**Comment by gloinul** [comment]
If the peer do not support CVO, then I think the right thing to do is to include imageattr with 720x1280 as well as 1280x720 if the declaring endpoint can capture both and feed its encoder both directions. However, I don't see a reason to do that prior to having attempted to negotiate CVO and failed.

**Comment by juberti** [comment]
Prague: Do simple thing of only including landscape resolution in imageattr.

**Comment by juberti** [comment]
Not sure if anything remains to be done here.

**Comment by fluffy** [comment]
@gloinul - do you think we need to make any changes? I have lost track of where we are on this one.
