### ISSUE TITLE
Transport stream structure depends on answer to offer when offering bundle.

### ISSUE THREAD

**Issue by gloinul** [rtcweb-wg/jsep#159]
F. Section 4.1.1:

   Regardless of policy, the
   application will always try to negotiate BUNDLE onto a single
   transport, and will offer a single BUNDLE group across all media
   sections.

I think this sentence may be a bit misleading without additional sentence(s) to explain that the actual number of established transport streams will depend on the peer's response to the attempt to bundle.

**Comment by juberti** [comment]
OK. This could be resolved by adding a final sentence of the form "Of course, the answerer can choose whether or not to accept BUNDLE".
