### ISSUE TITLE
Accessors for proposed local/remote description

### ISSUE THREAD

**Issue by ekr** [rtcweb-wg/jsep#16]
JSEP S 4.1.7 and 4.1.8 read:

"   TODO:  Do we need to expose accessors for both the current and
   proposed local description?"

and

"   TODO:  Do we need to expose accessors for both the current and
   proposed remote description?"

**Comment by juberti** [comment]
For the purposes of this comment, let's call the needed APIs .currentLocalDesc and .pendingLocalDesc. 

On the offerer side, setLocal(desc) updates .pendingLocalDesc to be (desc).
On the offerer side, setLocal(rollback) updates .pendingLocalDesc to be NULL.
On the answerer side, setRemote(desc) updates .pendingRemoteDesc to be (desc).
On the answerer side, setRemote(rollback) updates .pendingRemoteDesc to NULL.
On the answerer side, setLocal(desc) updates .currentLocalDesc to be (desc), .currentRemoteDesc to .pendingRemoteDesc, and .pendingRemoteDesc to NULL.
On the offerer side, setRemote(desc) updates .currentRemoteDesc to be (desc), .currentLocalDesc to be .pendingLocalDesc, and .pendingLocalDesc to be NULL.

Unfortunately, both .pending and .current have slightly different semantics than the existing .local/.remoteDescription properties, so I think we would need to retain .local/remote for now. However, they could be polyfilled as propX = (pendingX) ? pendingX : currentX.

**Comment by fluffy** [comment]
This looks good and need to be clear that some while the pending is out, you need to receive on both current and pending.

**Comment by fluffy** [comment]
Not done yet but started putting this into PC spec on branch https://github.com/w3c/webrtc-pc/compare/pendingSdp1 - have a look and see if it is going the right direction

**Comment by jan-ivar** [comment]
> The localDescription attribute MUST return pendingLocalDesc if it is not null and otherwise it MUST return currentLocalDesc. 

and

> The pendingLocalDesc attribute MUST return null if the PeerConnection is in the stable state and otherwise must return the local RTCSessionDescription that is in the process of being negotiated plus any local candidates that have been generated by the ICE Agent since the offer or answer was created.

This PR adds four attributes where only two seem needed to me: `stableLocalDescription` and `stableRemoteDescription` (ice candidates added everywhere).

**Comment by jan-ivar** [comment]
Hi @juberti , why not a simpler 2-arg rather than 3-arg solution? For the purposes of this comment, let's call the needed APIs .localDescription and .stableLocalDescription.

On the offerer side, setLocal(desc) updates .localDescription to be (desc).
On the offerer side, setLocal(rollback) updates .localDescription to be .stableLocalDescription.
On the answerer side, setRemote(desc) updates .remoteDescription to be (desc).
On the answerer side, setRemote(rollback) updates .remoteDescription to be .stableRemoteDescription.
On the answerer side, setLocal(desc) updates .localDescription and .stableLocalDescription to be (desc), and .stableRemoteDescription to be .remoteDescription.
On the offerer side, setRemote(desc) updates .remoteDescription and .stableRemoteDescription to be (desc), and .stableLocalDescription to be .localDescription.

**Comment by juberti** [comment]
I see what you are trying to do, and I think this would work OK, but the fact that the semantics of .localDescription/.remoteDescription mutate depending on the current state make this confusing. (IOW, sometimes localDescription is the stable desc, sometimes it is the pending desc).

I think .current/.pending is the clearest approach, but open to other opinions.

**Comment by jan-ivar** [comment]
I would argue the semantics don't mutate and their availability transcend state:
* `.localDescription` is the last-set description always
* `.stableLocalDescription` is the last negotiated description always

**Comment by fluffy** [comment]
From the point of view of a programmer using the API,  I think that what I want to get is the SDP to do with the current negotiation, and the old SDP that I would roll back to. I tend to think of it as old and new. During transition time, the stuff in use is the combination of the old offer/answer pair plus the new offer.  The stuff .current/.pending  is close enough to this and seems fine to me.

**Comment by jan-ivar** [comment]
Do you realize you just used "current" to refer to "pending", and "old" to refer to "current"?

You want to roll back to the last stable state.

**Comment by fluffy** [comment]
Uh, I used current to refer to old and pending to refer to new.

**Comment by jan-ivar** [comment]
> I think that what I want to get is the SDP to do with the *current* negotiation, and the *old* SDP that I would roll back to.

**Comment by jan-ivar** [comment]
My point is that these relative words "current" and "pending" are not well-defined, whereas "stable" is. KISS.

**Comment by fluffy** [comment]
I'm not sure stable is a word that makes as much sense as you might hope to developers. It is not used int he SDP or Offer/Answer spec. Anyways, I don't feel strongly about this. None of the names are perfect.

**Comment by jan-ivar** [comment]
http://w3c.github.io/webrtc-pc/#idl-def-RTCSignalingState.stable

**Comment by ekr** [comment]
Forgetting about the accessors for a second, the world can be in three basic states.

- There is an initial offer which has not been answered
- There is an offer which has been answered and no outstanding offers
- There is an offer which has been answered and an outstanding offer

In the first two cases, there is only one localdesc, which is either answered or not.
In the second case, there are two localdescs, one confirmed and one answered or not.

As Justin observes, currently localdesc is the most recent description set, regardless of whether it's answered. I find his argument persuasive here. I would prefer that we have two variables:

- Most recent answered description
- Most recent non-answered description

And in some cases either or both of these can be null.
We can obviously keep localdescription around for a while for compat.

I don't feel strongly about the names here, so I won't suggest some just yet. Let's agree on the principle one way or the other.

**Comment by jan-ivar** [comment]
The world can be in four basic states, the fourth being the initial state of no offer at all, which is the only state where "Most recent answered description" would be `null` I hope?

This would fit my understanding of "most recent": while it may be `null` initially (meaning "never been set"), it will never go to `null` after that (which would surprise me). I think we're on the same page here.

> And in some cases either or both of these can be null.

Can "Most recent non-answered description" ever go from non-`null` to `null`? If it can, then lets avoid the false symmetry with the first one:

* Most recent answered description, or `null` if never set.
* Most recent non-answered description if there is one since the last answered description, or `null`.

The first one is `currentLocalDesc` a.k.a. `stableLocalDescription`.

The second one is a temporal variable: it'll only ever be non-`null` *during* re-negotiation, correct? Moreover, *during* re-negotiation, it's indistinguishable from `localDescription`, do I have that right?

So, counting `localDescription` which we have today, we're adding a redundant third temporal variable that all it brings to the table is that it is `null` outside of renegotiation? Am I missing something?

**Comment by ekr** [comment]
On Fri, May 22, 2015 at 11:33 AM, jan-ivar <notifications@github.com> wrote:

> The world can be in four basic states, the fourth being the initial state
> of no offer at all, which is the only state where "Most recent answered
> description" would be null I hope?
>

Yes, then everything is null.



> This would fit my understanding of "most recent": while it may be null
> initially (meaning "never been set"), it will never go to null after that
> (which would surprise me). I think we're on the same page here.
>
> And in some cases either or both of these can be null.
>
> Can "Most recent non-answered description" ever go from non-null to null?
>

No.


> If it can, then lets avoid the false symmetry with the first one:Most
> recent answered description, or null if never set.
>
>    - Most recent non-answered description if there is one since the last
>    answered description, or null.
>
> The first one is currentLocalDesc a.k.a. stableLocalDescription.
>
Yes.


> The second one is a temporal variable: it'll only ever be non-null
> *during* re-negotiation, correct? Moreover, *during* re-negotiation, it's
> indistinguishable from localDescription, do I have that right?
>
 Yes.

So, counting localDescription which we have today, we're adding a redundant
> third temporal variable that all it brings to the table is that it is null
> outside of renegotiation? Am I missing something?
>
What it brings to the table is consistent and explicit meaning; that's not
redundant. You may not value this, but I do.

**Comment by alvestrand** [comment]
What's the value of "most recent non-answered description" after rollback?
(matters for the question of whether it can go from non-null to null)

**Comment by jan-ivar** [comment]
Right, hanging on to a failed description doesn't make much sense, so I see how we got to `null`.

So lets not cut it that way. I think a JS writer cares about:
 1. the last set value, and
 2. the reigning value.

Where rollback rolls back failed set values to the known-good reigning value.

Having `pc.localDescription` itself be the last-set-value matches most attribute patterns I've seen. (e.g. ["On getting, the attribute MUST return the value to which it was last set."](http://www.w3.org/TR/mediacapture-streams/#attributes-1)).

**Comment by ekr** [comment]
The problem with this categorization is that in the case of re-offer, there isn't "the reigning value". Rather, the offerer has two values which are simultaneously valid, so I think Justin's approach is superior. In any case, rather than debate this here, let's discuss it at the interim.

**Comment by fluffy** [comment]
So, given what is being discussed here is about PC spec, I'd sort of like to close this and move the conversation over to PC and not jsep.

**Comment by juberti** [comment]
I agree this overlaps with PC, but given the relevance of this to the overall JSEP O-A model, I think we need to have some description of this in Section 4.1.*

**Comment by alvestrand** [comment]
Personal opinion (not claiming to represent any consensus):
JSEP needs to describe the procedures followed to get the SDP we want.
JSEP shouldn't need to talk about accessors at all; we can leave that to WEBRTC.

What's specified in only one place has a greater chance of being consistent.

**Comment by juberti** [comment]
I find that logic persuasive, in that the accessors are not relevant to the state machine or any other fundamental part of JSEP.

That would imply that 4.1.7 and 4.1.8 ought to be removed from this document, and probably also 4.1.9 (canTrickleIceCandidates, another accessor-like API). @ekr wdyt?

**Comment by ekr** [comment]
I can live with that, but I thought that we had agreed previously that JSEP
would document this stuff and place requirements on the WebRTC API.

**Comment by alvestrand** [comment]
It's perfectly reasonable to have a sentence saying "the API will give access to current and pending SDP and whether or not trickleIce is supported". It's when we get the discussion about what the accessor names should be in 2 different places that I feel like we're not using our time optimally.

**Comment by ekr** [comment]
Well, I suggest we have one discussion and then put it in both places.

On Thu, Jun 18, 2015 at 4:40 AM, Harald Alvestrand <notifications@github.com

**Comment by ekr** [comment]
Consensus in W3C was to have two new accessors. This is editor ready.

**Comment by juberti** [comment]
Resolved by #208
