### ISSUE TITLE
Contradicting statements about a=imageattr between Section 3.6 and 5.2.1

### ISSUE THREAD

**Issue by gloinul** [rtcweb-wg/jsep#160]
G. Section 5.2.1:

This section contains the following:

   Each m= section MUST include the following attribute lines:

   o  If this m= section is for video media, an "a=imageattr" line, as
      specified in Section 3.6.

But, Section 3.6 does not mandate that a=imageattr always is included. Thus the text must be modified to allow the selective inclusion of the attribute based on what needs to be said.

**Comment by juberti** [comment]
Agreed; although 3.6 allows it to be omitted, we should update the text in 5.2.1 to avoid confusion.
