### ISSUE TITLE
Need policy to control whether upscaling is enabled

### ISSUE THREAD

**Issue by juberti** [rtcweb-wg/jsep#165]
For example, some decoders may have min limits, expressed in imageattr. By default, upscaling can be used for this, but there should be some control to turn this off (e.g. don't want to send "HD" video that is just upscaled to HD)

**Comment by fluffy** [comment]
Thoughts on if default should be upscale is allowed or not allowed ?

**Comment by ekr** [comment]
Generally it seems like a bad practice so I would default to not.
