### ISSUE TITLE
Multiple 'a=fingerprint' lines

### ISSUE THREAD

**Issue by stefhak** [rtcweb-wg/jsep#169]
In http://w3c.github.io/webrtc-pc/#dictionary-rtcconfiguration-members 'certificates' is a set, and the PeerConnection selects which certificate to use.

The SDP should have one 'a=fingerprint' line per certificate, and that is not reflected in the JSEP draft AFAICU.

**Comment by juberti** [comment]
Prague: One a=fingerprint line per cert, but we can go down to a single cert one DTLS has been established. The DTLS cert has to match one of the supplied a=fingerprints. (@ekr correct as necessary)

**Comment by ekr** [comment]
PR added for allowing multiples. Processing rules go in the TBD applying section
