### ISSUE TITLE
What should c= be during trickling?

### ISSUE THREAD

**Issue by ekr** [rtcweb-wg/jsep#171]
The question has come up about what the default candidate should be set to during trickle ICE
but after at least one candidate has been gathered so at least in principle you could set c= to one of those candidates. See also;
https://bugzilla.mozilla.org/show_bug.cgi?id=1192813

**Comment by fluffy** [comment]
Want to pick a solution that works even if we we do continous trickle and ice does not finish.

**Comment by ekr** [comment]
Consensus on today's call is:

- Before ICE is completed, follow the 5245 guidance and pick the "best" candidate.
- Once ICE is completed, pick whatever you are actually using.

**Comment by ekr** [comment]
+ If we move to a mode where ICE never completes, perhaps use the active pair.

**Comment by ekr** [comment]
It turns out that this was pretty clear already. I have made it slightly clearer.
