### ISSUE TITLE
Need clarification on ICE restart logic

### ISSUE THREAD

**Issue by juberti** [rtcweb-wg/jsep#179]
From deadbeef@google.com:
_Question 1: Should this be interpreted literally, to mean "the next call, and only the next call to createOffer will generate new ICE credentials"? If so, there are various situations wherein one could encounter unexpected behavior. For example:
Before createOffer is called, a remote offer is received that triggers an ICE restart. Should the next call to createOffer trigger another, superfluous ICE restart?
createOffer is called twice, without setting the local description (and kicking off a new gathering phase). Should the second call generate new credentials, or only the first?
I would propose a slight change, such as: "this will cause subsequent calls to createOffer to generate new ICE credentials, until a new gathering phase has started." This would more clearly represent the intent of the original rule, in my opinion._

_Question 2: The next paragraph states "Any changes to the ICE candidate policy also affect the next gathering phase, in similar fashion to the server changes described above." Does this mean that changes to the candidate policy will also cause an ICE restart, according to the same rules? I assume so, but figure it's worth asking._

**Comment by juberti** [comment]
On #1, any changes should set a needs-ice-restart bit, which is only cleared by setLD with new ICE credentials (although, possibly only by setLD + setRD, since the setLD could be rolled back)

On #2, if the ICE policy is being made more restrictive, no ICE restart is needed. Obvious if less restrictive, then the needs-ice-restart bit will be set.

**Comment by fluffy** [comment]
Both you proposed resolutions look good to me
