### ISSUE TITLE
Interfacing between WebRTC spec and JSEP

### ISSUE THREAD

**Issue by dontcallmedom** [rtcweb-wg/jsep#186]
As alluded in https://github.com/w3c/webrtc-pc/issues/337 , I think it would useful if JSEP stayed away from referring to specific W3C APIs names (methods or properties), and instead defined algorithms that takes well-defined parameters and define a processing model based on these received parameters.

To illustrate this, instead of describing what "createOffer" does when its called the first time, and say that it should look at the MediaSTreams that were added in the order they were added to the peer connection, JSEP could define the "create an initial offer" algorithm, which is called with an ordered lists of sources (mediastreamtracks and data channels), and returns an SDP description or an error. The API would then be responsible to distinguish when to invoke that algorithm vs "create a subsequent offer", and how the ordered list is built.

I think this would simplify the integration of the two documents.

**Comment by ekr** [comment]
Consensus among editor team is that this isn't worth doing at this time and that the current state doesn't create undue confusion
