### ISSUE TITLE
Get rid of msid-semantic

### ISSUE THREAD

**Issue by dontcallmedom** [rtcweb-wg/jsep#188]
JSEP requires sending q=msid-semantics:WMS:
> An "a=msid-semantic:WMS" line MUST be added, as specified in &lt;xref target="I-D.ietf-mmusic-msid">&lt;/xref>, Section 4.

If I read https://tools.ietf.org/html/draft-ietf-mmusic-msid-10 correctly, that is no longer defined, so that requirement should probably go.

I'm happy to provide a PR that removes the requirement, the example usage and updates the reference, but I assume that updating the reference involves more work than just this, so I'll refrain from doing so unless I hear it would still be useful.

**Comment by juberti** [comment]
I think we can just remove this line, and scrub it from the examples. 

More work is probably needed to fix up the refs regarding a=msid, but I think this part should be easy to handle.
