### ISSUE TITLE
ice-options:trickle handling unclear

### ISSUE THREAD

**Issue by stefhak** [rtcweb-wg/jsep#191]
1. JSEP defines this attribute on media level, while 5245 says it is a session level attribute. I understand that there is development ongoing here (e.g. 5245bis), but given that canTrickleIceCandidates is an API on the PeerConnection it makes more sense IMO to have ice-options:trickle on the session level than media line level. If we want this on media line line level, canTrickleIceCandidates should be a (readonly) Transceiver attribute. To that seems messy though, what would happen if Bundle is negotiated but one media line can do trickle but the other not?
2. While the relation between the application of an Answer and canTrickleIceCandidates is spelled out, the same thing should be done for application of an Offer.

**Comment by juberti** [comment]
Decision on 1): simplest thing here is to move ice-options to session level, right after "An "a=msid-semantic:WMS" line MUST be added..."

2) yes, this should be put into handling a remote description, not handling an answer.

**Comment by ekr** [comment]
I can take this.
