### ISSUE TITLE
Vague language on what lines that can be included in answers or subsequent offers

### ISSUE THREAD

**Issue by stefhak** [rtcweb-wg/jsep#192]
It goes something like
```
Each m= section MUST include the following: 
* If present in the offer, an "a=mid" line, ...
```
and so on. But it is not clear if the answer can contain an `a=mid` line if there was none in the offer.

**Comment by ekr** [comment]
Quoth RFC 5888:

9.1.  Mid Value in Answers

   The "mid" attribute is an identifier for a particular media stream.
   Therefore, the "mid" value in the offer MUST be the same as the "mid"
   value in the answer.  Besides, subsequent offers (e.g., in a
   re-INVITE) SHOULD use the same "mid" value for the already existing
   media streams.

So the answer seems to be "no"

**Comment by stefhak** [comment]
Given the quote from 5888, is it fair to conclude that https://github.com/w3c/webrtc-pc/issues/227 should be resolved with "null" for the mid property on the transceiver if there has been no mid in the SDP?

.mid was just an example, the same text is present for e.g. rtcp-mux, ice-option:trickle, rtcp-size.
