### ISSUE TITLE
Ice Candidate Policy should reference ip-handling draft

### ISSUE THREAD

**Issue by juberti** [rtcweb-wg/jsep#194]
https://tools.ietf.org/html/draft-ietf-rtcweb-jsep-12#section-3.4.3 talks about browser local policy. It should make this more concrete by referring to https://tools.ietf.org/html/draft-shieh-rtcweb-ip-handling-00 as the source of this policy.

**Comment by fluffy** [comment]
Do you see it as normatively depending on that or more just "useful implementor advice can be found in ..."

**Comment by juberti** [comment]
I guess it depends on what we think the purpose of the ip-handling draft is. If we think all browsers should implement this, then it should be a normative dependency. I'll make a PR as such and we can debate the details there.

**Comment by fluffy** [comment]
I think if it is something all browser need to implement, then we probably just want to move the normative text into this draft.

**Comment by juberti** [comment]
I think there is enough text that it warrants being in its own document.
