### ISSUE TITLE
Use RID for signaling interactions between primary and RTX/FEC flows

### ISSUE THREAD

**Issue by juberti** [rtcweb-wg/jsep#196]
cc @pthatcherg

**Comment by pthatcherg** [comment]
If the header extension is used, nothing needs to be signalled to correlate source RTP streams with redundancy streams, not even the RID value itself.

**Comment by juberti** [comment]
Yes. We just need to know what to put in the SDP for the createoffer/answer sections.

**Comment by hardie** [comment]
Suggest contacting Christer, Magnus, or Bernard for input.

**Comment by juberti** [comment]
@pthatcherg do you know what the RID SDP needs to look like?

**Comment by suhasHere** [comment]
here is the ABNF we have rid : https://tools.ietf.org/html/draft-ietf-mmusic-rid-00#section-10

**Comment by pthatcherg** [comment]
The result of createOffer should be:

a=rid:A send
a=rid:B send
a=rid:C send 
a=simulcast: send rid=A; B; C

When given an RtpEncodingParmeter like this:

pc.addTransceiver(videoTrack, {
  sendEncodings: [{
    rid: "A",
  }, sendEncodings: [{
    rid: "B",
  }, sendEncodings: [{
    rid: "C",
  }
 ]
});

And if there is only one encoding, we can leave off the a=simulcast line.

In other words, iterate over the encodings of the RtpSender.  If the rid is set, output an a=rid line with the rid value and "send".  If there is more than one encoding, output an a=simulcast line.  

If the browser chooses to support allowing the remote answer to constrain the rid-line via one of the parameters, then it can add that parameter to the rid line.  For example, to support constraining max FPS.

a=rid:A send max-fps
a=rid:B send max-fps
a=rid:C send max-fps
a=simulcast: send rid=A; B; C

But all of those are optional for the browser to support, as far as I know.

createAnswer is very similar to createOffer, except that it must only include rid lines where the rid value already exists in the offer, and skip those that don't.  That's a bit burdensome for the application to know what RID values were in the offer, but not overly so.  


As for receiving simulcast: I think that's out of scope for 1.0, so we don't need to output a=rid lines with "recv".

**Comment by fluffy** [comment]
This looks close to done in PR

**Comment by juberti** [comment]
I think this was resolved in #219.
