### ISSUE TITLE
Reconsider "public"and "none" ICE candidate policies

### ISSUE THREAD

**Issue by juberti** [rtcweb-wg/jsep#203]
From https://tools.ietf.org/html/draft-ietf-rtcweb-jsep-12#section-4.1.1

"public" is probably something the browser should control, not the application.
"none" was previously removed, but apparently Firefox has implemented it.

**Comment by fluffy** [comment]
Keep in mind that anything less than all means that mobile apps will work better than browser apps. Public tries to just reveal what is already revealed simply by browsing the web with no webrtc.

**Comment by juberti** [comment]
Right, but that's what "all" does when the browser is configured as recommended by draft-rtcweb-shieh-ip-handling. It's not clear why a "public" mode also needs to exist; the point of this draft is to protect the user from the application, so we can't really give the app the ability to choose whether it wants non-public addresses.

I think the real remaining question is whether "none" is worth keeping.

**Comment by ekr** [comment]
I think the motivation for "none" was a lot stronger when we had automatic gathering prior to setLD() in some situations. Now, it seems like you can just get the same effect by deferring setLD(). I agree that "public" is silly.
