### ISSUE TITLE
Automatic update of gh-pages seems broken

### ISSUE THREAD

**Issue by juberti** [rtcweb-wg/jsep#205]
I don't understand how the cibot is supposed to work - Eric, can you take a look?

**Comment by juberti** [comment]
I noticed this when browsing the branches and seeing that gh-pages hasn't been updated in 3 months.

**Comment by ekr** [comment]
Yeah, the problem here is that we don't want to update on non-master branch
updates.
Will take a look.

**Comment by martinthomson** [comment]
If you like, I can dump a new version of my i-d-template on here.  That has a feature where it can build branches other than master and push to gh-pages for previewing changes.

**Comment by ekr** [comment]
MT, what we want is the opposite: ONLY build if you are on master.

Can your template do that?

**Comment by martinthomson** [comment]
The template ensures that you don't build on updates to gh-pages, if that is your concern.  Or do you have other non-master branches that have crap on them?

**Comment by ekr** [comment]
Yeah, we have people pushing to topic branches on gh and not on their own
repo

**Comment by martinthomson** [comment]
Is there a reason that you wouldn't you want that to be built, reported on and available on github pages?

**Comment by ekr** [comment]
Well, things on topic branches are just PRs, so they shouldn't be in the
editor's draft.

**Comment by martinthomson** [comment]
They wouldn't be.  The process creates a new folder with the same name as the branch and puts a copy of the files there.  For example: https://martinthomson.github.io/webpush-vapid/jwt-only/

**Comment by ekr** [comment]
Should be fixed now.
