### ISSUE TITLE
Add support for explicitly disabling VAD via RTPSender

### ISSUE THREAD

**Issue by ekr** [rtcweb-wg/jsep#206]
We agreed on the call that it is important for JS apps to be able
to tell the browser not to do VAD when sending.This should be a frob on
RtpSender.

**Comment by juberti** [comment]
e.g. RtpEncodingParameters.vad or some such (i.e., similar to RtpEncodingParameters.fec)

**Comment by juberti** [comment]
By default, the vad setting would be dictated by the remote SDP, e.g. either through presence of CN, or usedtx=1.

We may need to spell this out in the handling-a-remote-desc section.

**Comment by fluffy** [comment]
Need to land https://github.com/rtcweb-wg/jsep/pull/215 first

**Comment by juberti** [comment]
The API point should go into the w3c doc. The remote description handling should be covered by #233.

**Comment by aboba** [comment]
W3C PR has been merged: https://github.com/w3c/webrtc-pc/pull/734

**Comment by fluffy** [comment]
still needs work to  add CN stuff
