### ISSUE TITLE
Add a requirement to respect preferences for no silence suppression

### ISSUE THREAD

**Issue by ekr** [rtcweb-wg/jsep#207]
In some codecs (e.g., Opus) requests to not do silence suppression are
advisory. We should consider whether we require browsers to respect
them so that counterparties which need the browser to not do silence
suppression can force that.

**Comment by juberti** [comment]
I think it would make the most sense for this to behave identically regardless of codec. IOW, if not offered, it can't be indicated in the answer.

The answer can of course reject a proposal to use VAD (currently via AnswerOptions), but there could perhaps be another surface for this.

**Comment by juberti** [comment]
Decision in Kirkland: if offer indicates no VAD (either through lack of CN, or usedtx=0), answer MUST not specify VAD. This is done on a per-codec basis, e.g. if answerer receives CN + usedtx=0, and answerer says Vad:True, answer will have CN + usedtx=0.

**Comment by juberti** [comment]
Fixed by #202
