### ISSUE TITLE
Define what effects RtpSender.setParameters has

### ISSUE THREAD

**Issue by pthatcherg** [rtcweb-wg/jsep#212]
RtpSender.setParameters can change codecs, maxBandwidth per Source RTP Stream, maxFramerate per Source RTP Stream, and maybe some other things.  We should define how those interact with the parameters processed in SetLocalDescription and SetRemoteDescription.

**Comment by juberti** [comment]
This would probably affect the language in Applying An Answer, where the discussion around how to send a Source RTP Stream would have to take these parameters into account.

I assume that any received TIAS value would clamp any specified value; however, I assume any specified codec would trump any received codec preference.

**Comment by juberti** [comment]
@aboba, how do you see the RtpEncodingParameters interacting with the received SDP values? (http://w3c.github.io/webrtc-pc/#idl-def-rtcrtpencodingparameters)

That is, does an b=AS:X constrain what the sender can set using RtpEncodingParameters.maxBitrate?

**Comment by taylor-b** [comment]
Our implementation currently is to take the minimum of the various maximums. But setting a "maxBitrate" higher than "b=AS" doesn't cause an error.

**Comment by juberti** [comment]
@taylor-b , what do you think JSEP needs to say about this? I don't think it needs to detail all the ways in which params can affect the encoding, but any interactions with SDP-expressed limits should be mentioned.

**Comment by taylor-b** [comment]
I don't think JSEP needs anything. We can just specify in webrtc-pc that maxBitrate is an additional constraint, on top of any existing bitrate constraints as described by JSEP.

**Comment by juberti** [comment]
Sold. Closing this accordingly.
