### ISSUE TITLE
MIDs in ICE for object when offer had no MIDs

### ISSUE THREAD

**Issue by fluffy** [rtcweb-wg/jsep#213]
If the browser receives and Offer with no MIDs, what does it put in the ICE objects. Text is last para of "ICE Candidate Format" requires unique MIDs. 

Perhaps this is a dup of other issues.... just flagging for now.

**Comment by fluffy** [comment]
Conclusion is we will create a random MID if there is none in the offer.

**Comment by juberti** [comment]
Right. The callee will still generate mids, it just won't put them into SDP. These generated mids will show up in the ICE candidates.

**Comment by fluffy** [comment]
The JSEP draft is clear that if MIDs are generated in the offer. If the received offer has a MID, this is used and put in the answer. And if the the offer does not have a MID, the answer will not have a MID but the ICE candidate objects will have a an local generated one. 

So I think this can be closed.

**Comment by ekr** [comment]
SGTM. Closing.
