### ISSUE TITLE
Candiates in use on Policy Change

### ISSUE THREAD

**Issue by fluffy** [rtcweb-wg/jsep#214]
If a candidate is in use and Policy changes such that this candidate is not longer allowed, do we have text that says to stop using that candidate and restart ice?

**Comment by juberti** [comment]
yes, I think this is covered in the setConfiguration text. Do you want to look and see if there is anything missing?

**Comment by juberti** [comment]
The current text says no ICE restart happens here, and it's not clear it should, since the cat is already out of the bag. Eric is going to look at adding a warning mentioning this.

**Comment by juberti** [comment]
Discussed in Kirkland and we think it is simplest to trigger ICE restart regardless of which way the policy changes.
