### ISSUE TITLE
Resolve TODO: list of ABNF references

### ISSUE THREAD

**Issue by juberti** [rtcweb-wg/jsep#226]
http://rtcweb-wg.github.io/jsep/#sec.parsing-a-desc
[TODO: ensure that every line is listed below.]

**Comment by juberti** [comment]
This TODO is really related to #227. But leaving it open to track some cleanup around the intro to section 5.6, and how we need to talk about the first stage being ABNF validation followed by actual parsing. In this part we also need to specifically call out the ABNF for the foo= lines, in addition to the attributes.

**Comment by hardie** [comment]
5.6 currently says:

  For each line, the  implementation will first ensure it is syntactically correct
   according its defining ABNF, check that it conforms to [RFC4566] and
   [RFC3264] semantics, and then either parse and store or discard the
   provided value, as described below.  A partial list of ABNF
   definitions for SDP attributes can found in:
 [Table]

This seems to be adequate to describe the sequence of steps required by Justin's comment above.  Can this be closed?

**Comment by fluffy** [comment]
I think once we get all the SDP stuff in so we know we are referencing all the required SDP RFCs, we should do a final check to to make sure all the normatively referenced drafts ended up in the table. We could easily do a first WGLC before that. I don't actually care if they do make the table because they are still normatively referenced and implementers can go find them but I think others wanted to make sure this table was complete.

**Comment by juberti** [comment]
I had a specific cleanup in mind here, but I forget the details. I will take another look over this section and update or close as appropriate

**Comment by juberti** [comment]
Re-reading, I just think an editorial pass is needed to clean up some unclear segues. Working on it now.

**Comment by juberti** [comment]
Also - reading more closely - it's not clear what the point of the table in this section is. It's basically a duplication of the parsing guidance below, pointing to the same sections. 

We could keep it as an easy reference, but we don't do this for other sections (e.g. createOffer). @fluffy, do you recall the intent here?

**Comment by fluffy** [comment]
action - move the table to appendix ?
