### ISSUE TITLE
Resolve TODO: a=setup value for reoffers

### ISSUE THREAD

**Issue by juberti** [rtcweb-wg/jsep#230]
Related to #72: need to figure out if actpass is the right thing to offer.

http://rtcweb-wg.github.io/jsep/#rfc.section.5.6.3
[TODO: may need revision, i.e., use of actpass]

**Comment by ekr** [comment]
I've been holding off on this because of the confusion around the dtls-connection attribute

**Comment by fluffy** [comment]
Will document in DTLS SDP draft and we can point to that from here.

**Comment by hardie** [comment]
DTLS SDP shows as having achieved working group consensus and is waiting for writer; can the pointer required to resolve this go in now?  Is reference to DTLS-SDP here:

DTLS setup value, which MUST be set according to the rules specified in [RFC5763], Section 5, and MUST be consistent with the selected role of the current DTLS connection, if one exists.

Enough, or is text needed?

**Comment by cdh4u** [comment]
When it comes to the data channel, I assume SCTP SDP (which will reference DTLS SDP) will be referenced?

**Comment by juberti** [comment]
Don't understand the SCTP SDP comment.

**Comment by cdh4u** [comment]
The usage of the setup attribute for data channels (SCTP over DTLS) is described in draft-SCTP-SDP.

**Comment by ekr** [comment]
Closed by https://github.com/rtcweb-wg/jsep/commit/22c1540793fdb8a5b563f3c87f5a02c5b11d598a
