### ISSUE TITLE
Resolve TODO: expand on 'establish a mapping'

### ISSUE THREAD

**Issue by juberti** [rtcweb-wg/jsep#232]
http://rtcweb-wg.github.io/jsep/#rfc.section.5.8

For each specified payload type that is also supported by the local implementation, establish a mapping between the payload type ID and the actual media format. 
[TODO - Justin to add more to explain mapping.]

 If any indicated payload type is unknown, it MUST be ignored.
 [TODO: should fail on answers]

**Comment by hardie** [comment]
Aggregated in omnibus 5.8 punchilst
