### ISSUE TITLE
Section 5.8: handling of special payload types

### ISSUE THREAD

**Issue by juberti** [rtcweb-wg/jsep#233]
http://rtcweb-wg.github.io/jsep/#rfc.section.5.8
[TODO: handling of CN, telephone-event, "red"]

**Comment by juberti** [comment]
Should also cover usedtx=1 in this section

**Comment by hardie** [comment]
Section 5.8 has the following TODOs:

1) If the media section proto value indicates use of RTP:
      *  [TODO: header extensions]
2)       *  For each specified payload type that is also supported by the
         local implementation, establish a mapping between the payload
         type ID and the actual media format.  [TODO - Justin to add
         more to explain mapping.]  
3.  If any indicated payload type is  unknown, it MUST be ignored.  [TODO: should fail on answers]

4.    *  [TODO: handling of CN, telephone-event, "red"]

**Comment by juberti** [comment]
Making individual issues for each TODO here
