### ISSUE TITLE
Nail down specifics in Section 6 (configurable SDP params)

### ISSUE THREAD

**Issue by juberti** [rtcweb-wg/jsep#235]
http://rtcweb-wg.github.io/jsep/#rfc.section.6
[[OPEN ISSUE: This is a placeholder for other modifications, which we may continue adding as use cases appear.]]

**Comment by ekr** [comment]
this seems like it needs a proposal for discussion in BA

**Comment by alvestrand** [comment]
The final proposal in RTCWEB at BA was "disallow all post-CreateOffer SDP munging for local offers/answers, period".
This achieved WG consensus (as far as I can tell).

**Comment by juberti** [comment]
Yes. The rationale, for posterity:
- New APIs have been added to control things that previously required SDP munging (e.g. reordering codecs)
- We want to encourage these APIs instead of SDP munging
- Applications that want to go "low-level" can drop down and use WebRTC NV APIs.

Lastly, some of the things that can be done with SDP munging can still be done post-setLD (e.g. reordering or removing codecs).

**Comment by hardie** [comment]
I believe that this issue is closed, as I believe the WG came to the consensus that Harald describes above.   If there is a different reason why this is open, pleae re-open and add.
