### ISSUE TITLE
Clarify a=rtcp processing on page 52

### ISSUE THREAD

**Issue by juberti** [rtcweb-wg/jsep#249]
From the interim, there was some confusion on whether ignoring a=rtcp prohibited unmuxed RTCP; the intention here was that a=rtcp is superfluous because the RTCP port/IP information is carried in a=candidate lines.

Suggest we just spell out this rationale explicitly.

**Comment by juberti** [comment]
That is, unless we use a=rtcp:0 to indicate exclusive.

**Comment by hardie** [comment]
This appears to be section 5.6.2's statement:

  If present, a single "a=rtcp" attribute MUST be parsed as
      specified in [RFC3605], Section 2.1, but its value is ignored.

(This is no longer on page 52)

Would   

    If present, a single "a=rtcp" attribute MUST be parsed as
      specified in [RFC3605], Section 2.1, but its value is ignored
    in favor of RTCP information carried in a=candidate lines

work?

**Comment by fluffy** [comment]
Perhaps we need something more like 

`If present, a single "a=rtcp" attribute MUST be parsed as specified in [RFC3605], Section 2.1, but its value is ignored if RTCP is being multiplexed with the RTP`
