### ISSUE TITLE
Permit changing of ICE credentials

### ISSUE THREAD

**Issue by martinthomson** [rtcweb-wg/jsep#25]
The text currently forbids changing of ICE credentials.  There's an argument that states this is no longer necessary since DTLS is mandatory.  We should resolve this point.

**Comment by fluffy** [comment]
Seems like this is covered (and fixed) in sec.icerestart - Can we close this ?

**Comment by juberti** [comment]
This is part of the section 6 discussion that we have never really settled (i.e. not sec.icerestart). We probably just need to go over section 6 and decide on what our policy should be on changing SDP fields that go against what the browser decided, but still result in legal SDP.

**Comment by juberti** [comment]
Overall section 6 questions covered by #235

**Comment by juberti** [comment]
Closing per discussion in #235.
