### ISSUE TITLE
Need to clarify behavior of addIceCandidate around an ICE restart.

### ISSUE THREAD

**Issue by taylor-b** [rtcweb-wg/jsep#251]
Consider the following sequence of actions:

setRemoteDescription(offer_with_ice_restart);
addIceCandidate(candidate);
setLocalDescription(answer_with_ice_restart);

As issue #250 describes, when the remote peer has set an offer with an ICE restart, but has not yet set an answer, it's doing ICE processing for both the new and old "generations" simultaneously (assuming we go that route). So, is this a candidate for the new or old generation? If "old", then it can be applied immediately. Otherwise, it should be queued and only applied after setting the local description, since the local description is what triggers the ICE restart.

Of course, there's a separate issue, which is that there's no way of telling which "generation" the candidate applies to. One proposed way of fixing this is to trickle a ufrag/password along with the candidate.

Another way would be to queue the candidates from the "old generation" before signaling them, and only signal them after rolling back the local description. If instead of rolling back the local description, an answer is applied, these queued old candidates would be discarded. This way, once a candidate is signaled, it unambiguously applies to only the newest generation.

Note that the "candidate" could also be an end-of-candidates indication, and the same reasoning applies.

**Comment by juberti** [comment]
Honghai already has considered how to associate candidates with ufrag/pwds. However, I think in the absence of such markings, the candidate should be associated with the new generation, since the offer specified ICE restart and the candidate followed the offer.

**Comment by taylor-b** [comment]
I agree. Thus, if an endpoint gathers a candidate for an old generation (and doesn't have a mechanism to associate it with a ufrag/pwd), it should only signal the candidate if and when the local description that triggered the ICE restart gets rolled back. That's what I was trying to explain in the second-to-last paragraph.

**Comment by juberti** [comment]
In ICE, we agreed to have a ufrag parameter on the candidate. Where that parameter goes is still TBD; it could be in a=candidate or on RTCIceCandidate. But this makes it clear what the JSEP implementation should do in this case.

**Comment by juberti** [comment]
The ufrag parameter would need to apply to a=end-of-candidates as well.

**Comment by taylor-b** [comment]
This is good news. But now we need to go back to the drawing board with trickling end-of-candidates. If the ufrag needs to be trickled, we can't just trickle a "null" candidate. And we can't trickle a single special candidate with a ufrag, because different media descriptions could have different ufrags.

**Comment by juberti** [comment]
:-/

Perhaps we could generate individual end-of-candidates objects, followed by a null for backcompat. 

The null would serve as an implicit end-of-candidates for the current ufrag, but new apps would never use the null.

**Comment by fluffy** [comment]
I think I lean towards having the trickle candidates strongly tied to a ufrag/pwd.

**Comment by taylor-b** [comment]
To provide an update on this issue:

I think we still want to clarify that if there's a pending ICE restart initiated by the remote peer, any remote candidates from the new "ICE negotiation session" should be queued and only processed by the local ICE agent once the stable signaling state is reached. I don't think this can go in the trickle ICE spec, because trickle ICE has no concept of a pending ICE restart (it's a consequence of having the ability to roll back an ICE restart offer).

Also, last I heard the decision was to trickle the ufrag and mid along with end-of-candidates indications. So the second paragraph off the `addIceCandidate` section will need to be changed to reflect this; it's no longer one indication "for all media descriptions in the last remote description".

**Comment by ekr** [comment]
I've dealt with the second paragraph in PR #312.

The first seems mostly like a "can't happen" to me. As an offerer, you should not be receiving candidates before the answer (that indicates a signaling channel reordering issue). I suppose in principle as an answerer you could receive ice candidates while thinking about the offer, but I think that the answer there is you just discard them.

**Comment by juberti** [comment]
See also #293
