### ISSUE TITLE
Need to document API points for RtpSender/RtpReceiver

### ISSUE THREAD

**Issue by juberti** [rtcweb-wg/jsep#261]
In section 4, Interface, the PC methods are listed but not the sender/receiver/transceiver methods.

**Comment by juberti** [comment]
I think we need to call out:
- PC.addTrack
- RtpSender.active, .mid
- RtpReceiver.active, .mid
- RtpTransceiver.mid, stop(). Maybe .sender, .receiver

**Comment by taylor-b** [comment]
Should JSEP also describe when properties of an RtpSender/RtpReceiver (transport and rtcpTransport for instance) are updated? Presumably in "applying a local/remote description"?

**Comment by juberti** [comment]
I'd prefer not to have to clone everything from webrtc-pc into JSEP. Properties that aren't relevant to SDP can hopefully be omitted.

**Comment by juberti** [comment]
Eric added placeholders for addTrack, addTransceiver, createDataChannel today.

**Comment by ekr** [comment]
@juberti I have written the above sections (and in any case there are placeholders and associated GH issues). Can we close this issue?

**Comment by juberti** [comment]
I think we still need .stop for the transceiver, and maybe the .mid and .active getters.

**Comment by pthatcherg** [comment]
An RtpSender/RtpReceiver doesn't have an .active or .mid, so I don't think we need to add anything for them. 

RtpTransceiver has .stop(), which makes the port 0.  I'll add that. 
RtpTransceiver also has .setDirection, which changes the m= line direction.  I'll add that.

I think that's all we need.

**Comment by pthatcherg** [comment]
Oh, there's a big one we forgot: setCodecPreferences.
