### ISSUE TITLE
Should probably list CNAME in the "un-modifiable" SDP parameters list

### ISSUE THREAD

**Issue by taylor-b** [rtcweb-wg/jsep#268]
draft-ietf-rtcweb-rtp-usage says:

> a WebRTC Endpoint MUST NOT use more than one RTCP CNAME in the RTP sessions belonging to single RTCPeerConnection

So it doesn't make sense to allow it to be changed. Unless someone can think of a reason why an application would care about its value in the initial offer/answer.

**Comment by juberti** [comment]
Closing this per #235.
