### ISSUE TITLE
Multiple t= sections

### ISSUE THREAD

**Issue by martinthomson** [rtcweb-wg/jsep#27]
We should probably not include these.  Not clear what we want to do if someone has set values.

**Comment by fluffy** [comment]
I think the current JSEP is fine and no change needed.We generate t=, we basically ignore it when used, and the ABNF check will detect errors when it is wrong.

**Comment by adamroach** [comment]
I sent my comments to the list; in short, I agree with Cullen: http://www.ietf.org/mail-archive/web/rtcweb/current/msg14428.html

**Comment by ekr** [comment]
Per comments, closing
