### ISSUE TITLE
Clarify what happens if the MID for a candidate is faulty

### ISSUE THREAD

**Issue by stefhak** [rtcweb-wg/jsep#272]
The spec is clear on that the MID has precedence over m= line index when coordinating candidates with m= lines. But it is not clear on what would happen if the MID has a value can't be matched to an m= line (while potentially the m= line index is valid).

**Comment by fluffy** [comment]
I suspect that should result in some sort of invalid value error.

**Comment by juberti** [comment]
Right, I think we should return an error from addIceCandidate in this case. If you wanted a different result, you should have used the correct mid :-)

**Comment by stefhak** [comment]
I agree to the above, just want it clarified.
