### ISSUE TITLE
Use consistent terminology for 'browser' / 'endpoint' / 'implementation'

### ISSUE THREAD

**Issue by juberti** [rtcweb-wg/jsep#281]
We currently aren't consistent in how we refer to the thing that actually implements JSEP. We use 'browser' in some places, 'JSEP implementation' in others, and probably 'endpoint' in a few places.

Browser seems overly specific, since there are many WebRTC mobile endpoints. Implementation is a bit clunky. But let's pick one and be consistent.

**Comment by ekr** [comment]
I suggest "endpoint" or "JSEP endpoint" where there is a need to distinguish between JSEP and non-JSEP gear (e.g., existing SIP softphones)

**Comment by ekr** [comment]
@juberti if you are happy with this, I will do the editorial work for it.

**Comment by juberti** [comment]
Your proposal LGTM

**Comment by juberti** [comment]
Discussed in Seattle: implementation is the WebRTC runtime, endpoint = implementation + app code. Browser is probably WebRTC runtime + general web runtime + application (although it could be argued the app is distinct from the browser)

**Comment by juberti** [comment]
@ekr, is this closed by #492?

**Comment by juberti** [comment]
ping @ekr

**Comment by juberti** [comment]
Closing per discussion this morning.
