### ISSUE TITLE
Define 'apply an ICE candidate' for WebRTC

### ISSUE THREAD

**Issue by burnburn** [rtcweb-wg/jsep#283]
The WebRTC spec says, in the addIceCandidate description:

"We probably want to define the process to 'apply an ICE candidate' in JSEP and link to it above. "

Although JSEP 3.5 talks extensively about ICE, it might be difficult for a new reader to figure out what 'apply an ICE candidate' means.  Adding that specific wording in JSEP might be helpful.

**Comment by ekr** [comment]
I would suggest that instead we change the WebRTC spec to say "add an ICE candidate"

**Comment by fluffy** [comment]
and point at "Add Ice Candiate" secion

**Comment by ekr** [comment]
FWIW, currently 4.1.16

**Comment by juberti** [comment]
http://rtcweb-wg.github.io/jsep/#rfc.section.4.1.16

**Comment by burnburn** [comment]
Works for me.
