### ISSUE TITLE
Missing verb

### ISSUE THREAD

**Issue by burnburn** [rtcweb-wg/jsep#284]
In section 5.2.1 it says 

'If the RtpTransceiver's RtpSender is active, and the application has specified RID values or has specified more than one encoding in the RtpSenders's parameters, an "a=rid" line for each encoding specified.'

Presumably there should be a "MUST be provided" or similar inserted.

**Comment by juberti** [comment]
If you look on page 33, there's a heading which says

>    Each m= section MUST include the following attribute lines:

with a following list of lines, including the a=rid line that you mention.

As such, I think this is written as intended. Thoughts?

**Comment by ekr** [comment]
I agree with Justin here. It's not ideal, of course, because this list is long, but I don't want to have a "must be added" boilerplate on each of thes.e

**Comment by burnburn** [comment]
Yep, missed that.  Thanks!  Closing.
