### ISSUE TITLE
Need JSEP anchor for receipt of multiple encodings

### ISSUE THREAD

**Issue by burnburn** [rtcweb-wg/jsep#285]
In WebRTC section 5.1, addTransceiver(), it says

'When setRemoteDescription is called with a corresponding remote description that is able to receive multiple RTP encodings as defined in \[JSEP\], the RTCRtpSender may send multiple RTP encodings and the parameters retrieved via the transceiver’s sender.getParameters() will reflect the encodings negotiated.'

It is not obvious what to use as the JSEP reference because there does not seem to be a single place that talks about receipt of multiple encodings.

**Comment by alvestrand** [comment]
The specification of signalling that you can recevie multiple encodings seems to belong in either the RID spec or the JSEP spec.
A decision was made some time back that WebRTC entities are only required to support receiving one incoming stream, but all the specs need to be clear on what that means in practice.

**Comment by fluffy** [comment]
I think it makes sense for us to add some text in JSEP for this and create a link

**Comment by juberti** [comment]
Right now we're deciding between making the pointer go to the simulcast document, or adding a new section in JSEP section 3 that would give an overview of simulcast.
