### ISSUE TITLE
Review addTrack track assignment algorithm

### ISSUE THREAD

**Issue by juberti** [rtcweb-wg/jsep#288]
> The track will be attached to the first compatible transceiver
> (of the same media type) which has never had a direction of
> "sendonly" or "sendrecv". If no such transceiver exists,
> then one will be constructed as described in
> <xref target="sec.addTransceiver"/>.

The reuse of 'recvonly'/'inactive' m= lines may not be correct, as this would require renegotiation of the various parameters of an already established m= line. But this may affect the W3C spec too.

**Comment by pthatcherg** [comment]
Wouldn't this be solved with your suggestion at IETF 96?  The text I suggested based on that suggestion was:


1. Transceivers have a "usable by addTrack" flag.
2. Transceivers created by setRemoteDescription have it set to true and all others have it set to false.
3. addTrack using it sets the flag to false.
4. Going to the stable state causes all transceivers to have their flag set
to false.


If we use that text, then the direction doesn't matter and this issue is solved.

**Comment by ekr** [comment]
@pthatcherg doesn't point 4 have the property that a transceiver added with recvonly by setRD will never be able to be used with addTrack in a new offer? I'm not saying that that's necessarily bad, but it seems like it's a pretty significant change.

**Comment by ekr** [comment]
Resolution at Berlin was that @pthatcherg and @juberti were to produce some text and send to the list. @pthatcherg is this that?

**Comment by juberti** [comment]
Peter's text in his comment above is an improvement over my suggestion from IETF 96, since it prevents accidental reuse during a reoffer.

My original text, from https://docs.google.com/presentation/d/1Ay80ztS2eMtnKWcUA7Q91uai9ICQTgrfMbZsjquQpN8/edit#slide=id.g155b90bad5_0_101:

> If the PeerConnection is in the have-remote-offer state, the track will be attached to the first compatible transceiver that was created by setRemoteDescription and does not have a local track. Otherwise, a new transceiver will be created.

**Comment by juberti** [comment]
Looking at it again, I think my text would be sufficient, as long as we say 'the first compatible transceiver that was created by the most recent setRemoteDescription'. Then we avoid some of the W3C-ness of Peter's algorithm, while maintaining the same meaning.

**Comment by juberti** [comment]
Justin to email list with this clarification, as requested at IETF 96.

**Comment by pthatcherg** [comment]
OK, how about this tweak of the text?

"If the PeerConnection is in the have-remote-offer state and the most recent call to setRemoteDescription created compatible transceivers that currently have no local track attached, attach to the first such transceiver.  If there is no such transceiver, create a new one."

I think that would work for me.  

By the way this conflicts with the W3C spec, so we'll have to fix the W3C spec.

**Comment by ekr** [comment]
@juberti: where are you on this?

**Comment by ekr** [comment]
@juberti, @fluffy I propose we just write this up and land it and then we can take it out if the WG hates it.

**Comment by fluffy** [comment]
SGTM
