### ISSUE TITLE
Detail out the steps for addIceCandidate

### ISSUE THREAD

**Issue by stefhak** [rtcweb-wg/jsep#290]
I think it would be very helpful if there was a separate section about applying an IceCandidate (as there now is for e.g. "applying a local description"). Here the processing and checking of the candidate can be spelled out.
All there is now is section 4.1.16 that among other things says "...if parsed successfully..." but there is little info on how to parse.

**Comment by ekr** [comment]
Well, this should just point to trickle ICE, but I can write something.

**Comment by ekr** [comment]
This has already been written.
