### ISSUE TITLE
Need description of behavior upon end of candidates

### ISSUE THREAD

**Issue by burnburn** [rtcweb-wg/jsep#293]
The WebRTC spec says in the description for RTCIceTransportState in section 5.6 (RTCIceTransportInterface):

"The failed and completed states require an indication that there are no additional remote candidates. This can be indicated either by canTrickleIceCandidates being set to false, or the processing of an end-of-candidates indication as described in [JSEP]."

I looked in JSEP 3.5.2 (ICE Candidate Trickling) and didn't see any text there about what to do upon receiving an end-of-candidates indication.  I wasn't sure where to look elsewhere in the spec for it, and in poking around I wasn't able to find it.  I could easily have missed it, but if not there should be both text describing behavior upon end-of-candidates indication and also a pointer to that text from 3.5.2.

Issue https://github.com/w3c/webrtc-pc/issues/723 depends on the resolution of this one.

**Comment by taylor-b** [comment]
I believe the relevant parts of JSEP are this paragraph from section 4.1.13:

>    This method can also be used to provide an end-of-candidates
>    indication (as defined in [I-D.ietf-ice-trickle]) to the ICE Agent
>    for all media descriptions in the last remote description.

And this paragraph from section 5.8:

>    o  If an "a=end-of-candidates" attribute is present, process the end-
>       of-candidates indication as described in [I-D.ietf-ice-trickle]
>       Section 11.

Can these simply be referenced from 3.5.2, or is more explanation required? Should JSEP directly explain how the end-of-candidates indication impacts RTCIceTransport.state?

**Comment by burnburn** [comment]
Wow, that was a major search failure on my part.  Let's give it a day or so to see what others think would be best.  In the end I need one or more appropriate references I can use in the WebRTC spec.

**Comment by aboba** [comment]
Shouldn't the WebRTC 1.0 text also reference calling addIceCandidate with a null value for candidate?

**Comment by taylor-b** [comment]
Doesn't it already?

> If candidate is null, the User Agent must queue a task that runs the following steps:
>
> 1. For each media description in the last successfully applied remote description, perform the  processing for an end-of-candidates indication for said media description as defined in [TRICKLE-ICE].

**Comment by juberti** [comment]
IETF 96: 4.1.16 should indicate that addIceCandidate can take an RTCIceCandidate 'type': 'end' (and maybe allude to this in Section 3's discussion of ICE as well)

**Comment by ekr** [comment]
@juberti I think this is actually handled OK by:
http://rtcweb-wg.github.io/jsep/#sec.addicecandidate. Do you think we can close?

**Comment by juberti** [comment]
I think the second para in 4.1.16 needs to be expanded to indicate that a partial-EOC can also be received (i.e. per-ufrag-mid tuple)

**Comment by ekr** [comment]
OK, will see what I can do.
