### ISSUE TITLE
a=fingerprint and a=bundle-only

### ISSUE THREAD

**Issue by martinthomson** [rtcweb-wg/jsep#295]
These are mutually exclusive, according to the latest bundle draft.  JSEP requires `a=fingerprint` on every media section, which is incorrect.

**Comment by juberti** [comment]
yes - JSEP mandates this in 5.2.1, so this will need to change.

**Comment by cdh4u** [comment]
If an m- line contains a unique address, a=fingerprint must be included. This is normally the case in the initial offer (or when a new m- line is added to a session at some point). Only when an m- line contains a shared address (i.e. the m- line has previously been accepted into a bundle group), or when an m- line is bundle-only, one does not include a=fingerprint (or any other IDENTICAL or TRANSPORT category SDP attributes).

**Comment by fluffy** [comment]
EKR working on PR for this

**Comment by ekr** [comment]
Fixed
