### ISSUE TITLE
Don't mandate a=rtcp

### ISSUE THREAD

**Issue by martinthomson** [rtcweb-wg/jsep#296]
Bundle says that you cannot include `a=rtcp` with bundled media sections.

JSEP requires it on every line.  That's probably wrong.

If the bundle spec changes (that might happen), then this can be closed with no action.

**Comment by juberti** [comment]
It's not clear why BUNDLE needs to indicate this. It should probably delegate to the rtcp-mux spec, which doesn't forbid a=rtcp.

**Comment by hardie** [comment]
Asked Christer to confirm resolution in external docs on August 12th.  Closure pending his confirmation.

**Comment by cdh4u** [comment]
BUNDLE says that, before an m- line has been accepted into a BUNDLE group, one may associate a=rtcp with the m- line in an offer.

The only exception is bundle-only m- lines, that won't be used to begin with unless it is accepted into a BUNDLE group (in which case RTP/RTCP mux will be used). I guess we could allow a=rtcp also in bundle-only m- lines, using the same port value as in the m- line, but I see no reason for that.

BUNDLE also says that, if an offerered m- line is accepted into a BUNDLE group, the answerer must not associated a=rtcp in the answer.

**Comment by cdh4u** [comment]
Also, if you offer rtcp-mux-only, I see no reason to include a=rtcp. However, draft-mux-only does allow it, but you must use the same port value as in the m- line.

**Comment by fluffy** [comment]
If the other side does not support the rtcp-mux-only attribute, I think this is going to end up really weird if we don't also signal the a=rtcp

**Comment by ekr** [comment]
Consensus from today's editor discussion:

a=rtcp:
Offers must contain it. Answers shouldn't (because it's useless)

a=rtcp-mux
Offers and answers must contain it
[EKR: but only on unbundled m= sections or those which are the head of the bundle group]

a=rtcp-mux-only
SHOULD send if you don't implement non-mux.
[EKR: but only on unbundled m= sections or those which are the head of the bundle group]

**Comment by cdh4u** [comment]
Commenting from a BUNDLE perspective:

a=rtcp:
Offers must contain it. Answers shouldn't (because it's useless)

[BUNDLE/Christer]: It is not used in bundle-only m- lines, because if they are accepted RTP/RTCP-mux will always be used.

a=rtcp-mux
Offers and answers must contain it
[EKR: but only on unbundled m= sections or those which are the head of the bundle group]

[BUNDLE/Christer]: BUNDLE currently does not mandate a=rtcp-mux in offers if a=rtcp-mux-only is included. But, Cullen has suggested to change that.

a=rtcp-mux-only
SHOULD send if you don't implement non-mux.
[EKR: but only on unbundled m= sections or those which are the head of the bundle group]

[BUNDLE/Christer] With "head of the BUNDLE group", do you mean the BUNDLE m- line?

**Comment by ekr** [comment]
- yes, I agree that it's not used in bundle-only m= lines.

- we don't think that a=rtcp-mux-only is a substitute for a=rtcp-mux, so yes, that should be changed.

- head of BUNDLE group == has bundle tag

**Comment by juberti** [comment]
Specifically, it doesn't seem that rtcp-mux-only as a substitute for rtcp-mux will work when talking with some legacy endpoint that understands rtcp-mux but not bundle (or existing bundle implementations).

**Comment by cdh4u** [comment]
There is still the chance that the answerer, if it doesn't understand rtcp-mux-only, chooses to NOT mux. draft-mux-exclusive provides generic guidance on what to do in such case (e.g., disable the RTP stream). Do we need to say something in JSEP?

**Comment by cdh4u** [comment]
I've created a PR for BUNDLE, which mandates a=rtcp-mux in all bundled RTP-based m- lines.

https://github.com/cdh4u/draft-sdp-bundle/pull/9

**Comment by ekr** [comment]
Here are the rules I think we need:

- Offers for new m= lines MUST contain a=rtcp
- Offers for existing m= lines that aren't muxed MUST contain a=rtcp
- Answers that are not muxed (and hence not bundled) MUST contain a=rtcp

@juberti does this seem right?

**Comment by cdh4u** [comment]
Looks good (again, it does not apply to new bundle-only m= lines)

**Comment by juberti** [comment]
@ekr, let me make sure I understand:

New m= line offer:
Bundle-only: no a=rtcp
Not bundle-only (mux-only): no a=rtcp
Not bundle-only (negotiate mux): a=rtcp

New m= line answer:
Bundle-only: no a=rtcp
not bundle-only, muxed: no a=rtcp
not bundle-only, not muxed: a=rtcp

Existing m= line offer/answer
Bundled: no a=rtcp
Not bundled, muxed: no a=rtcp
Not bundled, not muxed: a=rtcp

Does this match what you are thinking?

**Comment by ekr** [comment]
> New m= line offer:
> Bundle-only: no a=rtcp
> Not bundle-only (mux-only): no a=rtcp

I believe Cullen's argument was that this needs a=rtcp because otherwise if the other side is non-mux it well spray media somewhere crazy.


> Not bundle-only (negotiate mux): a=rtcp
> 
> New m= line answer:
> Bundle-only: no a=rtcp
> not bundle-only, muxed: no a=rtcp
> not bundle-only, not muxed: a=rtcp

Agreed.


> 
> Existing m= line offer/answer
> Bundled: no a=rtcp
> Not bundled, muxed: no a=rtcp
> Not bundled, not muxed: a=rtcp

Agreed.

> 
> Does this match what you are thinking?

**Comment by cdh4u** [comment]
>>New m= line offer:
>>Bundle-only: no a=rtcp
>>Not bundle-only (mux-only): no a=rtcp
>I believe Cullen's argument was that this needs a=rtcp because otherwise if the other side is non-mux it >well spray media somewhere crazy.

Didn't Cullen say that a=rtcp-mux should be included also in case of a=rtcp-mux-only? No a=rtcp means RTP port+1 in case of non-mux.

**Comment by cdh4u** [comment]
>New m= line answer:
>Bundle-only: no a=rtcp

Note that there is no bundle-only in an answer. An m- line is either in the bundle group or it's not.

>not bundle-only, muxed: no a=rtcp
>not bundle-only, not muxed: a=rtcp

To clarify: Does "not bundle-only" mean they are still bundled? If they are, they are always muxed.

**Comment by juberti** [comment]
Sorry, I meant bundled instead of bundle-only. Adjusted the text in my comment above accordingly.

I agree with the stated rationale on non-bundled non-mux-only in the initial offer (i.e. should include a=rtcp).
