### ISSUE TITLE
Placeholder open issue in 6. should be removed

### ISSUE THREAD

**Issue by hardie** [rtcweb-wg/jsep#302]
Section 6 has a placeholder open issue:

o  [[OPEN ISSUE: This is a placeholder for other modifications, which
      we may continue adding as use cases appear.]]

this should be removed before WGLC

**Comment by ekr** [comment]
@juberti, I think we agreed that there weren't any more. So can we just remove?

**Comment by juberti** [comment]
Will be resolved by #304
