### ISSUE TITLE
How do we signal synchronization

### ISSUE THREAD

**Issue by martinthomson** [rtcweb-wg/jsep#31]
Cullen wants LS groups because that is what legacy gear understands.

Magnus wants to use MSID, which carries this.

**Comment by ekr** [comment]
MT, would you be willing to write some text here?

**Comment by juberti** [comment]
Who has the token here?

**Comment by juberti** [comment]
Just realized there could be a problem. Consider A, who does not want to sync its audio/video, and B, who wants its video to be synced.

A offers a=group:LS with no mids.
B has to reply with a subset of the proposed mids, by 5888 rules. 
Therefore B's a/v won't be synced.

I don't see a good reason to require this, but 5888 is pretty clear. 
  
  The
   identification-tags contained in this "a=group" line MUST be the same
   as those received in the offer, or a subset of them (zero
   identification-tags is a valid subset).  When the identification-tags
   in the answer are a subset, the "group" value to be used in the
   session MUST be the one present in the answer.

**Comment by alvestrand** [comment]
There's an issue with LS when using bidirectional media sections.

If media stream X (from A to B) uses media sections 1 and 2, and media stream Y (from B to A) uses media sections 2 and 3, what should be the lipsync groups?

Are lipsync groups unidirectional or bidirectional?

**Comment by juberti** [comment]
see comment above. 5888 says bidi, but that is crazy talk.

**Comment by martinthomson** [comment]
Indeed.  Crazy.  What is our plan of attack here then?  

Can we ask MMUSIC to fix this?  Either by un-screwing-up a=group (which seems unlikely), by making a new grouping semantic, or by telling us that there is a better option.

**Comment by juberti** [comment]
JSEP reserves the right to contradict existing standards where necessary. Generally, it seems like the need for symmetry in a=group is semantic-dependent, and so fixing it later in 5888 seems possible.

**Comment by martinthomson** [comment]
So you are suggesting that we define a=group:LS as declarative: it applies to the media that is *sent* by the peer that includes the grouping.  I can live with that, though I suspect it will cause considerable heartburn.  It certainly complicates the grouping model considerably.

**Comment by juberti** [comment]
yes, essentially. I don't see any way to reconcile LS with reality otherwise.

**Comment by alvestrand** [comment]
Changing the semantics of existing mechanisms by declaring that they are changed without actually changing them is a dangerous process.
A simpler alternative is to drop media section reuse when LS groups are present:
If a particular media section is a member of an LS group, or if a MediaStream requires its tracks to be part of an LS group, don't use it for a track in the opposite direction.

The legacy case of one audio section, one video section that is used in both directions will then require that we somehow turn off LS group generation.
