### ISSUE TITLE
Support for SAR in imageattr

### ISSUE THREAD

**Issue by fluffy** [rtcweb-wg/jsep#310]
In https://rtcweb-wg.github.io/jsep/#rfc.section.3.6.2 we say 

For an "a=imageattr recv" attribute, only size limits are considered. Any other values, e.g. aspect ratio, MUST be ignored.

Ignoring sar seem problematic because we may get squashed video if the sender is not sending square pixels. (some video codecs can indicated the sar in the video stream but some can't)

**Comment by juberti** [comment]
Life is definitely simpler if we can avoid SAR negotiation. H.264 can include SAR in the bitstream, and VPX only supports square pixels.

Is there a specific scenario where SAR imageattr is needed?

**Comment by juberti** [comment]
If we did handle SAR in imageattr, the algo could be to first match SAR and then apply the sizing logic. However, trying to optimize in two dimensions seems complicated unless the SAR matching is very simplistic, i.e. only consider exact matches.

**Comment by fluffy** [comment]
Practically with SAR there are only two relevant cases i have seen in the wild,  1) the receiver can support any SAR because they scale video on display. 2) the receiver can only support square pixels. I was unaware that VPx only support square pixels. I thought a 264 to vp8 transcoder that was going from 264 CIF with non square pixels, would just transcode the video with the same number of pixels and use SAR in the imageattr on the VP8 side to indicate the aspect ratio of the pixels. I looked a VP8 and I don't think it says square pixels.

**Comment by juberti** [comment]
So there are two cases:
- S 3.6.1, where we say what a JSEP endpoint should generate for imageattr. I tend to think that we shouldn't say anything about SAR in imageattr, and just mention that with certain codecs, we may receive a bitstream with internal information indicating that pixels are non-square, and implementations SHOULD handle this properly.
- S 3.6.2, where we say what a JSEP endpoint should do when interpreting an imageattr. Currently we say that we ignore non-size attributes like SAR; here we could also say that JSEP endpoints MUST ignore an entire imageattr line if SAR is other than 1.0 (indicating that the other side wants non-square pixels, which JSEP endpoints will not send).

**Comment by juberti** [comment]
LMK what you think about these suggestions and I can turn them into text.

**Comment by fluffy** [comment]
works for me and sort by highest q seems best.
