### ISSUE TITLE
Should JSEP talk about generating a mid if missing?

### ISSUE THREAD

**Issue by adam-be** [rtcweb-wg/jsep#325]
In the WebRTC 1.0 spec we have text talking about generating a mid if the remote description is missing one. That text has a faulty link to a JSEP (as described in issue w3c/webrtc-pc/issues/698). I can't seem to find any text in JSEP about this. Should there be such text? I did find text that said that an answer only should have a mid if the offer did.

**Comment by juberti** [comment]
OK, I agree we need some additional text in 3.5.2.1 to indicate that if a MID is not negotiated in SDP, a MID is locally generated (but not included in SDP).

**Comment by juberti** [comment]
Fixed by #327

**Comment by adam-be** [comment]
Thank you!
