### ISSUE TITLE
Ensure 4572-update is fixed 

### ISSUE THREAD

**Issue by fluffy** [rtcweb-wg/jsep#330]
Make sure that 4672-update says 

At least one of the "a=fingerprint" lines for each certificate MUST have use the digest  algorithm used in the certificate signature.

**Comment by martinthomson** [comment]
See cdh4u/draft-4572-update#3

**Comment by fluffy** [comment]
This is fixed in https://tools.ietf.org/html/draft-ietf-mmusic-4572-update-07 and mmusci chair has made consensus call to to send to IESG so I am closing this.
