### ISSUE TITLE
Need rules for combining transceiver direction with offered directional attribute.

### ISSUE THREAD

**Issue by taylor-b** [rtcweb-wg/jsep#341]
The steps for createAnswer say each m= section must contain:

> o  A direction attribute which is the same as that of the associated
      transceiver.

But this doesn't take into account the directional attribute in the offer.

Imagine the following sequence of operations:

pc.setRemoteDescription(offer_with_sendonly_msection);
transceiver.setDirection("sendrecv");
pc.createAnswer();

Even though the transceiver's direction is "sendrecv", the answer must contain "recvonly", and the application must perform another offer/answer to change the negotiated direction.

**Comment by juberti** [comment]
Peter/Taylor - can you look into this before Friday (10/21)?

**Comment by taylor-b** [comment]
I'm gonna start making a PR now.

**Comment by juberti** [comment]
Fixed in commit 490ca75 (manual marge of an updated version of Taylor's PR).
