### ISSUE TITLE
Resolve TODO: Implementation requirements

### ISSUE THREAD

**Issue by juberti** [rtcweb-wg/jsep#353]
https://tools.ietf.org/html/draft-ietf-rtcweb-jsep-16#section-5.1.1

```
R-16  TODO: any others?
```

**Comment by juberti** [comment]
R-10 (a=ssrc) should probably be removed or adjusted to reflect the fact that JSEP won't generate these lines.

**Comment by fluffy** [comment]
We need to look at the PR started on this and see if this is something we want to do or if we should go the direction of just calling out the non obvious implementation requirements here.

**Comment by fluffy** [comment]
This seems fixed. Closing it

**Comment by juberti** [comment]
Cullen to inspect document and ensure all relevant SDP RFCs are cited in the generating/parsing offer/answer sections (using full list in #360)

**Comment by juberti** [comment]
Is this resolved by #577?

**Comment by juberti** [comment]
Yes. Closing.
