### ISSUE TITLE
Considering layering issue in Section 6

### ISSUE THREAD

**Issue by hardie** [rtcweb-wg/jsep#364]
Raised by Colin Perkins:

"Section 6 says:

   Note: The following algorithm does not yet have WG consensus but is
   included here as something concrete for the working group to discuss.

I don’t think what’s written here is right yet. The RTP specification has rules for forming RTP packets into RTP streams based on their SSRC, and for associating RTCP packets with RTP streams. Similarly, BUNDLE, as of -35, has rules for mapping RTP streams to m= sections based on the MID. This section seems to be trying to replicate these, rather than building on them. 

I think this section should leave the mapping from RTP/RTCP packets to RTP streams to RTP, and the mapping from RTP streams to m= sections to SDP (and BUNDLE, if used). It should talk instead about how RTP streams associated with m= sections are mapped onto RtpSenders and RtpReceivers. This may sound like just a terminology difference, but I think it’s important to get the layering and division of responsibilities right, if the protocol is to be maintainable and extensible."

**Comment by juberti** [comment]
Cullen to talk to Colin and decide if we should forklift this text to BUNDLE (replacing RtpXXXX with m= section), or somehow decompose it.

**Comment by gloinul** [comment]
I agree with Colin here. Section 6 needs to be restructured. First of all the RTP stream to RTP receiver mapping basic should be in bundle and only need to be referenced in JSEP. What I consider as an open issue is that if one have unique PTs, does one want to have rules for how one can use these to map RTP streams to media descriptions. This, likely doesn't belong in BUNDLE, as it requires MIDs, if one want to have some type of dealing with non bundle compliant implementations, then the PT could make sense. But, it do require that PTs are unique across all media description in the same bundle. 

The RTCP handling I also think should be significantly reworded. As I don't think the RTCP packet should be copied to the RTP receiver/sender layer. It is the relevant information elements from the various RTCP packets that is related to an SSRC currently associated with an RTP Receiver/Sender that should be provided to that RTP receiver/sender.

**Comment by pthatcherg** [comment]
This is addressed by https://github.com/rtcweb-wg/jsep/pull/411/files (moving text into BUNDLE).

**Comment by pthatcherg** [comment]
Dup: https://github.com/rtcweb-wg/jsep/issues/367
