### ISSUE TITLE
Need rules to prevent applying an old, obsolete offer/answer

### ISSUE THREAD

**Issue by taylor-b** [rtcweb-wg/jsep#366]
There is now the requirement:

> The SDP returned from createOffer or createAnswer MUST NOT be changed before passing it to setLocalDescription.

However, this requirement by itself doesn't prevent an application from doing the following:

```
fullCapabilityOffer = createOffer();
setLocalDescription(fullCapabilityOffer);
// Send offer, receive answer with reduced capabilities...
setRemoteDescription(reducedCapabilityAnswer);
// Later...
setLocalDescription(fullCapabilityOffer);  // Hey, I didn't modify the SDP, so it's legal!
```

Setting an old offer here is effectively the same as generating a new offer and modifying the SDP (adding codecs etc.), which we want to prevent.

So I think there also need to be rules about when an offer/answer is invalidated. Meaning it will be rejected in the same way that munged SDP would be rejected. Does this occur:
- Whenever the signaling state changes to `stable`? (I _think_ this is sufficient)
- Whenever the signaling state changes at all?
- Whenever the `PeerConnection` is modified by the application at all?

There's also the more innocuous example of:

```
addTransceiver();
oneTransceiverOffer = createOffer();
addTransceiver();
setLocalDescription(oneTransceiverOffer);
```

Where this just means that an implementation needs to be prepared to accept offers that don't match the current state of its transceivers. Which it already must do for answers, so this may not be a big deal.

**Comment by adamroach** [comment]
@taylor-b 
> Setting an old offer here is effectively the same as generating a new offer and modifying the SDP (adding codecs etc.), which we want to prevent.

It shouldn't be, because the `<session-version>` field field in the `o=` line will be stale. There might be additional text needed here, but it would basically be "if the `<session-version>` field is the same as or smaller than `<session-version>` from any previous calls to `setLocalDescription`, then it MUST be rejected. I mean, I think this is pretty strongly implied by RFC 3264 behavior already, but it wouldn't hurt to be explicit.

**Comment by taylor-b** [comment]
Ah, I forgot about the session version incrementing.

*However*, subsequent calls to `createOffer` can increment the session version, so would you still be able to do this?

```
version1Offer = createOffer();
// Fiddle with things
version2Offer = createOffer();
setLocalDescription(version1Offer);
// Now I have a backup version 2 offer I can set later.
```

**Comment by adamroach** [comment]
Yeah, so we might have to phrase it as the version number precisely matches the version returned by the most recent call to `create{Offer,Answer}`

**Comment by fluffy** [comment]
agree we probably need more advice here but when we write it, need to keep rollback in mind.

**Comment by juberti** [comment]
I agree we should invalidate offers at some point to prevent oddness where an app tries to expand the set of capabilities for the session (e.g. caches an initial offer, and then replays that later to try to change the codecs in use for the session). So, as Taylor indicates above, the question becomes when we should do the invalidation:
1. Whenever the signaling state changes to stable?

2. Whenever the signaling state changes at all?

3. Whenever the PeerConnection is modified by the application at all?

3) would probably break some existing code, and seems unnecessary.
2) seems like the simplest solution; just need to store the createOffer version count (not the SDP version number) any time setLD is called, and require the next vnum to be greater.

**Comment by alvestrand** [comment]
Conclusion from RTCWEB meeting: CreateOffer/answer invalidates previous offers/answers, you can't change the SDP from what was generated last. Any API changes are left to the WEBRTC WG.
