### ISSUE TITLE
Section 4.2.2: Stopped

### ISSUE THREAD

**Issue by aboba** [rtcweb-wg/jsep#369]
4.2.2.  stopped  

     The stopped method returns "true" if the transceiver has been
     stopped, either by a call to stopTransceiver or by applying an answer
     that rejects the associated m= section, and "false" otherwise.

[BA] This should be rewritten as follows: 

```
The stopped attribute has the value "true" if the RtpTransceiver has been stopped,
either by a call to transceiver.stop() or by applying an answer that
rejects the associated m= section and "false" otherwise.
```

**Comment by juberti** [comment]
Agree, there is precedent for this regarding the canTrickleIceCandidates property in https://tools.ietf.org/html/draft-ietf-rtcweb-jsep-17#section-4.1.14. We should make these consistent (note use of 'property' vs 'attribute')
