### ISSUE TITLE
Section 3.2 DTLS parameter

### ISSUE THREAD

**Issue by hardie** [rtcweb-wg/jsep#373]
Originally raised by Christer

Section 3.2 says:

   "the DTLS-SRTP parameters [RFC5763] sent to a remote party indicate what
   certificate the local side will use in DTLS setup"

1) I am not sure what "parameters" the text is referring to. If it¹s the
fingerprint, I think the text should reference RFC 4572.

2) I think we should simply have a generic statement that, following the
rules in RFC3264, parameters indicate receiving capabilities - unless
explicitly indicated otherwise.

**Comment by juberti** [comment]
The parameters include a=setup and a=fingerprint. 5763 seems like it covers both.

**Comment by juberti** [comment]
@cdh4u, thoughts?

**Comment by ekr** [comment]
Authors believe this text is fine. @cdh4u, please send us a PR with the specific change you want if you disagree.

**Comment by juberti** [comment]
@cdh4u said in email:

> But, in order to do that, I need to know what is meant by "the DTLS-SRTP parameters [RFC5763] sent to a remote party indicate what
certificate the local side will use in DTLS setup".
 
> Justin said: “The parameters include a=setup and a=fingerprint. 5763 seems like it covers both.”
 
> But, a=setup has nothing to do with the certificate, and in case of multiple possible certificates a=fingerprint won’t indicate which one will be used in DTLS setup.
 
>So, I would suggest to replace:
 
    “However, not all parameters follow this rule; for example, the DTLS-
    SRTP parameters [RFC5763] sent to a remote party indicate what
    certificate the local side will use in DTLS setup, and thereby what
    the remote party should expect to receive;”
 
>…with:
 
    “However, not all parameters follow this rule; for example, the fingerprints
      sent to a remote party are calculated based on the local certificate(s)
      offered;”
 
>If you agree with that understanding, I’m happy to submit a pull request.

**Comment by juberti** [comment]
OK, I now see what you are saying, and I think the text you propose looks reasonable. Thanks for offering to submit a PR!

**Comment by juberti** [comment]
[waiting on PR from @cdh4u]

**Comment by cdh4u** [comment]
It seems like I don't have rights to submit new branches (needed for the PR).

**Comment by ekr** [comment]
cd4u: fork the repo and push the branch to your fork, then submit the PR from there.

**Comment by cdh4u** [comment]
PR created: https://github.com/rtcweb-wg/jsep/pull/504

**Comment by juberti** [comment]
Fixed by #504
