### ISSUE TITLE
Section 3.2 Provisional Answer text

### ISSUE THREAD

**Issue by hardie** [rtcweb-wg/jsep#374]
Originally raised by Christer

Section 3.2 says:

   "JSEP also allows for an answer to be treated as provisional by the
    application.  Provisional answers provide a way for an answerer to
    communicate initial session parameters back to the offerer, in order
    to allow the session to begin, while allowing a final answer to be
    specified later. This concept of a final answer is important to the
    offer/answer model; when such an answer is received, any extra
    resources allocated by the caller can be released, now that the exact
    session configuration is known."

1) I would like explicit text saying that this is a deviation from RFC
3264, where there is no such thing as a provisional answer. I would like
to have a dedicated ³Deviations to RFC3264² (or something similar) section.

2) I would like explicit text saying that the final answer may be
completely different (in terms of candidates, codecs, accepted m- line
etc) from the provisional answer.

3) Related to 2), the final answer may also require NEW resources to be
allocated.

**Comment by juberti** [comment]
We discussed this and we don't think text is needed for 1) or 3); the offerer doesn't release resources until the final answer.

For 2), what kind of text did you have in mind?

**Comment by fluffy** [comment]
Few notes to cullen from talking wtih Christer 


Christer proposals ... adding section "SDP Offer/Nswer Usage" 

- document variation we make on SAVPF stuff 

- explain how ANSWE / PR answer are used withen paringin multiple  to single offer Points to section for details ...

- follwo proccedures in 3264
