### ISSUE TITLE
Section 3.2 Set local description interaction with provisional offer

### ISSUE THREAD

**Issue by hardie** [rtcweb-wg/jsep#375]
Originally raised by Christer

Section 3.2 says:

    "To support this, the JSEP media layer
     can provide an offer via the createOffer() method whenever the
     Javascript application needs one for the signaling.  The answerer can
     send back zero or more provisional answers, and finally end the
     offer-answer exchange by sending a final answer.  The state machine
     for this is as follows:"

1) I would like to explicitly note that the generated offer is not applied
(and any previously applied offer is not removed) until
setLocalDescription() is called.

**Comment by juberti** [comment]
OK. In this case, we should note this for the provisional answers as well.

**Comment by juberti** [comment]
I thought about this for a while and came to the conclusion that this is the wrong place for such text; spelling everything out makes the overall message less clear.

If we need to be super-prescriptive about the fact that the offer does not take effect until after setLD is called, we should state this in the createOffer/Answer sections (4.1.5/4.1.6), not here.

@cdh4u, PTAL.

**Comment by juberti** [comment]
Will update document according to my last comment.

**Comment by juberti** [comment]
See PR #498

**Comment by cdh4u** [comment]
PR #498 looks ok.
