### ISSUE TITLE
Section 3.3 Editorial change

### ISSUE THREAD

**Issue by hardie** [rtcweb-wg/jsep#376]
Originally raised by Christer

Section 3.3 says:

     "In the WebRTC specification, session descriptions are formatted as
      SDP messages."

1) To me it is unclear what an ³SDP message² is, so I suggest we say ³SDP
syntax², as we also do later in the section.

**Comment by juberti** [comment]
FWIW, RFC 4566 itself uses the term 'SDP message' in Section 7.

However, we could say 'descriptions use SDP syntax' instead.
