### ISSUE TITLE
Section 3.4.1 Request for explanatory text & editorial change

### ISSUE THREAD

**Issue by hardie** [rtcweb-wg/jsep#377]
Originally raised by Christer

Section 3.4.1 talks about ³RtpTranceivers², ³RtpSenders² and
³RtpReceivers².

1) I think they should be introduced in their own section (not within the
Session Description Protocol section).

2) I think it should be explained what an RtpXXX really is. At a minimum
there should be a reference to the appropriate W3C document. But, as there
is text on how they related to SDP m- lines etc, 1 or 2 sentences
describing what they are would also be useful.

**Comment by juberti** [comment]
Section 3.4.1 is its own section, and explains what the RtpTransceiver is.

Agree that Sections 3.4.2/3.4.3 (on senders/receivers) could be expanded somewhat.

@cdh4u FYI

**Comment by juberti** [comment]
Resolved by #458
