### ISSUE TITLE
Section 3.5.3 Browser requirements for selecting candidates

### ISSUE THREAD

**Issue by hardie** [rtcweb-wg/jsep#379]
Originally raised by Christer

Section 3.5.3 contains requirements regarding what a browser MUST do -
e.g., allowing the application to select what types of ICE candidates are
used.

1) I am not sure why such requirements are listed here. But, in any case,
is there a mechanism for applications for selecting candidate types etc?
If so, what mechanism?

**Comment by ekr** [comment]
This is ICE policy. Editorial

**Comment by juberti** [comment]
Suggested revision:

   To accomplish this, the browser MUST allow the application to restrict which ICE candidates
   are used in a session.

to

  To accomplish this, the browser allows the application to restrict which ICE candidates
  are used in a session.
