### ISSUE TITLE
Need to detail the effects of changing the candidate pool size mid-session.

### ISSUE THREAD

**Issue by taylor-b** [rtcweb-wg/jsep#381]
It's pretty straightforward how `setConfiguration` affects the candidate pool size *before* the pooled candidates are used. By the way, when I say "candidate" below, assume I mean "stream's worth of candidates", since a pool size of 1 really means you gather a bunch of candidates for one ICE "stream".

```
setPoolSize(2);  // 2 candidates gathered
setPoolSize(3);  // 1 additional candidate gathered
setPoolSize(1);  // 2 candidates discarded (if they were gathered by this point)
```

But what about after some (or all) of the pooled candidates begin to be used, as a result of setLocalDescription? Here are some examples:

**Increasing pool size after it's depleted**
```
setPoolSize(2);
setLocalDescription(offerWithTwoStreams);  // Pooled candidates used.
setPoolSize(3);  // Is 1 additional candidate gathered, or are 3?
```

**Decreasing size of depleted pool, then increasing it**
```
setPoolSize(2);
setLocalDescription(offerWithTwoStreams);  // Pooled candidates used.
setPoolSize(1);  // Pool size decreased, but no pooled candidates to discard.
setPoolSize(2);  // Does this do anything? We just decreased the size and increased it again.
```

**Creating pool after SLD**
```
setLocalDescription(offerWithTwoStreams);  // No pooled candidates to use.
setPoolSize(3);  // Is 1 candidate gathered, or are 3?
```

You could think of many other examples.

I can think of two reasonable solutions:

1. When a candidate is taken from the pool, the pool size decreases. This doesn't seem so hard, but it means we need some synchronization between the ICE Agent and User Agent, and the result of `getConfiguration` can now change (which is new).
2. The ICE agent keeps track of both candidates in the pool + taken out of the pool. Additional candidates are only gathered if the size is increased beyond this sum. Going back to the examples:

```
setPoolSize(2);  // Size = 2, Pooled = 2, Taken = 0
setLocalDescription(offerWithTwoStreams);  // Size = 2, Pooled = 0, Taken = 2
setPoolSize(3);  // Size = 3, Pooled = 1, Taken = 2
setPoolSize(1);  // Size = 1, Pooled = 0, Taken = 2
setPoolSize(2);  // Size = 2, Pooled = 0, Taken = 2
```

This is what I implemented in Chrome's WebRTC library (though the feature isn't yet available from JS). It may not be ideal but it's the best thing I could think of that fulfills the requirements of "pool size does not change unless you call `setConfiguration`" and "setting the same size is a no-op".

Or of course, there's also the option:

3. Setting a nonzero pool size after `setLocalDescription` is not allowed. :)

**Comment by juberti** [comment]
@taylor-b, is there any known use case where 2) is necessary? If not, I would suggest doing 3), or as @ekr suggested, a 4), where we just say that setting this attribute outside the ctor is currently undefined (since the pool is just an optimization, this wouldn't cause behavior problems).

**Comment by fluffy** [comment]
Decisions at IETF 97 -   "Setting pool size after setLocal() is a no-op"

**Comment by taylor-b** [comment]
Just to clarify: is it a no-op, or an error (InvalidModificationError in JS)? I'd assume the latter.
