### ISSUE TITLE
Section 4.2.3:  setDirection

### ISSUE THREAD

**Issue by aboba** [rtcweb-wg/jsep#382]
Section 4.2.3:

   The setDirection method sets the direction of a transceiver, which
   affects the direction attribute of the associated m= section on
   future calls to createOffer and createAnswer.

[BA] "sets the direction of a transceiver" is a bit confusing because
setDirection() doesn't immediately change whether an RtpSender can
send or an RtpReceiver can receive.  Since setDirection does
immediately change the value of the transceiver.direction
attribute you might say "sets the transceiver.direction attribute" instead. 

Also, an application may want to determine the current
direction (e.g. whether an RtpSender can send or an RtpReceiver
can receive) as opposed to the pending direction (provided
by transceiver.direction).  Taylor agreed to create a WebRTC 1.0
PR to add the concept of current direction (e.g. by adding
a currentDirection attribute).  It would therefore be useful to add some text
to Section 4.2.3 explaining the distinction.  For example:

"Note that while setDirection sets the transceiver.direction
attribute immediately, this pending direction does not immediately
affect whether an RtpSender will send or RtpReceiver will receive. 
After calls to setLocal/setRemoteDescription, the direction currently
in effect is represented by transceiver.currentDirection (the attribute
Taylor will be defining)."

**Comment by taylor-b** [comment]
As for naming: which of these makes the most sense?

- "direction"/"currentDirection"
- "pendingDirection"/"currentDirection"
- "preferredDirection"/"currentDirection"
- "preferredDirection"/"negotiatedDirection"

I like "preferredDirection" (or something of that nature); "pending" is a bit of a misnomer here because it's possible the set direction may _never_ end up negotiated.

**Comment by aboba** [comment]
@taylor-b  My personal preference would be "direction"/"currentDirection".  While "pendingDirection" might be more accurate than "direction", I'm a bit scared of all the spec changes that might be result from changing the attribute name.

**Comment by juberti** [comment]
Agree with @aboba.

**Comment by alvestrand** [comment]
LGTM (direction + currentDirection).

**Comment by juberti** [comment]
@taylor-b, can this now be closed?

**Comment by taylor-b** [comment]
I don't think Bernard's concern was addressed, which is that "sets the direction of a transceiver" is too ambiguous. Now that we *have* a "currentDirection" to reference, I'll add some clarifying text like he suggested.

**Comment by juberti** [comment]
Resolved by #456.
