### ISSUE TITLE
When "current direction" changes

### ISSUE THREAD

**Issue by aboba** [rtcweb-wg/jsep#384]
According to WebRTC 1.0 Section 5.4 setDirection() does not take effect immediately: 

"The setDirection method sets the direction of the RTCRtpTransceiver. Calls to setDirection() do not take effect immediately. Instead, future calls to createOffer and createAnswer mark the corresponding media description as sendrecv, sendonly, recvonly or inactive as defined in [JSEP] (section 5.2.2. and section 5.3.2.). Calling setDirection() sets the negotiation-needed flag."

My interpretation of the above is that setDirection immediately sets the transceiver.direction attribute, but that the "current direction" (distinct from the direction attribute) is only changed by calls to setLocal/setRemoteDescription. 

I would like to suggest that JSEP indicate precisely when the "current direction" changes.  My reading of JSEP is that this is determined from the currentLocalDescription and currentRemoteDescription.  For example: 

1. The direction provided in the currentLocalDescription (e.g. the "current direction") is "sendrecv" and setDirection("recvonly") is called.  Since setDirection does not change the direction in currentLocalDescription, the RtpSender does not stop sending.
2. createOffer() is called.  A "recvonly" offer is generated.  
3. setLocalDescription(RecvOnlyOffer) is called.  Now the direction in pendingLocalDescription changes to "recvonly", but the direction in currentLocalDescription is still "sendrecv", so the RtpSender does not stop sending.
4. setRemoteDescription(SendOnlyAnswer) is called.  Now the direction in currentLocalDescription is "recvonly", so the RtpSender will stop sending.

**Comment by juberti** [comment]
Bernard's description makes sense to me; currentLocal/Remote indicate the current direction state.

**Comment by juberti** [comment]
Fixed by #410
