### ISSUE TITLE
removeTrack()

### ISSUE THREAD

**Issue by aboba** [rtcweb-wg/jsep#385]
JSEP Section 4.1.2 talks about addTrack(), but there is no equivalent section relating to removeTrack(). 

The current text relating to removeTrack in WebRTC 1.0 Section 5.1 is a bit confusing:

    Stops sending media from sender. The RTCRtpSender will still appear in getSenders. Doing so     
    will cause future calls to createOffer to mark the media description for the corresponding    
    transceiver as recvonlyor inactive, as defined in [JSEP] (section 5.2.2.).

[BA] Since the above text refers to future calls marking the media description, this sounds a lot like a call to setDirection("recvonly") or setDirection("inactive").  However, this would not result in the sender immediately stopping the sending of media.

Since removeTrack is reversible, I would presume it is not equivalent to transceiver.stop() which would be permanent.  While setting the encodings[].active attribute to false would stop sending, that would seem inconsistent with the reference to future calls, which seems to lean more towards setting the direction of the transceiver.

**Comment by ekr** [comment]
I'm not sure I understand the concern here. removeTrack() *both* stops sending and arranges that future createOffers() have the track marked as non-sending

**Comment by juberti** [comment]
I think we have three distinct things:
- sender.setTrack(null): stops sending, no signaling
- removeTrack(sender): stops sending, queues a=recvonly signaling
- transceiver.stop: stops sending, queues port zero signaling

**Comment by juberti** [comment]
@aboba, what would you like to see here?

**Comment by aboba** [comment]
@juberti Taylor had a suggestion to have removeTrack() set sender.track to null (like sender.replaceTrack(null)).  This stops sending immediately, but not permanently, and queues a=recvonly signaling.

**Comment by juberti** [comment]
ok, agreed, as indicated above. What needs to go into JSEP?

**Comment by juberti** [comment]
ping @aboba
