### ISSUE TITLE
Section 3.6 issues - non square pixels and more

### ISSUE THREAD

**Issue by hardie** [rtcweb-wg/jsep#388]
Section 3.6 and 3.6.2 issues originally raised by Magnus:

JSEP
   implementations will not transmit non-square pixels, but SHOULD
   receive and render such video with the correct aspect ratio.

I have two issues with this. First of all, shouldn't JSEP implementations be WebRTC endpoints? The second is these statement that says that a JSEP/WebRTC foo will not do a thing. In most cases that is not necessary, as there would be no issues if a particular implementation supports this functionality. So, I think this should be written as:

WebRTC endpoints does not need to support transmission of non-square pixels, but SHOULD
   receive and render such video with the correct aspect ratio.

4. Section 3.6.2:

   When communicating with a non-JSEP endpoint, multiple relevant
   "a=imageattr recv" attributes may be received.  If this occurs,
   attributes other than the one with the highest "q=" value MUST be
   ignored.

There is to my knowledge nothing preventing multiple parameters sets to
have the same preference value (q). Thus, the formulation of this sentence needs to be addressed.

5. Section 3.6.2:

   If an "a=imageattr recv" attribute references a different video codec
   than what has been selected for the MediaStreamTrack, it MUST be
   ignored.

So, to my understanding there can be multiple video codecs and multiple RTP PTs that have been negotiated as possible to use. Is selected just the single currently used one, one or all the possible ones here?

6. Section 3.6.2:

   If the attribute includes a "sar=" (sample aspect ratio) value set to
   something other than "1.0", indicating the receiver wants to receive
   non-square pixels, this cannot be satisfied and the sender MUST NOT
   transmit the track.

Another instances where the language should allow for flexibility if an implementation goes beyond the defined mandatory support. Changing "this cannot be" to "if this cannot be" may resolve it. Also, isn't the relevant "MUST NOT" is to not accept this in the negotiation?

**Comment by fluffy** [comment]
at meeting decided to make this so a browser is not forbidden from sending non square pixels if it wants, but it is not MTI.

**Comment by fluffy** [comment]
from the meeting ... tentative plan is to break ties when q values are the same, implementation can takes the first one

**Comment by fluffy** [comment]
Update 11 minutes later at IETF 97, decided sending square pixels is not allowed.

**Comment by juberti** [comment]
Based on the feedback from IETF 97, the proposed changes are:

4. S 3.6.2 will state that when identical q= values are received, only the first one is used.
5. S 3.6.2 will change to say "payload type" instead of "video codec". 

Regarding 6, we will not make any changes about enabling sending of non-square pixels.
I did consider whether to make sar=!1.0 result in a negotiation failure, but it's not clear how this should be handled on the offerer side; the net effect would be similar to the existing text, where the stream is simply not transmitted.

cc @gloinul
