### ISSUE TITLE
Section 5.1.1 editorial split request

### ISSUE THREAD

**Issue by hardie** [rtcweb-wg/jsep#390]
Originally raised by Magnus

Section 5.1.1:

   This list of mandatory-to-implement specifications is derived from
   the requirements outlined in [I-D.ietf-rtcweb-rtp-usage].

   R-5   [RFC4568] MUST NOT be implemented to signal SDES SRTP keying
         information.

So, the list of mandatory-to-implement includes also some to not implement. That is fine, but probably should be moved to its own list, or rename the list so that it can contain both types.

Secondly, this specific requirement I think comes from the security docs, rather than rtp-usage.

**Comment by ekr** [comment]
I don't have a problem re-stating requirements here. We do that a lot. I'll clean up the list title a bit.
