### ISSUE TITLE
5.1.3 editorial requests

### ISSUE THREAD

**Issue by hardie** [rtcweb-wg/jsep#395]
Originally raised by Magnus:

Otherwise, assume that AVPF is being used in an AVP
      compatible mode and use AVP timing, i.e., "trr-int=4".

I find this sentence confusing. I think this should be clarified to say:

Otherwise, assume that AVPF is being used in an AVP
      compatible mode, i.e. use AVPF timing configured with a "trr-int=4".

15. Section 5.1.3:

Spurious space in:

For data m= sections, JSEP endpoints MUST support receiving the
      "UDP/ DTLS/SCTP", "TCP/DTLS/SCTP", or "DTLS/SCTP" (for backwards
      compatibility) profiles.

**Comment by ekr** [comment]
@gloinul: PR wanted.

**Comment by juberti** [comment]
@gloinul: the text here was trying to indicate that "AVP timing" was a minimum interval of 4 seconds. With the proposed change, the paragraph becomes confusing, as both parts reference "AVPF timing". What do you suggest we do?

      The use of AVPF or AVP simply controls the timing rules used for
      RTCP feedback.  If AVPF is provided, or an "a=rtcp-fb" attribute
      is present, **assume AVPF timing**, i.e., a default value of "trr-
      int=0".  Otherwise, assume that AVPF is being used in an AVP
      compatible mode, i.e. **use AVPF timing** configured with a "trr-int=4".

**Comment by juberti** [comment]
ping @gloinul

**Comment by gloinul** [comment]
@juberti the text you quote appears to be correct. The important aspect is that AVPF becomes compatible with AVP if one uses trr-int=4.0. Where if AVPF (SAVPF) is offered one should use either the default trr-int=0, or negotiate another value. I assume what you find confusing is this part "assume that AVPF is being used in an AVP compatible mode". A possible change could be to change that third sentence to read: "If AVP is offered, then use AVPF in an AVP compatible mode, i.e. set trr-int=4000 (4 s). Does this solve the issue?
