### ISSUE TITLE
Section 5.2.1 b=CT use

### ISSUE THREAD

**Issue by hardie** [rtcweb-wg/jsep#396]
Originally raised by Magnus:

Section 5.2.1:
   o  Session Information ("i="), URI ("u="), Email Address ("e="),
      Phone Number ("p="), Bandwidth ("b="), Repeat Times ("r="), and
      Time Zones ("z=") lines are not useful in this context and SHOULD
      NOT be included.

Considering that b=CT is not useless, I am a bit surprised to see b= on this list. Yes, b=CT: is only useful is one like to provide a upper total bandwidth limitation. So, maybe some discussion of the possible choice?

**Comment by fluffy** [comment]
This is just a mistake in 5.2.1 - we cover how to deal with it later in section 5. Prob need to remove the mention of b= here.
