### ISSUE TITLE
Section 5.2.1:  Should this reference a specific generation algorithm?

### ISSUE THREAD

**Issue by hardie** [rtcweb-wg/jsep#398]
o  An "a=mid" line, as specified in [RFC5888], Section 4.  When
      generating mid values, it is RECOMMENDED that the values be 3
      bytes or less, to allow them to efficiently fit into the RTP
      header extension defined in
      [I-D.ietf-mmusic-sdp-bundle-negotiation], Section 11.

Just to note that to my understanding we are having discussion if this should be referencing a more specific generation algorithm.

Such a change is likely to affect text on RID also:

19. Section 5.2.1:
The list of
      RTCP feedback mechanisms that SHOULD/MUST be supported is
      specified in [I-D.ietf-rtcweb-rtp-usage], Section 5.1.

I would request that we don't use the quite confusing "SHOULD/MUST" and instead write something like:

mechanisms that are recommended or mandated to be supported

**Comment by fluffy** [comment]
So proposed plan is we use some of the text Magnus wrote in other comment on this one and bs sepific about no PII or device ID and sugest some ways to solve are random or seuential

**Comment by ekr** [comment]
Editorial, but someone needs to go find the text.
