### ISSUE TITLE
Section 5.3.1: maxptime clarification

### ISSUE THREAD

**Issue by hardie** [rtcweb-wg/jsep#399]
o  If this m= section is for media with configurable frame sizes,
      e.g. audio, an "a=maxptime" line, indicating the smallest of the
      maximum supported frame sizes out of all codecs included above, as
      specified in [RFC4566], Section 6.

In most cases the maxptime attribute doesn't affect the frame size of the encoder, instead it affects the maximum amount of media that are packetized into a RTP payload, i.e. how many frames that are included.

**Comment by fluffy** [comment]
so what do you suggest we say here ? agree but of course some codecs do adjust frame size based on this too.

**Comment by juberti** [comment]
I would guess that we would want to say "maximum supported packetization sizes", or some such. @gloinul, wdyt?
