### ISSUE TITLE
Generation of CNAMEs for MSTs

### ISSUE THREAD

**Issue by ekr** [rtcweb-wg/jsep#4]
Section 5.2.1:
      in accordance with [RFC7022].  [OPEN ISSUE:  How are CNAMEs
      specified for MSTs?  Are they randomly generated for each
      MediaStream?  If so, can two MediaStreams be synced?]

**Comment by juberti** [comment]
What are next steps here?

**Comment by fluffy** [comment]
Propose browser generates one CNAME (or more if multiple clock sources). Later API may add ways to set the CNAME from JS.

**Comment by martinthomson** [comment]
That would be consistent with the RTP usage conclusions.
