### ISSUE TITLE
Section 5.3.1: rephrasing "bundled into" to "bundled with"

### ISSUE THREAD

**Issue by hardie** [rtcweb-wg/jsep#400]
Originally raised by Magnus:

Each m= section which is not bundled into another m= section, MUST
   contain the following attributes (which are of category IDENTICAL or
   TRANSPORT):

I react to "bundle into another m= section". I though they where "bundled with"?

**Comment by juberti** [comment]
We've used "bundled into" throughout this document, with the idea being that the "into" line is the one whose ICE component is preserved.

**Comment by juberti** [comment]
@gloinul, wdyt?

**Comment by juberti** [comment]
ping @gloinul

**Comment by gloinul** [comment]
Okay, I understand the issue here is that there are multiple implied contexts. There is one RTP session, multiple media source, and multiple media descriptions. What is into or with is different depending on context. So I am fine with leaving it as it is.
