### ISSUE TITLE
Section 5.7.2: an exception needed for non-mux case.

### ISSUE THREAD

**Issue by hardie** [rtcweb-wg/jsep#401]
Originally raised by Magnus:

   o  If present, a single "a=rtcp" attribute MUST be parsed as
      specified in [RFC3605], Section 2.1, but its value is ignored, as
      this information is superfluous when using ICE.

This is another case, where there is an exception to what is written if one has supports the non RTP/RTCP mux usage. Thus, this should be ammended to included such an exception.

**Comment by fluffy** [comment]
Hmm - even in non RTP/RTCP mux case, it you are using iCE it still seems like his is ignored

**Comment by gloinul** [comment]
Okay, yes you are correct, WebRTC doesn't support non-ice case where it would have meaning. So you can close this one.
