### ISSUE TITLE
Section 5.10:  Request to update to "any RTCP ICE componnent"

### ISSUE THREAD

**Issue by hardie** [rtcweb-wg/jsep#405]
Originally raised by Magnus      

*  If the media section has RTCP mux enabled, discard any RTCP
         component, and begin or continue muxing RTCP over the RTP
         component, as specified in [RFC5761], Section 5.1.3.
         Otherwise, prepare to transmit RTCP over the RTCP component; if
         no RTCP component exists, because RTCP mux was previously
         enabled, this MUST result in an error.

I think this should say "any RTCP ICE component"..

**Comment by juberti** [comment]
agreed

**Comment by taylor-b** [comment]
I have a related question: Should ICEbis describe the procedures for discarding an ICE media stream or component (as needed for BUNDLE and RTCP mux negotiation)? Or is it obvious enough already what this implies?
