### ISSUE TITLE
Section 5.10: Consider multi-stream draft's considerations for feedback efficiency

### ISSUE THREAD

**Issue by hardie** [rtcweb-wg/jsep#406]
Originally raised by Magnus:

When sending RTCP feedback, use the
         SSRC of an outgoing Source RTP Stream as the RTCP sender SSRC;
         if no outgoing Source RTP Stream exists, choose a random one.

This is okay, but could be slightly more open in regards to sending feedback packets efficiently. Section 5.4.1 in https://datatracker.ietf.org/doc/draft-ietf-avtcore-rtp-multi-stream/?include_text=1 is providing more detailed rules for things to consider.

**Comment by fluffy** [comment]
Magnus, what do you think is needed here. Informative ref ?

**Comment by gloinul** [comment]
A reference would be good. I would consider cutting away the explicit recommendation here and only say that "When sending RTCP feedback, follow the rules and recommendations in Section 5.4.1 of [draft-ietf-avtcore-rtp-multi-stream] to select which SSRC to use."
