### ISSUE TITLE
Section 6: update advice on PT usage to determine m= section?

### ISSUE THREAD

**Issue by hardie** [rtcweb-wg/jsep#407]
Originally raised by Magnus.

      If any payload type could map to more than one RtpReceiver, map to
      the RtpReceiver whose m= section appears earliest in the local
      description.

I think this is a bad advice. I think it should say that if this is the case, PT should not be used to try to determine which m= section it belongs to. I think wrongly attributing a packet is worse than dropping it in cases where the information is incomplete. This rule can result in that one associate an SSRC with the wrong m= section.

**Comment by fluffy** [comment]
there is another bug on this too - I agree we could change this

**Comment by juberti** [comment]
Obsoleted by events - moved to BUNDLE
