### ISSUE TITLE
Section 6: Clarify that old MID's association table needs to be deleted.

### ISSUE THREAD

**Issue by hardie** [rtcweb-wg/jsep#408]
Originally raised by Magnus:

      If the packet has a MID and that MID is in the table mapping MID
      to RtpReceiver, update the incoming SSRC mapping table to include
      an entry that maps the packet's SSRC to the RtpReceiver for that
      MID.

This is all fine, but requires an addition. If there was already a MID associated with the SSRC, i.e. a new MID has been assigned to this SSRC, then there is deleting in the old MIDs association table that needs to happen.

**Comment by juberti** [comment]
May be obsoleted by events (mapping moving out to bundle).

**Comment by juberti** [comment]
@ekr, is this now obsolete?

**Comment by pthatcherg** [comment]
So can we close this then?

By the way, I think the phrase "update the table" implies both adding the new mapping and removing the old mapping.  So I'm not sure this was an issue in the first place, unless I just misunderstand the issue being raised.
