### ISSUE TITLE
What happens when browser receives offer with different capabilities than currently negotiated

### ISSUE THREAD

**Issue by fluffy** [rtcweb-wg/jsep#409]
Browser offer MCU, VP9, and VP10. MCU answers with VP10. Offer / answer completes. 

Later the MCU offers VP9 to browser on m-line that was currently use VP10. What does the browser do? A strict reading of spec might suggest that since MCU only offered VP9, and current is VP10, the m-line should be rejected. 

Do we need to change this ? Is it OK for browser to respond with VP9.

**Comment by taylor-b** [comment]
Previously I've heard people say "the non-JSEP endpoint can do whatever it wants with codecs." For example, in the thread for issue #266.

**Comment by andyhutton** [comment]
It is definitely OK for the browser to accept the VP9 in the updated offer and I would go further and say that it must accept VP9 in such an updated offer if it is capable of doing so.  The spec should make it clear that browsers MUST accept such codec changes in updated offers.

**Comment by juberti** [comment]
If we solve this, #266 should resolve.
