### ISSUE TITLE
3.6.1 Mandatory constraint change on incoming track causing an offer/answer exchange?

### ISSUE THREAD

**Issue by alvestrand** [rtcweb-wg/jsep#414]
Section 3.6.1 describes mandatory constraints applied to an incoming
track resulting in a new offer-answer exchange. Since this is "action at
a distance" (modify the track and the PeerConnection emits a
negotiation-needed), I think this needs to be synced with the webrtc-1.0
API spec, and possibly even media-capture.

Also, what's the state of the track between the changing of constraints
at the receiver and the renegotiation? It seems to me that the track
should be scaled at the receiver to fit the agreed-upon constraints.

**Comment by juberti** [comment]
OK, agreed we have moved away from this sort of approach.

I guess we could add a new API to RtpReceiver if we decide we need this sort of functionality; we can either spec said API here in JSEP for future implementation, or drop discussion of it altogether.

@alvestrand, wdyt?

**Comment by alvestrand** [comment]
Dropping discussion seems like the simplest approach; that will mean that the receiver hands whatever comes to it into the track, and the track processes it like it processes any other source.

Simple is good.

**Comment by juberti** [comment]
See PR #499
