### ISSUE TITLE
Mention implementations setting step size?

### ISSUE THREAD

**Issue by alvestrand** [rtcweb-wg/jsep#416]
Section 3.6.1 gives an example with a minimum resolution of 16x16 -
where did that come from? If we want to admit to the existence of
macroblocks, we may want to say that the implementation can specify step
sizes (typically 16) in its imageattr values.

**Comment by juberti** [comment]
I avoided discussing step sizes intentionally since it makes the matching more complicated. 

Unless we see a definite need for this, I'd prefer not to support step sizes. If there is a need, we could say that the sender needs to downscale to hit a step size, if the resolution doesn't match already.

**Comment by fluffy** [comment]
I think the 16 was just an example to illustrate the type of place this might be used. I'd rather not get into the whole stepsize thing.

**Comment by alvestrand** [comment]
a minimum of 160x100 is much less likely to make people think about macroblocks. Adding ", and where the minimum useful video size is 160x100" would give a backing story.

**Comment by juberti** [comment]
16x16 seemed like a reasonable minimum for a hw decoder. The Windows framework has a minimum res of 48x48; I can use that value if you prefer.

**Comment by alvestrand** [comment]
I'm happy with anything that includes a backing story for the value. Adding "with a capability of decoding anything from 16x16 to HD" after "multiformat video decoder" would give a backing story.

**Comment by juberti** [comment]
SGTM
