### ISSUE TITLE
Remove claim that API doesn't show number of simultaneous tracks?

### ISSUE THREAD

**Issue by alvestrand** [rtcweb-wg/jsep#417]
Section 3.7 Simulcast - I'm not sure it's true that the information
about number of layers is not surfaced through any API - the number of
elements in the encoding list, and their active/passive state, which is
accessible through getSettings(), should surely give a hint about this.

Suggest removing the claim, since what the API exposes (apart from what's essential for doing JSEP) is beyond the scope of this document.

**Comment by fluffy** [comment]
Ignore that close - was just hit wrong button issue.

**Comment by juberti** [comment]
According to #368, we decided to not support receiving a simulcast offer in 1.0. As such, I suggest we close this issue as wontfix.

@alvestrand, wdyt?

**Comment by alvestrand** [comment]
Remove " but this information is currently not surfaced through any API. " and I'm happy.

The claim is, as I read it, both false and out of scope for JSEP, and adds no useful information.

**Comment by fluffy** [comment]
PR for this is https://github.com/rtcweb-wg/jsep/pull/438

**Comment by juberti** [comment]
If we do this, we need to walk back the text that says we can't receive a simulcast offer. I'm not sure we want to do that, and assuming that's the case, we'd need to have some other rationale for not supporting an incoming simulcast offer.

**Comment by juberti** [comment]
I think I addressed this in #494 by being more generic about why this can't work in the current JSEP.

Go ahead and reopen if I misunderstood.

**Comment by alvestrand** [comment]
This version works for me.
