### ISSUE TITLE
"relay" description too terse?

### ISSUE THREAD

**Issue by alvestrand** [rtcweb-wg/jsep#419]
Section 4.1.1 - the description of "relay" - is it worth noting that
the degre of obfuscation is under the control of the application based
on its choice of turn servers? And that browser-configured turn servers
also matter here?

**Comment by juberti** [comment]
The text does note that the obfuscation is dependent on how the app deploys its relay servers. Was there something specific you thought would help clarify this?

**Comment by juberti** [comment]
ping @alvestrand

**Comment by alvestrand** [comment]
I would replace "Depending on how the application deploys its relay servers" with "Depending on which relay servers are chosen", which doesn't give the false impression that it's only the application's choices that matter.
