### ISSUE TITLE
Editorial: Note that addTransceiver in have-remote-offer will cause negotiation-needed?

### ISSUE THREAD

**Issue by alvestrand** [rtcweb-wg/jsep#420]
- Section 4.1.2 addTrack: Worth noting that using addTransceiver in
have-remote-offer will cause negotiaiton-needed to be fired when the
track returns to stable?

**Comment by pthatcherg** [comment]
JSEP doesn't talk about onnegotiationeneeded, so perhaps this is a W3C issue, not a JSEP issue.
