### ISSUE TITLE
Editorial, section 4.1.8 to 4.1.16

### ISSUE THREAD

**Issue by alvestrand** [rtcweb-wg/jsep#423]
- Section 4.1.8 setLocalDescription - "the PeerConnection must be able
to simultaneously support... until a final answer is received". This is
unclear for several reasons - suggest "while the connection is in the
have-local-offer or have-remote-pranswer state". (There's a race
condition here between media and signalling, of course.)

- Section 4.1.10 currentLocalDescription - "a copy of the current
negotiated local description" is ambiguous (see issue raised in
webrtc-1.0 - https://github.com/w3c/webrtc-pc/issues/921). Suggest
making language here less normative - "shows the current negotiated
local description" would probably be weak enough.

- Section 4.1.15 setConfiguration - "and may result in a change to media
state". Not sure this belongs here - it can lead to a cascade of events
that may end up changing media state, but it is not the call that
directly causes the change. Suggest deleting.

- Section 4.1.16 addIceCandidate - suggest deleting the
"end-of-candidates" text here, and saying separately that there is a
means of indicating end of candidates. There seems to be consensus that
mixing the two was an API design mistake, discussions are about how to
get out of it.

**Comment by ekr** [comment]
@alvestrand: we don't understand this last point. Author consensus is that it is generally OK.

See upcoming PR for fixes for other issues.

**Comment by alvestrand** [comment]
Since the API discussions have converged on leaving us in the state where end-of-candidates is a frob on addIceCandidate, I'm happy to leave the text as is.
(Still think the design is not the best one, but given that we've decided to stick with it, it's not worth complexifying the issue here.)
