### ISSUE TITLE
Codec preferences - why is order of codecs prohibited from changing?

### ISSUE THREAD

**Issue by alvestrand** [rtcweb-wg/jsep#424]
Section 4.2.4 setCodecPreferences - "However, the codec preferences
cannot change the order of the media formats after an answer containing
the transceiver has been applied". I don't understand why we can't
change the order in order to have the new order reflected on the next
offer/answer exchange - there would be no immediate effect, but the
current language locks in the order permanently, without a clear
justification for why it has to be that way.

The codec order shows the preference order that the receiver would prefer from the sender. The RFC says that the sender SHOULD obey that order, not that it MUST. I do not understand why reordering the codecs is a MUST NOT while deleting them (which is strictly more disruptive) is permitted.

**Comment by alvestrand** [comment]
This also affects section 5.3.2 (generation of subsequent answers).

**Comment by juberti** [comment]
The intent here was that the initial offer/answer should indicate the overall format preferences for the session, and any specific changes to which formats are used are at the discretion of the sender. This is to avoid bouncing between formats depending on which side is sending a re-offer (e.g. if A offers X Y but B offers Y X).

I agree that this can be avoided somewhat by not requiring the sender and receiver to have the same ordering, but under what conditions should that occur - only if setCodecPreferences has been called on the answerer side?

@taylor-b wrote the text for this and may have some additional insights.

**Comment by juberti** [comment]
Suggested solution: change the text to always use the specified codec preferences when generating an offer or answer, ignoring 3264's guidance of keeping the same ordering for offer/answer when these prefs have been explicitly set on the answer side.

Specifically:
1. If neither offerer or answerer has set prefs, offerer's default prefs are reflected in the answer, and used for send/receive.
2. If offerer has set prefs, but not answerer, this case is similar to 1).
3. If offerer has not set prefs, but answerer has, the initial answer is ordered differently than the offer, and results in different codecs being used for send/receive. If there is a later reoffer by the initial answerer, the answer to this reoffer will also use the initial answerer's prefs, and the session will stabilize on those values.
4. If both sides have set prefs, the answer will always reflect the answerer's prefs, and this will typically lead to distinct send/receive codecs, although the choices will be stable across a reoffer.

Examples:
EP1 (offerer) prefers [A B C D]
EP2 (answerer) prefers [D C B A]
1. offer = [A B C D], answer = [A B C D], send/recv A, reoffer = [A B C D]
2. offer prefs = [B C D A], offer = [B C D A], answer = [B C D A], send/recv B, reoffer = [B C D A]
3. answer prefs = [C B A D], offer = [A B C D], answer = [C B A D], send C/recv A, EP2 reoffer = [C B A D], EP1 answer = [C B A D], send C/recv C
4. offer prefs = [B C D A],  answer prefs = [C B A D], offer = [B C D A], answer = [C B A D], send C/recv B, no change in reoffers.

If this solution is acceptable, it is a fairly straightforward matter of changing the text in 4.2.4, spelling the answerer behavior out in 5.3.1, and dropping the requirement on order switches in 5.2.2/5.3.2.

**Comment by cdh4u** [comment]
How the offerer and answerer know whether the peer has prefs is a signalling issue, outside the scope of JSEP, right?

**Comment by juberti** [comment]
I don't think either side needs to know if the remote side has prefs. The offerer either offers its preferences, if they exist, or what was previously negotiated, if not. The answerer either answers with its preferences, if they exist, or what was offered, if not.

**Comment by cdh4u** [comment]
Ok, so if the answerer has prefs, they will always override the offer - no matter if the offerer has prefs or not?

**Comment by alvestrand** [comment]
They're two different prefs, neither overrides the other.

In the offer, the offerer sends what he would prefer to receive.
In the answer, the answerer sends what he would prefer to receive.

They don't need to match.

**Comment by cdh4u** [comment]
I agree with you, and I do not understand what the issue is. RFC 3264 does recommend to not change the order of the codecs in the answer, unless there is a good reason. Different preference is a good reason, in my opinion :)

**Comment by juberti** [comment]
The issue was that we were trying to maintain the SHOULD in 3264, but as you and Harald point out, this is a case where ignoring that directive makes everything simpler.

**Comment by cdh4u** [comment]
Exactly which SHOULD are you referring to?

**Comment by juberti** [comment]
"not changing the order in the answer"

**Comment by cdh4u** [comment]
Isn't it only a recommendation?

   "Although the answerer MAY list the formats in their desired order of
   preference, it is RECOMMENDED that unless there is a specific reason,
   the answerer list formats in the same relative order they were
   present in the offer."

**Comment by juberti** [comment]
right, RECOMMENDED is approximately equivalent to SHOULD

**Comment by cdh4u** [comment]
We don't need to argue terminology :) My point is that the text does allow to change the order if there is a specific reason, and different prefs is a valid reason in my opinion.

Also, based on my experience, endpoints usually aim to using the same codec in both directions, which means the answerer will keep the order (it will obviously remove codecs it doesn't support). But, IF it has a reason to change the order, it can do so. I don't think it breaks 3264.

**Comment by juberti** [comment]
agreed - was trying to say this above

**Comment by ekr** [comment]
I am OK with this.

**Comment by juberti** [comment]
@taylor-b, can you take a crack at updating the text to reflect the consensus here?

**Comment by taylor-b** [comment]
Sure.
