### ISSUE TITLE
Lipsync algorithm not clear enough for easy verification

### ISSUE THREAD

**Issue by alvestrand** [rtcweb-wg/jsep#427]
Section 5.3.1 I'm unsure about the language on lipsync groups. I can't
figure out without more careful analysis if it works for the case of
1A+1V replying to 1A+1V - in almost any other case, I think the result
is that answer doesn't have LS groups.

**Comment by juberti** [comment]
Cullen to walk through 1A/1V example here in the bug; maybe add as inline example to doc.

**Comment by juberti** [comment]
PR outstanding.
