### ISSUE TITLE
Comments on RTP demux section

### ISSUE THREAD

**Issue by alvestrand** [rtcweb-wg/jsep#431]
Since this section seems to be moving to BUNDLE, this might be moot.

- Section 6: "this is only a strawman" language needs deleting. We're in
WG Last Call.

- Section 6: For tables where many-to-one mappings are expected (such as
SSRC to receiver when simulcast, RTX or FEC is active), it might be
worth noting this. For tables where many-to-one is an error (such as MID
to RTPReceiver), it might be worth noting that too.

- Section 6: "If the packet's payload type is in the payload type table,
update.." - this will have interesting consequences ("last one wins") if
the sender sends two streams with the same PT and different SSRCs.
Suggest discarding packets where a SSRC->Receiver mapping already exists
for that PT. This gives issues when changing SSRC for a stream; tradeoff
needs evaluating.

**Comment by alvestrand** [comment]
These comments have been incorporated into https://github.com/cdh4u/draft-sdp-bundle/pull/16#pullrequestreview-9995961 which is a PR moving section 6 to the BUNDLE draft.

**Comment by fluffy** [comment]
Will leave this open while list discussion evolves but I suspect this will be resolved by new mux stuff in bundle.

**Comment by pthatcherg** [comment]
FYI, I added the text from the BUNDLE PR back into an appendix in JSEP in https://github.com/rtcweb-wg/jsep/pull/411/files in order to make it easier to iterate on.

**Comment by pthatcherg** [comment]
I addressed all of your comments, by the way.
