### ISSUE TITLE
What happens when RTCP mux policy is "require" and an answer is set without "a=rtcp-mux"?

### ISSUE THREAD

**Issue by taylor-b** [rtcweb-wg/jsep#447]
I may be overlooking something, but I don't think this behavior is documented anywhere.

I think the choices, in order of harshness, are:

- Silently fails, and you don't get RTCP
- negotiationneeded fires, and the m= section is port-zeroed in the next offer
- setRemoteDescription throws an error

I'd lean towards the middle option, but that assumes that applications listen to negotiationneeded.

**Comment by juberti** [comment]
I lean toward the last option, as a violation of an invariant set by the offerer.

**Comment by juberti** [comment]
Agree that this should be documented somewhere.

**Comment by fluffy** [comment]
+1 on the throw an error option

**Comment by juberti** [comment]
The general policy that we discussed here in Seattle was that any spec violation should lead to a setRD exception, not a zero port. For the rtcp-mux-only doc, we probably should have some language that makes rtcp-mux in the answer a MUST.

**Comment by juberti** [comment]
Resolved by #449
