### ISSUE TITLE
a=rtpmap for rtx, fec should come right after normal a=rtpmap

### ISSUE THREAD

**Issue by juberti** [rtcweb-wg/jsep#506]
For createoffer, createanswer ordering of attribs

**Comment by gloinul** [comment]
So SDP has no requirement on the ordering of the a= lines. I don't see how a parser, even a JSEP one can expect to get the a= lines in any specific order. I fear that even a "it is recommended to generate them in this order" will be misinterpreted. I think this is one of SDPs warts that you will have to live with.

**Comment by juberti** [comment]
Right, there isn't any need to mandate an order, I just think that in the text for generating an offer, the places that talk about adding a=rtpmap should be adjacent.

This should be a fairly trivial editorial change.
