### ISSUE TITLE
Use approved IP addresses in examples

### ISSUE THREAD

**Issue by juberti** [rtcweb-wg/jsep#525]
@fluffy sayeth:
> The IP address in IETF stuff have to come out of one of 192.0.2.0/24 198.51.100.0/24
or 203.0.113.0/24. I suggest we go with the convention for all our examples of something along lines of local for offer side is 192.0.2.100 and answer side local is 198.51.100.200 , and the IPs on the outside of there nats are 203.0.113.101 and 203.0.113.201 respectively and relay IP of 203.0.113.102 and 203.0.113.202. The idea being to make it so you can look at last 3 digits and quickly have a clue what address it is.

> Oh, and around the start of the example in the draft add some text that explains our naming conventions to readers.

> And use the last tuple of the IP as the last 3 digits of the port.

**Comment by juberti** [comment]
Thanks for the details here. I kind of like using 192.0.2.0/24 as relay and 198.51.100.0/24 as stun and 203.0.113.0/24 for local addresses, since it's a bit surprising to have srflx and relay addresses be similar.

**Comment by fluffy** [comment]
I like you scheme to use the nets - sounds good.
