### ISSUE TITLE
JSEP Sections 5.4 and 5.8: How to interpret?

### ISSUE THREAD

**Issue by aboba** [rtcweb-wg/jsep#532]
In Section 5.4, JSEP says: 

" The SDP returned from createOffer or createAnswer MUST NOT be changed
   before passing it to setLocalDescription."

However in Section 5.8, it says: 

"First, the parsed parameters are checked to ensure that they are
   identical to those generated in the last call to createOffer/
   createAnswer, and thus have not been altered, as discussed in
   Section 5.4; otherwise, processing MUST stop and an error MUST be
   returned."

[BA] So is *any* change to description.sdp unacceptable (e.g. must be byte for byte identical)? Or is the text trying to say that the parsed representation must be the same (e.g. "a=" lines appearing in a different order shouldn't matter)?

**Comment by juberti** [comment]
I believe the expectation was that the description is entirely immutable.

Verifying isomorphism in the fact of minor modifications seems like something that is not entirely trivial, and TBH I don't quite understand why it would be needed.

**Comment by aboba** [comment]
Thanks. PR https://github.com/w3c/webrtc-pc/pull/1003 assumes that description.sdp is immutable.

**Comment by juberti** [comment]
I will update 5.8 accordingly.
