### ISSUE TITLE
Add sections on parsing and interpreting SDP

### ISSUE THREAD

**Issue by juberti** [rtcweb-wg/jsep#54]
Outline: https://docs.google.com/a/google.com/document/d/1XzhL55Z9PibChNz7nUwE7p0tJYhItTTw0USRUirtTMg/edit

**Comment by juberti** [comment]
Overall no major concerns about this at IETF 92.

**Comment by fluffy** [comment]
Just wondering if we have most of this in the spec now and if this should be closed ?

**Comment by juberti** [comment]
We have probably 50% of this in, but I haven't written the parts about what to actually do with the values once parsed and stored.
