### ISSUE TITLE
Make sure JSEP specifies identity handling 

### ISSUE THREAD

**Issue by fluffy** [rtcweb-wg/jsep#546]
See email to rtcweb from Stefan Håkansson  subject "Identity in the SDP"

**Comment by juberti** [comment]
Sayeth Stefan:

> Hi all,
>
> this relates to identity when webrtc is used with an IdentityProvider (IdP).
>
>I've been browsing the specs, and to me it seems that the only place where we describe how the SDP is affected is in -security-arch [1].
>
>Is this right? And is that the way it is supposed to be?
>
>(Asking since in a discussion in W3C WebRTC [2] draft-ietf-stir-rfc4474bis is mentioned; is that out of scope or in scope?).
>
>Also, I think adding identity to the JSEP and SDP (i.e. draft-ietf-rtcweb-sdp) specs would be a good thing.
>
>Stefan
>
>[1] https://tools.ietf.org/html/draft-ietf-rtcweb-security-arch-12
>[2] https://github.com/w3c/webrtc-pc/issues/964
