### ISSUE TITLE
draft-ietf-ice-rfc5245bis MTI ?

### ISSUE THREAD

**Issue by fluffy** [rtcweb-wg/jsep#559]
Do we require draft-ietf-ice-rfc5245bis and if so we should add a ref to it

**Comment by juberti** [comment]
Deltas: https://tools.ietf.org/rfcdiff?difftype=--hwdiff&url2=draft-ietf-ice-rfc5245bis-08.txt&url1=draft-ietf-ice-rfc5245bis-01.txt
ICE2 changes seem fairly minor, but we'd probably need to update a bunch of references. Not sure we need to do this.

**Comment by ekr** [comment]
Yeah, I suggest we don't
