### ISSUE TITLE
Add ref to draft-ietf-mmusic-data-channel-sdpneg

### ISSUE THREAD

**Issue by fluffy** [rtcweb-wg/jsep#560]

**Comment by juberti** [comment]
I don't think WebRTC/JSEP need to concern themselves with SDP-based DC negotiation:
https://tools.ietf.org/html/draft-ietf-mmusic-data-channel-sdpneg-11

**Comment by ekr** [comment]
Yeah, no. Let's not.

@fluffy: feel free to close this if you concur

**Comment by fluffy** [comment]
data-channel-sdpneg is normatively refed by ietf-mmusic-rfc4566bis but not clear where this is refed .. still tracking down

**Comment by fluffy** [comment]
Don't see any changes in 4566 that we need.
