### ISSUE TITLE
Do we require draft-ietf-mmusic-ice-sip-sdp

### ISSUE THREAD

**Issue by fluffy** [rtcweb-wg/jsep#561]
if so add ref to it

**Comment by juberti** [comment]
https://tools.ietf.org/html/draft-ietf-mmusic-ice-sip-sdp-11
This seems largely redundant with 5245. I don't see a need for us to point at this.

**Comment by ekr** [comment]
Agreed.

**Comment by fluffy** [comment]
+!

**Comment by fluffy** [comment]
reopen just to track what is going on this

**Comment by fluffy** [comment]
cat 4

**Comment by fluffy** [comment]
jsep depends on draft-ietf-mmusic-sdp-bundle-negotiation which normatively depends on this.

**Comment by fluffy** [comment]
Seem email thread in mmusic with subject "normative dependencies in draft-ietf-mmusic-sdp-bundle-negotiation "
