### ISSUE TITLE
Any reason to point at ietf-mmusic-rfc4566bis instead of 4566 

### ISSUE THREAD

**Issue by fluffy** [rtcweb-wg/jsep#562]
If so, need to update JSEP to do that

**Comment by juberti** [comment]
If we do this, we'll need to update all our RFC 4566, Section 6 references to point to the new specific 6.x subsections.

I didn't see any reason though that would compel us to do this. @fluffy, do you think we'll be asked to do this as part of IESG review?

**Comment by ekr** [comment]
Yeah, let's not.

**Comment by fluffy** [comment]
yep looked at all diff from 4566 to bis and do not see anything we need
