### ISSUE TITLE
Do we need ref to 4570

### ISSUE THREAD

**Issue by fluffy** [rtcweb-wg/jsep#563]
I suspect we do not but need to track this down

**Comment by juberti** [comment]
https://tools.ietf.org/html/rfc4570
I did not even know such a thing existed. I don't think we need to include this.

**Comment by fluffy** [comment]
Yah - I was going to try and find out how this got in the ref list but agree we should not have a ref in JSEP.  Leave this open for me for a bit and I will close it once I track it down.

**Comment by fluffy** [comment]
this was old back from when we had the ssrc stuff - we no longer have dep on it. 

Can close
