### ISSUE TITLE
Add ref for draft-ietf-payload-flexible-fec-scheme ?

### ISSUE THREAD

**Issue by fluffy** [rtcweb-wg/jsep#564]

**Comment by juberti** [comment]
I don't think this is needed, since we point at the rtcweb FEC doc already.

      For each supported FEC mechanism, "a=rtpmap" and "a=fmtp" lines,
      as specified in [RFC4566], Section 6.  The FEC mechanisms that
      MUST be supported are specified in [I-D.ietf-rtcweb-fec],
      Section 6, and specific usage for each media type is outlined in
      Sections 4 and 5.

**Comment by fluffy** [comment]
+1

**Comment by ekr** [comment]
Consensus is that this is a transitive dependency.
