### ISSUE TITLE
Add ref for rfc4756

### ISSUE THREAD

**Issue by fluffy** [rtcweb-wg/jsep#565]

**Comment by juberti** [comment]
https://tools.ietf.org/html/rfc4756
We don't currently support this sort of FEC, as indicated in the rtcweb FEC doc:
    Use of FEC-only m-lines, and grouping using the SDP group mechanism
    as described in [RFC5956], Section 4.1 is not currently defined for
    WebRTC, and SHOULD NOT be offered.

Not sure if we need to say anything in JSEP about this, or the FEC doc (i.e. MUST reject or some such). My inclination would be to not say anything beyond what the FEC doc says.

**Comment by fluffy** [comment]
OK with me

**Comment by ekr** [comment]
WFM
