### ISSUE TITLE
Do we need ref to rfc7160 - multi clock rate 

### ISSUE THREAD

**Issue by fluffy** [rtcweb-wg/jsep#574]
https://tools.ietf.org/html/rfc7160

**Comment by juberti** [comment]
This doesn't affect SDP, but we could add some text to the para below indicating a SSRC switch is needed when changing to a codec with a different clockrate:

         *  If the directional attribute in the answer is of type
         "sendrecv" or "sendonly", choose the media format to send as
         the most preferred media format from the remote description
         that is also present in the answer, as described in [RFC3264],
         Sections 6.1 and 7, and start transmitting RTP media once the
         underlying transport layers have been established.  If a SSRC
         has not already been chosen for this outgoing RTP stream,
         choose a random one.

**Comment by juberti** [comment]
(and add a reference)

**Comment by juberti** [comment]
Closing per #592
