### ISSUE TITLE
Do we need refs for TURN / OAuth rfc7635 

### ISSUE THREAD

**Issue by fluffy** [rtcweb-wg/jsep#575]
https://tools.ietf.org/html/rfc7635

**Comment by juberti** [comment]
I don't think this affects SDP at all. We don't discuss TURN URIs in the document either, leaving it abstract:

    The PeerConnection constructor allows the application to specify
    global parameters for the media session, such as the STUN/TURN
    servers and credentials to use when gathering candidates, as well as
    the initial ICE candidate policy and pool size, and also the bundle
    policy to use.

**Comment by juberti** [comment]
IOW, I think we can close this.

**Comment by fluffy** [comment]
works for me
