### ISSUE TITLE
Do we need ref for rfc7741 VP8 SDP 

### ISSUE THREAD

**Issue by fluffy** [rtcweb-wg/jsep#576]

**Comment by juberti** [comment]
I am inclined to say no, since we simply point at the audio/video codec docs which do provide this reference:

      Unless excluded by the above restrictions, the media formats MUST
      include the mandatory audio/video codecs as specified in
      [I-D.ietf-rtcweb-audio](see Section 3) and
      [I-D.ietf-rtcweb-video](see Section 5).

**Comment by fluffy** [comment]
+1

**Comment by ekr** [comment]
+1
