### ISSUE TITLE
Update "a=setup value" according with draft-dtls-sdp

### ISSUE THREAD

**Issue by mparis** [rtcweb-wg/jsep#584]
As commented in [1],
PR in draft-dtls-sdp where the a=setup value issue was discussed is already closed [2].
So I think that we should update the explanation in JSEP according with it.

Refs:
[1] https://github.com/rtcweb-wg/jsep/issues/448#issuecomment-274460375
[2] https://github.com/cdh4u/draft-dtls-sdp/pull/21

**Comment by juberti** [comment]
This doesn't match the previous discussion (#448) that we had on this topic, IIRC. Leaving it to @ekr to resolve.

**Comment by ekr** [comment]
See my comments on PR#448. We are consistent with dtls-sdp, just more restrictive. I think this is fine.

**Comment by mparis** [comment]
Agreed, thanks!!
