### ISSUE TITLE
How to parse and handle SDP with more than one identity line in it 

### ISSUE THREAD

**Issue by fluffy** [rtcweb-wg/jsep#601]

**Comment by fluffy** [comment]
Also see https://github.com/w3c/webrtc-pc/issues/964

**Comment by ekr** [comment]
What's the issue?

**Comment by fluffy** [comment]
Someone thought we should talk about how to parse SDP with more than one identity line and handle that. I did not look, we may already have whatever we need in the draft but I just opened this so we would at least go check.

**Comment by ekr** [comment]
JSEP practice is just to put in placeholders and link to the defining draft, so we should punt the actual semantics in security-arch.
