### ISSUE TITLE
Do we need a reference for CVO?

### ISSUE THREAD

**Issue by juberti** [rtcweb-wg/jsep#613]
We mention it in the imageattr section.

          This is
          required regardless of whether the receiver supports
          performing receive-side rotation (e.g., through CVO), as it
          significantly simplifies the matching logic.

**Comment by juberti** [comment]
@fluffy , can you look into this? Not WGLC2 blocking.

**Comment by fluffy** [comment]
will do - I seem to recall it is a 3GPP ref but will try and track down.
