### ISSUE TITLE
Is the PT table in the demux algo necessary?

### ISSUE THREAD

**Issue by juberti** [rtcweb-wg/jsep#619]
BUNDLE mandates sending MID in RTP headers and RTCP messages. What's the rationale for having a second demux mechanism?

**Comment by juberti** [comment]
@pthatcherg , @taylor-b , @aboba - do you recall the thinking here? This was one thing that was bugging me while finishing off the last PRs on the demux algo.

**Comment by aboba** [comment]
Since no browsers currently support MIDs, developers are writing applications that depend on PT mux.  Documenting the expected behavior will assure that browsers behave similarly.

**Comment by juberti** [comment]
OK, that makes sense. I think it would be a good idea to include a paragraph that explains this - will make a PR.

**Comment by juberti** [comment]
(i.e. that PT demux is for browsers that support a draft version of BUNDLE, and not MIDs)

**Comment by fluffy** [comment]
The consensus is that bundle would not mandate that so I don't know why it says that.

**Comment by juberti** [comment]
https://tools.ietf.org/html/draft-ietf-mmusic-sdp-bundle-negotiation-36#section-10.1 says "MUST be enabled" for the MID extension, but later says that "SHOULD include" the MID extension in the outgoing RTP packets (S 14).

Our text also says MUST:
      In order for an offerer and answerer to always be able to
      associate an RTP stream with the correct "m=" line, the offerer
      and answerer using the BUNDLE extension MUST support the
      mechanism defined in <xref
      target="I-D.ietf-mmusic-sdp-bundle-negotiation" />,

**Comment by juberti** [comment]
PR #620 outstanding to try to document our thinking. If MID is not a MUST use, we can update this para accordingly.

**Comment by juberti** [comment]
@fluffy , PTAL at this

**Comment by fluffy** [comment]
I don't think putting MID in RTP is a MUST use. I do think it is MUST implement for jsep.
