### ISSUE TITLE
createOffer in have-local-offer when there is a current remote description looks unspecified

### ISSUE THREAD

**Issue by docfaraday** [rtcweb-wg/jsep#626]
For non-initial offers, there is currently language for the case where we are in have-local-offer, but the initial offer has not been answered yet (ie; we're creating an alternate version of the initial offer).

There is also language for the case where we have a current remote description and are in either stable or have-remote-pranswer.

But I don't see anything that specifies what should happen if we have completed the first offer/answer, then created and set a reoffer, and are now calling createOffer _again_ (in state have-local-offer).

**Comment by docfaraday** [comment]
I should note that simply following the logic for the second case opens some cans of worms.

Let's say we had completed offer/answer, and all the m-sections are being used. Then, we stop one of our transceivers, and call createOffer. This generates SDP with a disabled m-section. Then we set this local description, add a new transceiver, and call createOffer again. Following the existing language in the draft, we would recycle that disabled m-section for the new transceiver (because the disabled m-section is present in the current local description). If we then use that SDP, the other side will see an m-section change its msids, mid, etc out of the blue, which I gather is something we're trying to avoid?

**Comment by taylor-b** [comment]
> Following the existing language in the draft, we would recycle that disabled m-section for the new transceiver (because the disabled m-section is present in the current local description).

I don't think so. Because the description isn't "current" yet, it's only "pending" until an answer is applied (see the definition of `currentLocalDescription`). So I believe generating the second re-offer will end up performing the exact same steps as for the first re-offer.

**Comment by docfaraday** [comment]
Hmm. Then we should probably remove the recycling language from case 1 (in have-local-offer, but initial offer has not been answered yet), since it involves inspecting current SDP, which will never be set in this case.

**Comment by docfaraday** [comment]
Also, there's two copies of that recycling language in there.

**Comment by juberti** [comment]
@taylor-b , what do you recommend we do here?

**Comment by taylor-b** [comment]
The Subsequent Offer section is structured into:

1. `stable` state, no offer/answer ever applied.
2. `have-local-offer` state.
3. `stable` state, offer/answer already applied.

I believe @docfaraday's point is that, in the `have-local-offer` state, sometimes there will be no current local description. But sometimes there will be. So unless it's split into two sections (`have-local-offer` during first offer/answer exchange, `have-local-offer` during subsequent offer/answer exchange), the recycling text is relevant there, and I wouldn't change anything. Except for removing the duplicated recycling bullet (it appears twice in the same list almost word-for-word).

**Comment by juberti** [comment]
I think the duplicated recycling text has been removed on master.

I will take another pass to see if there are any other odd cases where we are in have-local-offer with an existing remote description.
