### ISSUE TITLE
Remove SDP munging text

### ISSUE THREAD

**Issue by juberti** [rtcweb-wg/jsep#634]
There is a lot of text that should have been removed when the decision to prohibit SDP munging was taken. I will call these out individually, but wanted to call it out here at the top since it has impacts in many places. (In this sentence and elsewhere, I use "munging" exclusively to refer to changing SDP between a createOffer or createAnswer and the corresponding setLocalDescription. In particular, I *do* *not* use it to refer to changes applied to SDP sent to or received from the remote party). Although I repeat it below, I want to be clear in my position: if an implementation creates SDP, verifies that it has not changed since its creation, and then has difficulty processing it, that is a programming error, not a protocol error. It is not appropriate to call out how to recover from programming errors in a protocol document.

**Comment by juberti** [comment]
Agreed.

**Comment by juberti** [comment]
Closing this as it's handled in individual issues. @adamroach, please advise if there was anything else that you thought needed attention.

**Comment by adamroach** [comment]
Thanks. This was an umbrella explanation of the individual nits, which have all been addressed.
