### ISSUE TITLE
Clarify x=0,y=0 imageattr text

### ISSUE THREAD

**Issue by juberti** [rtcweb-wg/jsep#646]
The second paragraph of section 3.6.1 seems odd when talking about creating answers, and downright incorrect when talking about offers. Minimally, it needs text to explain why  x=0/y=0 would ever make more sense than using "a=sendonly/recvonly/inactive."

**Comment by juberti** [comment]
There was a clear rationale for why we did this, as I remember having this exact conversation before, but I need to go dig it up.

**Comment by adamroach** [comment]
@juberti --
>There was a clear rationale for why we did this, as I remember having this exact conversation before, but I need to go dig it up.

Ideally, this rationale would be added to the document once you find it.

**Comment by juberti** [comment]
Sounds like a good idea.

**Comment by juberti** [comment]
I was able to find it - the concern was that if you offered a=recvonly, you could then potentially change that to a=sendrecv via transceiver.setDirection, so a=imageattr of [0, 0] provided a way to prevent any video from being sent without additional complexity.

https://github.com/rtcweb-wg/jsep/pull/499

**Comment by juberti** [comment]
I'm coming around to Adam's viewpoint on this one - not sure we should be inventing a new syntax for saying 'don't send me this video stream'.
