### ISSUE TITLE
Clarify "original resolution"

### ISSUE THREAD

**Issue by juberti** [rtcweb-wg/jsep#647]
Section 3.6.2 talks about "original resolution" where it appears to want to reference the current resolution. This happens in three different places.

**Comment by ekr** [comment]
I don't actually think this is correct. I think "original resolution" is intended to be "what comes out of the camera"

**Comment by juberti** [comment]
It was supposed to mean what comes out of the source. We could use "input resolution", but not sure "original resolution" is ambiguous.

**Comment by juberti** [comment]
@adamroach, thoughts?

**Comment by adamroach** [comment]
@juberti -- It's really more an editorial nit than anything else. I don't think it's going to cause implementors to get things wrong; it just reads a bit odd to me. I'm okay if you want to leave it as-is.

**Comment by juberti** [comment]
After working on some issues in this area I have also come to the opinion that this text is confusing, since resolution might be reduced for other reasons.
