### ISSUE TITLE
Add RtpTransceiver and its friends, Rtpsender and Rtpreceiver

### ISSUE THREAD

**Issue by juberti** [rtcweb-wg/jsep#65]
They affect generated SDP, so they need to appear in Jsep.

**Comment by fluffy** [comment]
done

**Comment by fluffy** [comment]
wrong doc - oops

**Comment by juberti** [comment]
@pthatcherg has volunteered to help write this text

**Comment by fluffy** [comment]
PR to do this is just about done

**Comment by juberti** [comment]
Landed in #257
