### ISSUE TITLE
Rollback missing from type enum

### ISSUE THREAD

**Issue by juberti** [rtcweb-wg/jsep#650]
Section 4.1.9 paragraph one includes an enumeration of things that can appear in the "type" field, but omits "rollback" from the list.

**Comment by juberti** [comment]
Sure.

**Comment by juberti** [comment]
Also may need to cover rollback in the 'applying a local description/remote description' sections.

**Comment by juberti** [comment]
Yes, looks like this is needed.

**Comment by fluffy** [comment]
This has been fixed.
