### ISSUE TITLE
Resolve profile string grammar

### ISSUE THREAD

**Issue by juberti** [rtcweb-wg/jsep#652]
BLOCKER: The first bullet on page 35 has a normative statement about the AVT profile strings that must be accepted, but uses an unspecified grammar to actually specify the string. If this is normative, it needs to be formal. Either specify the string using a formal and cited grammar, or provide an exhaustive list.

**Comment by ekr** [comment]
Proposal on editor's call is to use POSIX extended regular expressions.
https://en.wikipedia.org/wiki/Regular_expression#POSIX_extended

I believe this would give us the expressions.
(UDP|TCP)/TLS/RTP/SAVPF?

and:

RTP/S?AVPF?

**Comment by adamroach** [comment]
You're sure you want to pull in another reference for regexes instead of just listing all eight valid values?
