### ISSUE TITLE
MUST only is confusing

### ISSUE THREAD

**Issue by juberti** [rtcweb-wg/jsep#660]
The bullets on page 45 use the construct "MUST only" three times. This is confusing, and likely to lead to implementors doing the wrong thing. Please rewrite in the form "The 'a=rtcp' line MUST NOT be added unless..."

**Comment by fluffy** [comment]
In the section "Subsequent Offers" we have the text 

 o  The RTCP feedback extensions MUST only include those that are
      present in the most recent answer.

   o  The "a=rtcp" line MUST only be added if the most recent answer did
      not include an "a=rtcp-mux" line.

   o  The "a=rtcp-mux" line MUST only be added if present in the most
      recent answer.

Next step - Rewrite as adam suggested.
