### ISSUE TITLE
Editorial regarding a=setup

### ISSUE THREAD

**Issue by juberti** [rtcweb-wg/jsep#663]
Page 52, bullet starting "An 'a=setup' line": add the words "when allowed" to the end of the bullet.

**Comment by fluffy** [comment]
Text is 

An "a=setup" line, as specified in [RFC4145], Section 4, and
      clarified for use in DTLS-SRTP scenarios in [RFC5763], Section 5.
      The role value in the answer MUST be "active" or "passive"; the
      "active" role is RECOMMENDED.

Fix per adam.

**Comment by fluffy** [comment]
So more discussion in the bug but seems like we should reject this PR and leave it as is
