### ISSUE TITLE
Clarify parsing the local session description

### ISSUE THREAD

**Issue by juberti** [rtcweb-wg/jsep#664]
Section 5.5, bullet 4 talks about parsing the local session description. This is legacy from when SDP munging was allowed, and should be removed (especially the normative statement about parsing errors: the check that the SDP has not changed will catch changes, and any implementation that cannot parse its own SDP is exhibiting an internal error, not a protocol error).

**Comment by fluffy** [comment]
In 5.5.  Processing a Local Description

Proposal - remove the point that says 

o  Next, the SessionDescription is parsed into a data structure, as
      described in the Section 5.7 section below.  If parsing fails for
      any reason, processing MUST stop and an error MUST be returned.

I think Adam argument if correct but lets check we all agree.

**Comment by fluffy** [comment]
@ekr @juberti - if you guys are good with removing that point, I will kill it
