### ISSUE TITLE
Related to #664, regarding remote description

### ISSUE THREAD

**Issue by juberti** [rtcweb-wg/jsep#665]
Section 5.7, first paragraph: similar to above, change "setLocal/RemoteDescription" to "setRemoteDescription."

**Comment by fluffy** [comment]
Section 

5.7.  Parsing a Session Description

Text is 

 When a SessionDescription of any type is supplied to setLocal/
   RemoteDescription, the implementation must parse it and reject it if
   it is invalid.  The exact details of this process are explained
   below.

Fix as adam sugested
