### ISSUE TITLE
Unknown attribute handling

### ISSUE THREAD

**Issue by juberti** [rtcweb-wg/jsep#667]
Section 5.7.2 should include a statement (probably at the end) that implementations may know and process attributes other than those described in this section.

**Comment by fluffy** [comment]
Section 
5.7.2.  Media Section Parsing

Text 
 As required by [RFC4566], Section 5.13, unknown attribute lines MUST
   be ignored.

proposal 

update that text to say something about OK to process things are known but not specified in JSEP.
