### ISSUE TITLE
Local desc processing no longer needs to worry about broken SDP

### ISSUE THREAD

**Issue by juberti** [rtcweb-wg/jsep#669]
Section 5.8 describes the behavior of an implementation processing its own unmodified SDP. It contains significant error language that should have been removed when SDP munging was removed. In particular, please remove all of the following:
	•	"If an error is returned, the session MUST be restored to the state it was in before performing these steps."
	•	"If RTCP mux is not indicated, but was previously negotiated, i.e., the RTCP ICE component no longer exists, this MUST result in an error."
	•	"If any indicated RTP header extension is not supported, this MUST result in an error."
	•	"If any indicated media format is not supported, this MUST result in an error."
	•	"If any referenced primary payload types are not present, this MUST result in an error."
The first bullet of section 5.8 includes: "...unless it has been marked as bundle-only...," and the second includes "...and it has not been marked as bundle-only..." -- in both cases, I believe the indicated behavior is supposed to happen for any bundled section (e.g., in a re-offer or re-answer), regardless of whether it is bundle-only.

**Comment by ekr** [comment]
I think Adam is right about this, but I wonder if this actually belongs elsewhere, so further study needed.

**Comment by ekr** [comment]
> •	"If an error is returned, the session MUST be restored to the state it was in before performing these steps."

This is already duplicated.


> •	"If RTCP mux is not indicated, but was previously negotiated, i.e., the RTCP ICE component no longer exists, this MUST result in an error."

This seems to be a prohibition that is stricter than RFC 5761, and if we remove it here we have removed it generally, unless I have missed somewhere else we say it.


> •	"If any indicated RTP header extension is not supported, this MUST result in an error."
> •	"If any indicated media format is not supported, this MUST result in an error."

This is not appropriate for remote descriptions.

> •	"If any referenced primary payload types are not present, this MUST result in an error."

We say this in 5.9.

>The first bullet of section 5.8 includes: "...unless it has been marked as bundle-only...," and the second includes "...and it has not been marked as bundle-only..." -- in both cases, I believe the indicated behavior is supposed to happen for any bundled section (e.g., in a re-offer or re-answer), regardless of whether it is bundle-only.

Yeah, I think Adam is right about this and it's probably the result of some section refactor

**Comment by ekr** [comment]
Made some progress on it.

Editor discussion on the mux piece. Once an m= line has mux or non-mux negotiated, that's immutable.
