### ISSUE TITLE
Editorial on RtpTransceiver

### ISSUE THREAD

**Issue by juberti** [rtcweb-wg/jsep#670]
Section 5.8 contains the sentence: "If there is no RtpTransceiver associated with this m= section (which will only happen when applying an offer)..." -- it is grammatically ambiguous whether this says that the *absence* of an RtpTranceiver can only happen with an offer, or if the *presence* of an RtpTranceiver can only happen with an offer. Suggest rephrasing as: "If applying an offer and there is no RtpTransceiver associated with this m= section, find one..."

**Comment by juberti** [comment]
@pthatcherg, can you take a look at this?

**Comment by juberti** [comment]
I'm not sold on this approach, since it then invites the question, what should one do if this condition happens when applying an answer?

My suggestion would be to still call this out explicitly, but try to avoid the ambiguity noted above by changing the parenthetical to its own sentence at the end of the paragraph, e.g.

"Note that this situation will only occur when applying an offer."

**Comment by pthatcherg** [comment]
I changed it to that.
