### ISSUE TITLE
Remote desc handling clarification

### ISSUE THREAD

**Issue by juberti** [rtcweb-wg/jsep#671]
BLOCKER: Section 5.9 discusses remote description handling. This means that the first bullet on page 65 talks about remote description handling in the "have-local-offer" state. This means that the second sentence of that bullet talks about remote offer handling when in the "have-local-offer" state. That... doesn't seem right. I'm particularly concerned that the language regarding ICE restart probably belongs somewhere else, since it doesn't appear to belong where it is, but I can't quickly figure out where it's missing from.

**Comment by ekr** [comment]
On the call today, we tried to clarify the flowchart. Basic assumption is that you have already checked the message for being the right one for the state machine. So at this point:

```
If type == offer:
   Mark ICE restart needed  // No provisional state to blow away
If type == answer || type == pranswer:
   If !offered ICE restart:
      Error
   else:
      if local state == have-local-pranswer:
         discard the ICE parameters you got in PRanswer and redo the ICE restart // Ugh
      else:
         OK
```

**Comment by juberti** [comment]
LGTM

**Comment by ekr** [comment]
@fluffy: PTAL

**Comment by fluffy** [comment]
Yah - I think this is correct.
