### ISSUE TITLE
Unsupported media formats

### ISSUE THREAD

**Issue by juberti** [rtcweb-wg/jsep#672]
The bullet in the middle of page 66 (starting "For each specified media format...") states that unsupported media formats must be ignored. The following bullet specifies that "rtx" media formats that refer to "primary payload types [that] are not present" MUST result in an error. Read naïvely, implementors may very well discard a payload type for lack of understanding, and then discover an "rtx" for that discarded PT, and generate an error ("it's not present!"). These bullets need additional text regarding how they interact with each other.

**Comment by ekr** [comment]
We should discuss this, but I just don't think Adam is reading it correctly. These are separate sentences with separate conditionals. But that said, we could probably make the logic here clearer, as you clearly can't be processing an offer in have-local-offer. I think it's just a rewrite of this one bullet, though.I don't think we need to move the text.
