### ISSUE TITLE
Simplify AS->TIAS conversion

### ISSUE THREAD

**Issue by juberti** [rtcweb-wg/jsep#673]
It's nice that you describe how you get from AS to TIAS, but as the formula here isn't intended to be tuned, please simplify it for imlementors as "TIAS = (950 * AS) - 16000". Minimally, include parentheses around the first three terms and the final two; while most people will assume proper order of operations, leaving these ungrouped is asking for trouble. (I once had an argument with an implementor reading an RFC who insisted that 96 wasn't an even multiple of 32; they asserted, with great vehemence, that 96 is 32 times three, and three is odd, so 96 is an *odd* multiple of 32. Don't underestimate the ingenuity of some of the people who will end up implement these specifications.)

**Comment by ekr** [comment]
I don't think we need to have parentheses. The order of operations for multiplication and addition is like basic algebra

I could go either way on the simplification, but I think it's clearer as it is.

**Comment by ekr** [comment]
I propose we close.

**Comment by ekr** [comment]
@juberti , @fluffy

**Comment by fluffy** [comment]
Draft currently has text 

  TIAS = AS * 1000 * 0.95 - 50 * 40 * 8

         The 50 is based on 50 packets per second, the 40 is based on an
         estimate of total header size, the 1000 changes the unit from
         kbps to bps (as required by TIAS), and the 0.95 is to allocate
         5% to RTCP.  "TIAS" is used in preference to "AS" because it
         provides more accurate control of bandwidth.

I prefer this to TIAS = (950 * AS) - 16000 because it helps explain where the numbers came from. 

I believe that precedence of + and * are well understood without brackets

**Comment by fluffy** [comment]
So my suggestion is no change for this one

**Comment by juberti** [comment]
I'd be fine with including the 50 * 4 * 8 in parentheses, since it provides some grouping of the related numbers.
