### ISSUE TITLE
Clarify RFC 3264-related sub-bullet

### ISSUE THREAD

**Issue by juberti** [rtcweb-wg/jsep#675]
BLOCKER: Page 68 contains a sub-bullet that says "If the m= section references any media formats, RTP header extensions, or RTCP feedback mechanisms that were not present in the corresponding m= section in the offer, this indicates a negotiation problem and MUST result in an error." No. This is a violation of RFC 3264. Section 6.1 of that document, when talking about generating answers, specifically stipulates:
   The stream MAY indicate additional media formats, not listed in the    corresponding stream in the offer, that the answerer is willing to    send or receive (of course, it will not be able to send them at this    time, since it was not listed in the offer).  
Note, for example, that this is *exactly* the behavior that the CN handling I describe above relies on. General handling for header extensions and (I believe) feedback mechanisms is intended to operate the same way. This sub-bullet needs to be remove in its entirety.

**Comment by ekr** [comment]
Adam is right, and I think we actually contradict this later.

**Comment by juberti** [comment]
See also: #651

**Comment by juberti** [comment]
So I agree this is permitted by 3264 for media formats, but it's explicitly prohibited for RTCP feedback mechanisms (see https://tools.ietf.org/html/rfc4585#section-4.2), and ambiguous for RTP header extensions (see https://tools.ietf.org/html/rfc5285#section-6).

I'm not sure that removing the bullet is entirely correct.

**Comment by fluffy** [comment]
agree  - updated PR to just remove media formats

**Comment by fluffy** [comment]
Section 6 of https://tools.ietf.org/html/rfc5285#section-6 has the text 

   Either party MAY include extensions in the stream other than those
   negotiated, or those negotiated as "inactive", for example, for the
   benefit of intermediate nodes.  Only extensions that appeared with an
   identifier in the valid range in SDP originated by the sender can be
   sent.

Given that text, I am going to remove that from the error case in th PR.
