### ISSUE TITLE
Similar to #676, page 70

### ISSUE THREAD

**Issue by juberti** [rtcweb-wg/jsep#677]
BLOCKER: The first bullet on page 70 exhibits the same error.

**Comment by ekr** [comment]
Maybe I am just dumb but I am not seeing this in the text.

**Comment by juberti** [comment]
Sorry, I mis-entered this one. This is regarding media directionality again.

**Comment by juberti** [comment]
@ekr, PTAL and see if there's anything from #676 that we need to do here.
