### ISSUE TITLE
Examples do not include all mandatory formats

### ISSUE THREAD

**Issue by juberti** [rtcweb-wg/jsep#680]
BLOCKER: This is an issue with all of the examples. Page 37 contains a bullet that asserts that (unless excluded by rare circumstances which the examples do not stipulate), media formats MUST include those specified in [draft-ietf-rtcweb-video], section 5. None of the examples comply with this normative requirement.

**Comment by ekr** [comment]
This appears to be correct. These just have VP8 and not H.264
