### ISSUE TITLE
telephone-event requires a=fmtp

### ISSUE THREAD

**Issue by juberti** [rtcweb-wg/jsep#681]
All examples include telephone-event audio codecs, but omit a corresponding "a=fmtp" line. RFC4733 specifies:
   SDP descriptions using the event payload MUST contain an fmtp format    attribute that lists the event values that the receiver can process.
While this is a little hinky for implementations that plan to send, but not to receive, DTMF (and that's the only reason I'm not marking this as a blocker), I don't believe that such implementations are exempted from the normative requirement (as SDP recipients may not be expecting such a situation). Including such fmtp lines in the examples is probably the best way to avoid resulting interop issues.

**Comment by ekr** [comment]
This also looks like an example issue.
