### ISSUE TITLE
Clarify handling of upscaling vs dynamic resolution adjustment

### ISSUE THREAD

**Issue by juberti** [rtcweb-wg/jsep#715]
To meet bandwidth limits, the encoder may dynamically apply downscaling. This may conflict with upscaling performed to meet a=imageattr requirements.

This conflict needs to be resolved somehow. I suggest that we remove the language around upscaling and policy and instead state that JSEP implementations SHOULD have appropriate fallback to ensure that they can decode 'too-low' resolutions in software.

**Comment by ekr** [comment]
Resolution on editor's call:

- Just remove the ability to upscale (WebRTC API doesn't permit this anyway)
- If you are in a situation where you would need to upscale to meet the imageattr reqs, just don't send.
- Implementations SHOULD have software fallback if they have some sort of goofy minimum size decoder.

Someone needs to email the mailing list about this change.
