### ISSUE TITLE
Simulcast interaction with a=imageattr

### ISSUE THREAD

**Issue by juberti** [rtcweb-wg/jsep#741]
If a sender is transmitting video at 180p, 360p, and 720p, and it receives an a=imageattr that limits received resolution to 480p, what should happen?

a) 180p and 360p are transmitted intact, 720p is not transmitted
b) 180p and 360p are transmitted intact; 720p is scaled to 480p
c) Everything is scaled down; transmission is 480p, 240p, 120p

I would argue that a) makes the most sense here, but this is somewhat at odds with the guidance we are giving for the non-simulcast case, which is more like b).

**Comment by fluffy** [comment]
This might be a case where the browser needs to do b and the JS need to figure out what happened and turn off the 480 so you end up with an effective results of a. Once we move into simulcast land, the JS just need to deal with taking care of more stuff.

**Comment by fluffy** [comment]
I'm good with A.
