### ISSUE TITLE
If we receive an imageattr with q=1.0 but sar!=1.0, should we use the next best imageattr?

### ISSUE THREAD

**Issue by juberti** [rtcweb-wg/jsep#745]
@gloinul sayeth:
> I think this selection algorithm has a big weakness, that it can select an attribute that results in no encoding at all. I would strongly propose that the selection criteria is to pick the alternative with the highest q that allows for an encoding, i.e. not blocked by the rules preventing an encoding to be generated by the below rules, such as SAR!=1.0.

@juberti sayeth:
> What should happen then in the case of only a SAR!=1.0 imageattr?

**Comment by gloinul** [comment]
If there is only a single one with SAR!=1.0, then you don't need to send any encoding. However, my original point is that if one receive an multi image-attr offer, where one contain SAR!=1.0 on a sub-set of those attribute lines, then discarding them first appears simple and more likely to result in something that an WebRTC endpoint can create or consume.

**Comment by ekr** [comment]
Why is this a special case? For instance, couldn't you also have a q=1.0 with 640x480 and then q=.7 with 320x240 and a stream that was 320x240

**Comment by juberti** [comment]
Agree. If we're starting to make the logic to be 'work down the list until you find an acceptable imageattr', we should do that completely, or not at all (i.e. the current behavior).

**Comment by gloinul** [comment]
Yes, having just re-read the current -21 version draft text, I think the reasonable thing is to go over the aspects listed from the highest q, and if equal q, take the first one listed. Then check if any parameters would prevent sending video. If that is the case, then take next. Thus it becomes a simple looping over the possible attributes until one that at least produces video is found, or one comes to the end of the list and then refuses to send by changing directionality. 

This is simple enough logic and avoids the problem of accepting multiple ones and determining which one will use, which I think was the original complaint that resulted in this text.

**Comment by fluffy** [comment]
WFM

**Comment by juberti** [comment]
Consensus here is to proceed with Magnus' proposed 'first-fit' change.
