### ISSUE TITLE
removeTrack should change direction based on "transceiver.direction", not "transceiver.currentDirection"

### ISSUE THREAD

**Issue by taylor-b** [rtcweb-wg/jsep#757]
Section 4.1.3, removeTrack, states:

> Future calls to createOffer will mark the m= section associated with the sender as recvonly (if transceiver.currentDirection is sendrecv) or as inactive (if transceiver.currentDirection is sendonly).

This should say "transceiver.direction". Using "currentDirection" doesn't work because it may be null, and it also may result in un-intuitive behavior, where `removeTrack` ends up not having any effect and results in a "sendrecv" or "sendonly" direction being negotiated.

**Comment by juberti** [comment]
Want to make a PR?
