### ISSUE TITLE
Determine how a remote peer can be notified of a locally stopped stream

### ISSUE THREAD

**Issue by juberti** [rtcweb-wg/jsep#76]
The SDP will indicate a=recvonly, but it won't be clear if the stream is stopped or merely held. Harald proposed msid-control at IETF 89 to deal with this, but IIRC there wasn't consensus for this yet.

**Comment by juberti** [comment]
IETF 92 discussion - this doesn't cause any real problems, so we'll just leave it as-is for v1 of this doc. Need to check whether any text needs to be updated for this.

**Comment by gloinul** [comment]
For an actual explicit indication of local pause, one could use PAUSED indication from https://datatracker.ietf.org/doc/draft-ietf-avtext-rtp-stream-pause/ which is in IETF last call and thus no issues to reference if desired to be used.

**Comment by fluffy** [comment]
I don't think pause will work here. The issue is if something is rcvonly, how is it indicated it will never go back to sending and thus the PT can be used for something else. The existing equipment assumes the answer to this is never, it can always attempt to renegotiate it back to sending after seting it to rcvonly

**Comment by juberti** [comment]
Regarding the original bug - I think that if you are sending and stop your stream, the other side learns this by the disappearance of a=msid for the stream, in addition to going a=recvonly.

If you are receiving and stop the incoming stream, then the other side doesn't learn this if you still have a sending stream; your side goes to a=sendonly, but it's unclear to the sending side whether the stream has been stopped or just held.

Nevertheless, as mentioned on Mar 26, not sure this information is critical to have.

**Comment by hardie** [comment]
@juberti Can this be closed as OBE?

**Comment by juberti** [comment]
I have been leaving this open to document the actual changes to track assignment and directionality status.

**Comment by juberti** [comment]
Likely addressed by #65

**Comment by juberti** [comment]
Closing since this is now handled via sender/receiver states.
