### ISSUE TITLE
Second para in 3.2

### ISSUE THREAD

**Issue by juberti** [rtcweb-wg/jsep#764]
Second paragraph of 3.2, last sentence: at "these parameters or reject
them" - "these" and "them" have ambiguous antecedents. It's not clear if you
are trying to point to the parameters that don't follow the earlier stated
rule, or all parameters. The sentence is complex. Splitting it up and
finding a way to avoid the need for the semicolon will likely make it
easier to say what you mean.

**Comment by ekr** [comment]
I agree that this is messy. Editorial.
