### ISSUE TITLE
createAnswer edge case

### ISSUE THREAD

**Issue by juberti** [rtcweb-wg/jsep#767]
Odd edge: The description createAnswer (in 4.1.7) leaves open the
possibility that the application could call createAnswer twice
(back-to-back with no intervening calls to other APIs) with different
values in the options parameter. Is this ok? If not, should there be
language that says not to do that somewhere?

**Comment by ekr** [comment]
This is explicitly OK, and the state machine makes it clear.

**Comment by ekr** [comment]
Not sure we need to say anything here, though, given the state machine.

**Comment by ekr** [comment]
@juberti: I forgot to mark this invalid but I think it may be.

**Comment by juberti** [comment]
Discussed with team and plan is to amend the paras that talk about cO/cA not changing media state to also mention that they don't change signaling state.
