### ISSUE TITLE
Profile string references

### ISSUE THREAD

**Issue by juberti** [rtcweb-wg/jsep#768]
Slightly more than minor maybe: The first paragraph of 5.1.2 has at least a
reference error. UDP/TLS/RTP/SAVPF is not specified in RFC7850. It's in
RFC5764. Assuming that this is only a reference error, then the last
sentence seems like a stray. It doesn't seem to be in the right context
("this advertisement" doesn't cast back to the discussion of the two
profiles above it, which are both UDP only). Please clarify the sentence,
giving it the right context, or remove it.

**Comment by ekr** [comment]
This text is correct. The point is we are saying "advertise UDP but we can do TCP or UDP". We can try to rewrite.
