### ISSUE TITLE
sess-id wonkiness

### ISSUE THREAD

**Issue by juberti** [rtcweb-wg/jsep#769]
The fourth sentence of the second bullet of section 5.2.1 is confusing. (It
starts "It is RECOMMENDED that the <sess-id>".) RFC3265 requires the
initial sess-id high-order bit to be zero. As written, this can be read to
say that setting that bit to zero is only RECOMMENDED, and that it's
possible to have sess-ids that are something other than 64 bits. You mean
to say "Do what 3265 says to do and make the lower 63 bits random". Here's
one possible replacement for the sentence: "RFC 3265 requires that the
high-order bit of the initial <sess-id> be zero. It is RECOMMENDED that the
remaining 63 bits be initially set to a cryptographically random value."

**Comment by ekr** [comment]
Yes, this is a reasonable change.

**Comment by fluffy** [comment]
The text from 3264 is 

   The numeric value of the session id
   and version in the o line MUST be representable with a 64 bit signed
   integer.  The initial value of the version MUST be less than
   (2**62)-1, to avoid rollovers. 

My read of this is the *two* high order bits need to be zero
