### ISSUE TITLE
Prohibited attribs in answers

### ISSUE THREAD

**Issue by juberti** [rtcweb-wg/jsep#770]
The last paragraph of 5.3.1 prohibits the same attributes from generated
answers that are prohibited in generated offers. Consider adding text for
what to do if an offer shows up from a peer with some of those prohibited
attributes.

**Comment by ekr** [comment]
Seems like another condition in 5.7 graf 2.

**Comment by ekr** [comment]
The prohibited attributes are:

   o  "a=crypto"
   o  "a=key-mgmt"
   o  "a=ice-lite"

All of these actually seem safe for JSEP implementations to receive (though the first two must be ignored). You actually could legitimately get a=ice-lite from ice-lite offers. And I note that the next graf says:

   Note that these requirements are in some cases stricter than those of
   SDP.  Implementations MUST be prepared to accept compliant SDP even
   if it would not conform to the requirements for generating SDP in
   this specification.

So I think this is actually invalid. @juberti

**Comment by juberti** [comment]
Agreed.

**Comment by fluffy** [comment]
agree

**Comment by juberti** [comment]
Closing as invalid accordingly.
