### ISSUE TITLE
Restated requirements in 5.7

### ISSUE THREAD

**Issue by juberti** [rtcweb-wg/jsep#772]
The first paragraph of section 5.7.1 is simply restating requirements from
RFC4566. Restating normative requirements like that has led to interop
problems through unintended introduced ambiguity and spec maintenance
problems. Please consider rewriting the paragraph to say "RFC4566 says" and
avoid the 2119 keywords.

**Comment by ekr** [comment]
I'm not so sure that this is a good idea. One of the ideas in JSEP is to restate the normative things, and we explicitly cite 4566. I think we should reject this.

**Comment by juberti** [comment]
I'm of the same opinion. If we did change this text, I think the only parts that would be replaced would be the 3 sentences regarding v=, o=, b=, and possibly not even the b=. Sending readers to a separate document just for those lines seems like a questionable improvement.
