### ISSUE TITLE
PC needs a reference

### ISSUE THREAD

**Issue by juberti** [rtcweb-wg/jsep#775]
PeerConnection is used first at the next to last paragraph of section 3.
Please add a reference at that point.

**Comment by ekr** [comment]
Yes.

**Comment by juberti** [comment]
Does Robert mean a ref to Section 4, or a ref to the W3C doc? We do have a ref to the W3C doc in Section 1.

**Comment by ekr** [comment]
That is why I concluded to S 4 (distinguishing between PC and RTCPC)
