### ISSUE TITLE
Why mention 'if parsed successfully'

### ISSUE THREAD

**Issue by juberti** [rtcweb-wg/jsep#779]
At 4.1.17's first paragraph: Why is "if parsed successfully" necessary to
call out? I suggest removing the phrase.

**Comment by ekr** [comment]
I think it's useful to remind people of this.

**Comment by fluffy** [comment]
I don't care

**Comment by juberti** [comment]
Suggest moving this text to the last sentence of this para, where we already mention error conditions.
