### ISSUE TITLE
Direction properties

### ISSUE THREAD

**Issue by juberti** [rtcweb-wg/jsep#780]
4.2.3 talks about setting direction properties, but the values that can be
set aren't called out (and even then only by inference from a list in an
example) in section 4.2.5. Should there be explicit pointers to the api doc
here? (And in section 4.2.6?)

**Comment by ekr** [comment]
Yes, I think a pointer to the API doc is what's needed here.

**Comment by fluffy** [comment]
The more I look at it, I think it is the SDP, not the API doc that effectively defines the allow values of the direction.
