### ISSUE TITLE
Redundant bullets?

### ISSUE THREAD

**Issue by juberti** [rtcweb-wg/jsep#782]
The 4th bullet on page 64 is ambiguous at "this m= section". It looks like
this bullet should just be merged with the previous bullet.

**Comment by ekr** [comment]
I'm not sure what the problem is here, but I'm not against merging it. @juberti?

**Comment by fluffy** [comment]
The bullet point in question is the one that reads 

     If this m= section was present in the previous answer then the
      state of RTP/RTCP multiplexing MUST match what was previously
      negotiated.
