### ISSUE TITLE
Or, what?

### ISSUE THREAD

**Issue by juberti** [rtcweb-wg/jsep#784]
It's not clear what the "Or," in the first bullet on page 65 is referring
to. Are you trying to say "If the m= section is not new, and the ICE ufrag
and password values have changed" or something else?

**Comment by ekr** [comment]
The point is that it's an alternative to the previous bullet. I tend to think this is invalid. @juberti

**Comment by juberti** [comment]
The intent here is as stated, "if the m= section is not new and the values have changed".
