### ISSUE TITLE
Rephrase intro sentence

### ISSUE THREAD

**Issue by juberti** [rtcweb-wg/jsep#786]
Suggested change to the first sentence of 1.1

  OLD:

    The thinking behind WebRTC call setup has been to fully specify and
    control the media plane, but to leave the signaling plane up to the
    application as much as possible.

  New:

    WebRTC call setup has been designed to focus on controlling the media
    plane, leaving signaling plane behavior up to the application as much as
    possible.

**Comment by ekr** [comment]
OK
