### ISSUE TITLE
Rephrase 'note when considering'

### ISSUE THREAD

**Issue by juberti** [rtcweb-wg/jsep#787]
The first full bullet on page 18 has a sentence that starts "Note that when
considering". Please change that to simply "When considering". As written,
there is an implication that this is a consequence of something specified
somewhere else.

**Comment by ekr** [comment]
Yes, this seems rihgt.

**Comment by fluffy** [comment]
To help find it, the whole sentence is is 

     Note that when considering a MediaStreamTrack that is
      producing rotated video, the unrotated resolution MUST be used for
      the checks.  This is required regardless of whether the receiver
      supports performing receive-side rotation (e.g., through CVO
      [TS26.114]), as it significantly simplifies the matching logic.
