### ISSUE TITLE
'Surfaced' is confusing

### ISSUE THREAD

**Issue by juberti** [rtcweb-wg/jsep#788]
The verb "surfaced" appears three times in the document without support or
definition. Can you replace them with simpler language?

**Comment by ekr** [comment]
I don't see a reason to change this. It seems like relatively straightforward langauge.

**Comment by fluffy** [comment]
I don't care. FWIW ... I asked a few developers what surfaced in an API meant and it did not seem a common term they used but given context they all read it the way we mean in spec..

**Comment by ekr** [comment]
The first two, which are about errors, will be changed to "raised"
The last one, which is about candidates will be changed to "made available"
