### ISSUE TITLE
'Note that' is unnecessary

### ISSUE THREAD

**Issue by juberti** [rtcweb-wg/jsep#789]
At the second to last sub-bullet at the end of page 66, please remove "note
that". The sentence is stronger without it.

**Comment by ekr** [comment]
This is incorrect, "note that" is an instruction to the client, not a parenthetical. Perhaps we could say "the agent MUST note that..."

@juberti: agreed?

**Comment by fluffy** [comment]
I don't care.

**Comment by ekr** [comment]
Resolution: change to "the agent MUST note that..." @juberti, also see typo
