### ISSUE TITLE
Determine whether we should generate a=ssrc values for a=recvonly m-lines

### ISSUE THREAD

**Issue by juberti** [rtcweb-wg/jsep#79]
RTCP senders need to have a SSRC, and so if we are signaling SSRCs we should also signal the SSRC used by a RTCP sender using a=ssrc.

This SSRC would be also used if the stream became sendrecv in the future..

**Comment by ekr** [comment]
"- a=ssrc for a=recvonly m-lines (#79)
  * This idea will go off and die and we'll come up with some other way of doing this.
"

**Comment by juberti** [comment]
That's all the minutes say; as such probably no action needed in document. There was some good discussion about what should actually be done here, which might warrant some sort of mention; I'll see if I can distill something useful from the recording.

**Comment by docfaraday** [comment]
Was the idea here that the receiver of the RR would examine the report blocks one by one and determine which streams they applied to?

**Comment by juberti** [comment]
I believe so. Since you can have compound RTCP, one needs to do that anyway.

**Comment by ekr** [comment]
Justin, suggest that the document could benefit from some non-normative text explaining this?

**Comment by juberti** [comment]
yes, the section on a=ssrc should make some mention of this.

**Comment by benbro** [comment]
Related:
https://bugzilla.mozilla.org/show_bug.cgi?id=1160280
https://code.google.com/p/webrtc/issues/detail?id=4740

**Comment by fluffy** [comment]
I'm lost - what needs to be changed here ?

**Comment by juberti** [comment]
I think we need to add some text about how to demultiplex RTCP from an endpoint that is not sending RTP and hence has not signaled its sending SSRC using a=ssrc. The summary is that it should allow any sending SSRC.

**Comment by juberti** [comment]
Closing this in favor of #223.
