### ISSUE TITLE
Hard-to-read sections

### ISSUE THREAD

**Issue by juberti** [rtcweb-wg/jsep#790]
I noted these sections as particularly hard to read when going through the
document linearly. I don't have concrete suggestions for improvement, but
perhaps other eyes (if they agree the sections could use improvement) can
come up with something:
 - First sentence of the first paragraph on page 19.
 - 2nd sentence of the 4th paragraph on page 19.

**Comment by ekr** [comment]
I guess one of can take a look, but some more detail would help.

**Comment by fluffy** [comment]
The first sentence on page 19 is 

   Applications request support for simulcast by configuring multiple
   encodings on an RtpSender, which, upon generation of an offer or
   answer, are indicated in SDP markings on the corresponding m=
   section, as described below.

**Comment by fluffy** [comment]
The 2nd sentence of 4th para is 


   This means that
   established simulcast streams will continue to work through a
   received re-offer, but setting up initial simulcast by way of a
   received offer requires out-of-band signaling or SDP inspection.

**Comment by juberti** [comment]
Obligatory comment: "It was hard to write, so it's only natural that it's hard to read"

**Comment by juberti** [comment]
Suggestion for S1:

> Applications request support for simulcast by configuring multiple
encodings on an RtpSender. Upon generation of an offer or
answer, these encodings are indicated via SDP attributes on the corresponding m=
section, as described below.

**Comment by juberti** [comment]
Suggestion for S2:

> This means that setting up simulcast in the case where the JSEP endpoint receives the initial offer requires out-of-band signaling or SDP inspection. However, in the case where the JSEP endpoint sets up simulcast in its in initial offer, any established simulcast streams will continue to work upon receipt of an incoming re-offer.
