### ISSUE TITLE
Clarify sentence in security seciton

### ISSUE THREAD

**Issue by fluffy** [rtcweb-wg/jsep#792]
From "Opsdir last call review of draft-ietf-rtcweb-jsep-21"

A minor observation, not even a nit, is that the text in the Security
Considerations "While formally the JSEP interface is an API, it is better to
think of it is an Internet protocol, with the JS being untrustworthy from the
perspective of the endpoint. " could be more clear.

**Comment by ekr** [comment]
I have no idea what to do with this. Obviously I thought it was clear when  wrote it

**Comment by juberti** [comment]
This is the only place in the document where we use "JS". I think it would be good to spell out "JavaScript", and potentially use "application JavaScript" in the first usage.

Finally, I think we should use "implementation" rather than "endpoint" in this para.
