### ISSUE TITLE
Image copping  and aspect ratio

### ISSUE THREAD

**Issue by fluffy** [rtcweb-wg/jsep#828]
JSEP currently says:

> If the encoder resolution exceeds the maximum size permitted by the attribute, and the encoder is allowed to adjust its resolution, the encoder SHOULD apply downscaling in order to satisfy the limits, although the downscaling MUST NOT change the picture aspect ratio of the encoding. For example, if the encoder resolution is 1280x720, and the attribute specified a maximum of 640x480, the expected output resolution would be 640x360. 

While WebRTC says:

> When resizing video, the source video is first centered relative to the desired video then scaled down the minimum amount such that the video fully covers the desired size, then finally cropped to the destination size.  ... For example, if the source video was 1280 by 720, and the max size that could be sent was 640 by 480, the video would be scaled down by 1.5 and 160 columns of pixels on both the right and left sides of the source video would be cropped off. This algorithm is designed to minimize occurrence of images with with letter box or or pillow boxing. 

I think we need to change something to align theses. I lean towards the crop approach used by WebRTC to avoid the black jail bars. I know we discussed this before but I forget the outcome. 

@ekr @juberti - Can you refresh my memory on this?

**Comment by fluffy** [comment]
Related to https://github.com/w3c/webrtc-pc/issues/1283

**Comment by juberti** [comment]
We explicitly say that the aspect ratio must not be changed. This means that we would not crop or letterbox. See the example in the paragraph you mentioned.

**Comment by fluffy** [comment]
Discussed on editor call today. Clear that it is not clear what got agreed to in all the WG. In the simple case of receiver says can only do 640 by 480, and the sender has 720p, Justin thinks it should just fail. A good argument for this is cropping screen sharing seldom ends well. This would mean that the text in the WebRTC spec needs to change. 

Plan is to leave this bug as open while we have this contradiction between WebRTC and RTCWeb but to discuss this in next WebRTC meeting. If the WebRTC text resolves to match RTCWeb then we can close this.

**Comment by stefhak** [comment]
FWIW, in  the [minutes](https://www.w3.org/2016/09/22-webrtc-minutes) from TPAC/Lisbon (search for 'crop' on that page) it says we decided on 'center, scale, crop'. That is also con you get to the discussion (and there is also a discussion in the end of https://github.com/w3c/webrtc-pc/issues/305 that seems to confirm that decision).

Slide 73 in https://www.w3.org/2011/04/webrtc/wiki/images/1/1e/WebRTCWG-2016-09-22.pdf 
is the one shown when we discussed at TPAC (if memory serves).

**Comment by juberti** [comment]
Those minutes are from a very long time ago, before we had RtpSender etc, and before we decided that constraints don't apply to RTCPeerConnection.

IIUC, there is no control surface in RTCPeerConnection where such cropping can be specified. It might make sense to add this text to the media capture spec, but I am pretty sure it does not belong here, and it certainly does not have any bearing on how JSEP should process an a=imageattr.

**Comment by stefhak** [comment]
The senders and transceivers had been there for a long time (TPAC Lisbon was less than a year ago).

Anyway, I'm not that interested in history but rather getting to consensus.

**Comment by juberti** [comment]
Right, but what control surface exists to specify this cropping? That's what I am missing.

**Comment by stefhak** [comment]
I think we never had such a surface. I remember you had a proposal waaay back (at the Acme hosted joint IETF&W3C interim in Boston), but that was never implemented. What was agreed at TPAC was without any control surface, and (if memory serves, but I would like to hear what @pthatcherg  who lead that discussion remembers) the reasoning was something like "black surfaces are very annoying, this solution (i.e. 'center, scale, crop') avoids that".

**Comment by juberti** [comment]
But then I'm back to the original question: what situation forces us to have to crop?

**Comment by stefhak** [comment]
The spec says

```When sending media, the sender may need to rescale or resample the media to meet various requirements including the envelope negotiated by SDP. When resizing video, the source video is first centered relative to the desired video then scaled down the minimum amount such that the video fully covers the desired size, then finally cropped to the destination size. The video remains centered while scaling and cropping. For example, if the source video was 1280 by 720, and the max size that could be sent was 640 by 480, the video would be scaled down by 1.5 and 160 columns of pixels on both the right and left sides of the source video would be cropped off. This algorithm is designed to minimize occurrence of images with with letter box or or pillow boxing. The media MUST NOT be upscaled to create fake data that did not occur in the input source.```

Do you mean that a situations like the one in the example above will never occur?

**Comment by juberti** [comment]
Correct. The remote side doesn't indicate display aspect, just maximum decoder resolution.

**Comment by stefhak** [comment]
If that's right it seems straightforward to remove the text. I'd still like someone involved in the discussion in Lisbon (e.g. @pthatcherg) to confirm.

**Comment by stefhak** [comment]
@juberti I am still a little puzzled. Reading section 3.6 of [JSEP](http://rtcweb-wg.github.io/jsep/#rfc.section.3.6), in combination with the above example:
- assume the "track resolution" is 1280 by 720
- assume the imageattr indicates max 640 by 480
I think that was JSEP says is that the video should be downscaled to 640 by 360.
But, if the encoder only has a certain set of resolutions is can do, and 640 by 360 is not one of them (but it can do 640 by 480), what should happen? I think it is for this later case the WebRTC text is applicable, not for the actual SDP o/a part.

**Comment by adamroach** [comment]
@fluffy @juberti @stefhak 

As the responsible AD for this document -- which is post IETF last call -- I'll remind you that any changes to its contents need to be the result of conversations on IETF mailing lists.

If we believe that there is a continued need to open issues against the document, I'm inclined to ask the chairs to take it back to the working group for completion [cc @hardie, @seanturner]. I'm not trying to prevent additional improvements; I'm just observing that if there is work yet to be done, then the document is in the wrong state, and it's my job to correct that.

**Comment by juberti** [comment]
JSEP is clear that if downscaling cannot be applied, the track MUST NOT be sent.

This seems like an extremely uncommon case, and so I think handling it this way is the correct approach.

@adamroach based on this and your comment, I am inclined to close this issue, and it can be discussed on the mailing list if needed.

**Comment by stefhak** [comment]
I do not have an opinion on closing this issue it the right thing or not. Copying something @ekr wrote:

"1. JSEP requires that endpoints process imageattr: 
http://rtcweb-wg.github.io/jsep/#rfc.section.3.6.2. This means that receivers 
can in fact tell senders exactly what sizes they support.

2. I think there's general consensus that you should downscale as long as the 
aspect ratio is the same and that you should not upscale by creating fake image 
data (e.g., pixel doubling).

3. The question is what happens in cases where you can't simply downscale. For 
instance, say you have a receiver which can only receive 640x480 and you have 
720p. You have a number of alternatives:

(a) fail the call
(b) letterbox
(c) center/crop (as in the WebRTC spec, but prohibited by the JSEP spec)
(d) some sort of fancier pan and scan"

and noting for (3) that 
i. this situation can occur even if the imageattr is not the problem - the encoder may have limitations
ii. JSEP says (b) (or possibly (a)) must happen
iii. the consensus at the WebRTC f2f less than a year ago (and the WebRTC spec) says (c) (or possibly (a)) must happen

it is clear to me that this needs some more discussion.

**Comment by fluffy** [comment]
Lets see what at WebRTC interim meeting on the Sep 12 - if the conclusion of that is that WebRTC aligns with this, then we can close this. If not we can get the conversation in the right places at IETF.

**Comment by juberti** [comment]
Responding to @ekr by way of @stefhak, JSEP does not place any limits on what the remote side does. If the remote side can decode the video, it can perform any cropping or letterboxing it wants (probably with more knowledge than the sender).

The question then solely becomes about the case where the remote side can only process very specific resolutions. I argue that this case is entirely artificial, and, as such, JSEP's simple "transmit nothing and report an error" policy is entirely reasonable.

**Comment by stefhak** [comment]
It is not only the case when the remote side can only process very specific resolutions, but also when the sender/encoder is very limited on what it can handle.

Other than that I personally agree to https://github.com/rtcweb-wg/jsep/issues/828#issuecomment-326723564 fully, but as @fluffy said: let's see if the WebRTC WG is OK with this.

**Comment by ekr** [comment]
@juberti: Sure, I don't disagree here. I think the general principle that the sender shouldn't be doing destructive stuff to the video because the receiver has options is a good policy

**Comment by stefhak** [comment]
Hi @ekr @fluffy @juberti I'm trying to summarize in the slides for next week's VI. Can you check if slides 23-26 in look correct?

**Comment by ekr** [comment]
Slide 24 says:
"

   -

   The question is only relevant when the track’s size and/or width is
   larger than what the sender/encoder can use AND when there is an aspect
   ratio mismatch"

This seems like the wrong way to frame it. The question is what the
receiver can consume. I suppose we can discuss the question of internal
inconsistencies on the sender, but that seems different. Also, it's
possible that what the sender has is *too small* but it could be fixed with
letterboxing/pillarboxing, etc.

**Comment by stefhak** [comment]
Thanks for the comment. I agree, I should update a but, but to me it seems easier to look at the intersection of what the sender can send (in terms of width+height combination) and what the receiver can receive than solely what the receiver can consume.

I understand that from a JSEP / imageattr the interesting thing is what the receiver can consume, but from an application author's perspective the intersection is what is interesting.

**Comment by fluffy** [comment]
So given the W3C call, I think we can close this. Correct ?

**Comment by juberti** [comment]
I don't think we covered this in depth in the latest interim, but I haven't heard any good reason to change the JSEP text yet. I'm inclined to close it.

**Comment by stefhak** [comment]
We did not cover this item at the September interim. I've sent this proposed resolution to the list though: https://lists.w3.org/Archives/Public/public-webrtc/2017Sep/0072.html

**Comment by juberti** [comment]
I chimed in on that thread. Will close this issue.

If there is disagreement on that thread, we can reopen.
