### ISSUE TITLE
Needs a ref to data-channel-sdpneg

### ISSUE THREAD

**Issue by fluffy** [rtcweb-wg/jsep#836]
Seems like this needs a normative ref to draft-ietf-mmusic-data-channel-sdpneg

**Comment by juberti** [comment]
Which section in JSEP would make this reference?

**Comment by fluffy** [comment]
In  5.2.1 para that starts "Lastly, if a data channel has been created, a m= section MUST be generated for data"

In 5.3.1 para that starts "If a data channel m= section has been offered, a m= section MUST also be generated for data. "

**Comment by fluffy** [comment]
I'm actually surprised that we don't need some more text about handling what happens in subsequent offers but I have not gone to look to see if I think anything is needed.

**Comment by juberti** [comment]
So this document talks about how to negotiate data channels in SDP, which is not supported in JSEP:

    This section defines an SDP extension by which two clients can
    negotiate data channel-specific and subprotocol-specific parameters
    without using DCEP [I-D.ietf-rtcweb-data-protocol].  This SDP
    extension only defines usage in the context of SDP offer/answer.

It seems like any reference would be to specifically indicate that this is not supported.

**Comment by fluffy** [comment]
That makes sense but I am trying to find which draft were we say that we must use DCEP and can't use data-channel-sdpneg - Do you know where that is? I had the vague memory both we allowed but I am probably wrong on that.

**Comment by juberti** [comment]
webrtc-pc says

> Let configuration be an information bundle received from the other peer as a part of the process to establish the underlying data transport described by the WebRTC DataChannel Protocol specification [RTCWEB-DATA-PROTOCOL].

JSEP doesn't say anything on the wire format for data channels right now; we could easily add a ref to ietf-rtcweb-data-protocol in 4.1.5, by mentioning that data channels will use DCEP. We could also add a ref to sdpneg in the creating offer/answer sections to say that JSEP implementations will not (MUST NOT?) generate the data channel SDP from the sdpneg document.

**Comment by juberti** [comment]
(Note that you can use your own out-of-band protocol instead of DCEP if you set the datachannelinit.negotiated bit, but that doesn't imply use of sdpneg)

**Comment by fluffy** [comment]
I don't think we need a ref to say don't do X and when I looked I failed to look at the w3c specs. That seems fairly clear. I'm closing this.
