### ISSUE TITLE
Wrong refs for end-of-candidates SDP

### ISSUE THREAD

**Issue by juberti** [rtcweb-wg/jsep#841]
Agree, the references in Sections 5.2.2 and 5.3.2 should be updated accordingly. 

> On Wed, Oct 11, 2017 at 12:23 AM, Christer Holmberg <christer.holmberg@ericsson.com> wrote:
> Hi,
> 
> JSEP references draft-ietf-ice-trickle for the SDP ‘end-of-candidates’ attribute.
> 
> But, draft-ice-trickle only talks about a generic end-of-candidates indication. For SDP, the actual SDP attribute is defined in draft-ietf-mmusic-trickle-ice-sip.
>  Shouldn’t JSEP reference that spec instead?
>

**Comment by fluffy** [comment]
If this changes the dependency graph to stuff we don't need, I might suggest the definition of the attributes gets moved.

**Comment by juberti** [comment]
@fluffy, can you take a shot at this?

**Comment by juberti** [comment]
Not positive this was closed, needs review

**Comment by fluffy** [comment]
I'm looking into this one

**Comment by fluffy** [comment]
We need to resolve the what ICE version thing ( https://github.com/rtcweb-wg/jsep/issues/990 ) before we can sort this out

**Comment by fluffy** [comment]
Have a look at https://github.com/rtcweb-wg/jsep/pull/993 - I think it fixes this - I could not find other instances that looked wrong

**Comment by fluffy** [comment]
I think #993 fixed this.
