### ISSUE TITLE
canTrickleIceCandidiates when sending initial offer

### ISSUE THREAD

**Issue by cdh4u** [rtcweb-wg/jsep#848]
JSEP-24 says:

        "null:  No SDP has been received from the other side, so it is not
         known if it can handle trickle.  This is the initial value before
         setRemoteDescription() is called.²

         (The same is said in the W3C WebRTC spec)

         ...and:

        "However, applications can use the canTrickleIceCandidates property to determine whether their  peer can actually do Trickle ICE, i.e., whether it is safe to send an initial offer or answer followed later by candidates as they are gathered. As "true" is the only value that definitively indicates remote Trickle ICE support, an application which compares canTrickleIceCandidates against "true" will by default attempt Half Trickle on initial offers and Full Trickle on subsequent interactions with a Trickle ICE-compatible agent."

QUESTION: Since the value will be NULL before completion of setRemoteDescription (before SDP has been received from the other side) how can the value be used by applications for initial offers?

SUGGESTION: Remove the text saying that canTrickleIceCandidates can be used when creating an initial offer.

**Comment by juberti** [comment]
It seems like the answer to your question is spelled out in the final part of the sentence, i.e.

> an application which compares canTrickleIceCandidates against "true" will by default attempt Half Trickle on initial offers and Full Trickle on subsequent interactions with a Trickle ICE-compatible agent.

**Comment by cdh4u** [comment]
I think it should be explicitly said WHY that is the case. I.e., "as the value will always be null when the initial offer is created, an application which compares..."

**Comment by juberti** [comment]
@ajeanmahoney to see if there's a simple way to work this into the text without making it harder to read

**Comment by ajeanmahoney** [comment]
Current:
> As "true" is the only value that definitively indicates remote Trickle 
> ICE support, an application that compares canTrickleIceCandidates 
> against "true" will by default attempt Half Trickle on initial offers and 
> Full Trickle on subsequent interactions with a Trickle ICE-compatible agent.

Perhaps:
> An application that compares canTrickleIceCandidates against "true" 
> will by default attempt Half Trickle on initial offers, as the value will always 
> be null when the initial offer is created, and Full Trickle on subsequent 
> interactions with a Trickle ICE-compatible agent as definitely indicated 
> by the value "true".

**Comment by ajeanmahoney** [comment]
And perhaps put "null" in quotes, like "true" is.

**Comment by ekr** [comment]
It seems to me that the current text is correct and need not be updated.

**Comment by ekr** [comment]
Note that null is an explicit value in JS objects. If no value exists it is "undefined"

**Comment by juberti** [comment]
perhaps then a simple parenthetical will suffice, e.g., 

> As "true" is the only value that definitively indicates remote Trickle
> ICE support, an application that compares canTrickleIceCandidates
> against "true" will by default attempt Half Trickle on initial offers (as canTrickleIceCandidates will be null) and
> Full Trickle on subsequent interactions with a Trickle ICE-compatible agent.

@ajeanmahoney, do you think this helps with comprehension? If not, I'm inclined to leave as is since 4.1.15 does spell out the null state clearly already.

**Comment by ajeanmahoney** [comment]
LGTM

**Comment by ajeanmahoney** [comment]
@ekr @juberti  Shall I make Justin's suggested change or leave as-is? I'm good either way.

**Comment by ekr** [comment]
Justin's changes LGTM, but I am also fine with as-is.

**Comment by juberti** [comment]
In the end I felt the parenthetical made things harder to understand, and hence a net negative. Ergo I have chosen to keep the text as is, which clearly states why an initial offer would have the value set to null.
