### ISSUE TITLE
3) [rfced] Eric, we note that Mozilla and RTFM are listed as your

### ISSUE THREAD

**Issue by juberti** [rtcweb-wg/jsep#873]
3) [rfced] Eric, we note that Mozilla and RTFM are listed as your
affiliation in various documents within the cluster.  Please review
and let us know if any updates are needed.

**Comment by fluffy** [comment]
Given EKR used Mozilla in TLS 1.3, I propose we just move to that if we don't hear back

**Comment by juberti** [comment]
SGTM

**Comment by ajeanmahoney** [comment]
Waiting to hear back from @ekr

**Comment by juberti** [comment]
Let's go ahead and close this out. As the text currently references Mozilla, let's just remove the comment.

**Comment by juberti** [comment]
@ekr any input here?

**Comment by ekr** [comment]
Yes, I'm using "Mozilla" as my affiliation and "ekr@rtfm.com" as my email
address.
