### ISSUE TITLE
5) [rfced] Section 1.1:  For ease of the reader, and per other

### ISSUE THREAD

**Issue by juberti** [rtcweb-wg/jsep#875]
5) [rfced] Section 1.1:  For ease of the reader, and per other
documents in this cluster (cluster C238), we expanded "XMPP," cited
RFC 6120, and added RFC 6120 to the list of Informative References.
Please let us know any concerns.

Original:
 For example,
 libraries exist to adapt the JSEP API into an API suitable for a SIP
 or XMPP.

Currently:
 For example,
 libraries exist to adapt the JSEP API into an API suitable for a SIP
 interface or an Extensible Messaging and Presence Protocol (XMPP)
 interface [RFC6120].
...
 [RFC6120]  Saint-Andre, P., "Extensible Messaging and Presence
            Protocol (XMPP): Core", RFC 6120, DOI 10.17487/RFC6120,
            March 2011, <https://www.rfc-editor.org/info/rfc6120>.

**Comment by juberti** [comment]
Seems like this should refer to 'applcation' or 'protocol' or some such

**Comment by juberti** [comment]
I would suggest something like:
`For example, libraries exist to provide SIP and Extensible Messaging and Presence Protocol (XMPP) [RFC6120] signaling protocol implementations atop the JSEP API.`

**Comment by ajeanmahoney** [comment]
How about:
`For example, libraries exist to provide signaling protocol implementations of SIP and Extensible Messaging and Presence Protocol (XMPP) [RFC6120] atop the JSEP API.`

**Comment by juberti** [comment]
Doesn't feel quite right to me. How about:
```For example, libraries exist to provide implementations of the SIP [RFC3261] and Extensible Messaging and Presence Protocol (XMPP) [RFC6120] signaling protocols atop the JSEP API.```
