### ISSUE TITLE
11) [rfced]  Sections 4 and 7:  For ease of the reader, please

### ISSUE THREAD

**Issue by juberti** [rtcweb-wg/jsep#881]
11) [rfced]  Sections 4 and 7:  For ease of the reader, please
let us know if we may cite [W3C.webrtc] as a reminder regarding
"addTrack," "removeTrack," etc. (Section 4) as well as
"onicecandidate," "addIceCandidate," and "ontrack" (Section 7),
as follows.

Original:
 The actual API exposed in the W3C API
 may have somewhat different syntax, but should map easily to these
 concepts.
...
 More examples of SDP for WebRTC call flows, including examples with
 IPv6 addresses, can be found in [I-D.ietf-rtcweb-sdp].

Suggested:
 The actual API exposed in the W3C API [W3C.webrtc]
 may have somewhat different syntax but should map easily to these
 concepts.
...
 More examples of SDP for WebRTC call flows, including examples with
 IPv6 addresses, can be found in [SDP4WebRTC].  See [W3C.webrtc] for
 information regarding "onicecandidate," "addIceCandidate," and
 "ontrack".

**Comment by juberti** [comment]
hmm, we never refer to ontrack or onicecandidate in this document, I wonder if we should mention them in Section 4.

**Comment by juberti** [comment]
The ideal solution here would be to have a subsection of section 4 to refer to ontrack (adjacent to the existing addTrack section) and one to refer to onicecandidate (adjacent to the existing addIceCandidate section).

The onicecandidate section should be fairly trivial and could simply refer to the ICE gathering process already defined in JSEP, but ontrack would need to be referenced by setRemoteDescription, so this would not be entirely editorial.

@fluffy from a process perspective, what would you suggest here?

**Comment by juberti** [comment]
@adamroach for his thoughts

**Comment by fluffy** [comment]
It does make sense to add something. We are not making a normative change to how anything works, just clarifying the mapping to the W3C spec. I suspect that the AD could approve that.

**Comment by adamroach** [comment]
I'm not too fussed either way.

I think folks who read both this and the W3C spec will get their implementation right, so it's not required for interop; while at the same time, it's probably a slight improvement to add specific text. I would defer to the current ADs on the correct choice between the two (I think @mskucherawy implicitly picked the C238 work up with the rest of my former realtime groups). I do agree with Cullen that the path that adds new text for `ontrack` definitely requires AD approval, while leaving it as-is does not.

**Comment by juberti** [comment]
I'd prefer that the document be internally consistent, so I'd advocate adding the new paragraph if @mskucherawy is OK with it. I'll make a PR and send to the list for a decision.

**Comment by juberti** [comment]
PTAL at https://github.com/rtcweb-wg/jsep/pull/995/files. @fluffy @mskucherawy @ekr

**Comment by fluffy** [comment]
made one comment over on PR

**Comment by mskucherawy** [comment]
PR #995 is approved as it is right now.
