### ISSUE TITLE
13) [rfced] Section 4.1.8.1:  As it appears that "ICE and DTLS

### ISSUE THREAD

**Issue by juberti** [rtcweb-wg/jsep#883]
13) [rfced] Section 4.1.8.1:  As it appears that "ICE and DTLS
handshaking have" means "ICE handshaking and DTLS handshaking have,"
we updated this sentence accordingly.  Please let us know if this is
incorrect (i.e., if the text refers to one handshaking process, in
which case "have" should be "has").

Original:
 Upon acceptance by the user, the
 application will plug in the tracks it has acquired, which, because
 ICE and DTLS handshaking have likely completed by this point, can
 start transmitting immediately.

Currently:
 Upon acceptance by the user, the
 application will plug in the tracks it has acquired, which, because
 ICE handshaking and DTLS handshaking have likely completed by this
 point, can start transmitting immediately.

**Comment by juberti** [comment]
SGTM

**Comment by fluffy** [comment]
LGTM

**Comment by juberti** [comment]
@ajeanmahoney please close this issue once you consider it resolved.
