### ISSUE TITLE
23) [rfced] Section 5.2.1:  This is the only bullet item in this

### ISSUE THREAD

**Issue by juberti** [rtcweb-wg/jsep#893]
23) [rfced] Section 5.2.1:  This is the only bullet item in this
list that (1) is a sentence fragment, unlike the rest and (2) does
not contain "RFC 2119" language.  We have updated as follows, but
please let us know if further changes are needed.

Original:
 o  If WebRTC identity is being used, an "a=identity" line as
    described in [I-D.ietf-rtcweb-security-arch], Section 5.

Currently:
 *  If WebRTC identity is being used, an "a=identity" line, as
    described in [RFC8827], Section 5, needs to be included.

**Comment by juberti** [comment]
I think what we want is

 `an "a=identity" line MUST be added, as described in [RFC8827], Section 5.'

**Comment by juberti** [comment]
@ajeanmahoney please close this issue once you consider it resolved.

**Comment by ajeanmahoney** [comment]
@mskucherawy normative text change, please review.

**Comment by ajeanmahoney** [comment]
Removed editor-ready because it's already been addressed and added the discuss label since that seems like a reasonable label for AD attention.

**Comment by juberti** [comment]
ping @mskucherawy

**Comment by mskucherawy** [comment]
Yep, that's approved.
