### ISSUE TITLE
25) [rfced] Sections 5.2.1 and 5.2.2:  Please confirm that these

### ISSUE THREAD

**Issue by juberti** [rtcweb-wg/jsep#895]
25) [rfced] Sections 5.2.1 and 5.2.2:  Please confirm that these
citations for RFC 8843 [I-D.ietf-mmusic-sdp-bundle-negotiation], Section 8.1
are correct; we could not see a relationship.

Original:
 To avoid unnecessary duplication when
 bundling, attributes of category IDENTICAL or TRANSPORT MUST NOT be
 repeated in bundled m= sections, repeating the guidance from
 [I-D.ietf-mmusic-sdp-bundle-negotiation], Section 8.1.
...
 Instead,
 JSEP implementations MUST simply omit parameters in the IDENTICAL
 and TRANSPORT categories for bundled m= sections, as described in
 [I-D.ietf-mmusic-sdp-bundle-negotiation], Section 8.1.

**Comment by juberti** [comment]
needs review of latest BUNDLE doc

**Comment by fluffy** [comment]
The  8.1 should probably 7.1.3

https://tools.ietf.org/html/draft-ietf-mmusic-sdp-bundle-negotiation-54#section-7.1.3

**Comment by juberti** [comment]
agreed
