### ISSUE TITLE
26) [rfced] Section 5.2.1:  Please confirm that this citation is

### ISSUE THREAD

**Issue by juberti** [rtcweb-wg/jsep#896]
26) [rfced] Section 5.2.1:  Please confirm that this citation is
correct; we could not see a relationship between Section 14 of
RFC 8843 [I-D.ietf-mmusic-sdp-bundle-negotiation] and the RTP header
extension.

Original:
 All MID
 values MUST be generated in a fashion that does not leak user
 information, e.g., randomly or using a per-PeerConnection counter,
 and SHOULD be 3 bytes or less, to allow them to efficiently fit
 into the RTP header extension defined in
 [I-D.ietf-mmusic-sdp-bundle-negotiation], Section 14.

**Comment by juberti** [comment]
Need to review latest BUNDLE doc

**Comment by fluffy** [comment]
I think the reference should be to section 15.2 (not 14 ) 

https://tools.ietf.org/html/draft-ietf-mmusic-sdp-bundle-negotiation-47#section-15.2

**Comment by juberti** [comment]
Agreed. There may be some other citation around MID generation (that suggests starting at 0) that would be even better to reference too.

**Comment by juberti** [comment]
Section 17 of BUNDLE (https://tools.ietf.org/html/draft-ietf-mmusic-sdp-bundle-negotiation-54#section-17) mentions a per-bundle-group counter. However I tend to think we should just update the ref to what Cullen mentions and close this out.
