### ISSUE TITLE
36) [rfced] Section 5.2.2:  We could not find any indication in

### ISSUE THREAD

**Issue by juberti** [rtcweb-wg/jsep#906]
36) [rfced] Section 5.2.2:  We could not find any indication in
RFC 8843 [I-D.ietf-mmusic-sdp-bundle-negotiation], Section 6 that an
"a=bundle-only" line MUST NOT be added.  Will this be clear to
readers?

Original:
 o  An "a=bundle-only" line MUST NOT be added, as indicated in
    [I-D.ietf-mmusic-sdp-bundle-negotiation], Section 6.

Possibly:
 *  An "a=bundle-only" line, as described in [RFC8843], Section 6,
    MUST NOT be added.

**Comment by fluffy** [comment]
The proposed text seems correct

**Comment by juberti** [comment]
I would suggest 'defined' in lieu of 'described', but otherwise LGTM.
