### ISSUE TITLE
38) [rfced] Section 5.3.1:  Does this text mean that the offered

### ISSUE THREAD

**Issue by juberti** [rtcweb-wg/jsep#908]
38) [rfced] Section 5.3.1:  Does this text mean that the offered
media formats are allowed (in which case it should say "they are
allowed") or are not allowed (in which case "and, if applicable"
should be "or, if applicable")?

Original:
 o  None of the offered media formats are supported and, if
    applicable, allowed by codec preferences.

**Comment by juberti** [comment]
The intention was that at least one of the offered media formats needs to be supported AND allowed by codec preferences, if codec preferences have been set.

Perhaps "are both supported and ..." would help clarify.

**Comment by ajeanmahoney** [comment]
Perhaps:

There is no offered media format that is both supported and, if applicable, allowed by codec preferences.

**Comment by juberti** [comment]
LGTM
