### ISSUE TITLE
39) [rfced] Section 5.3.1: Should "must be followed:" here be

### ISSUE THREAD

**Issue by juberti** [rtcweb-wg/jsep#909]
39) [rfced] Section 5.3.1: Should "must be followed:" here be
"MUST be followed:"? (We ask because (1) we see "For the m= line
itself, the following  rules MUST be followed:" in Section 5.2.1 and
(2) all of the rules listed below this sentence include a "MUST.")

Original:
 For the m= line itself, the
 following rules must be followed:

**Comment by juberti** [comment]
yes, should be MUST.

**Comment by ajeanmahoney** [comment]
@mskucherawy Normative text change, please review

**Comment by juberti** [comment]
I hit this one in #996, closing it out accordingly.
