### ISSUE TITLE
43) [rfced] Section 5.8.1:  We found this sentence confusing;

### ISSUE THREAD

**Issue by juberti** [rtcweb-wg/jsep#913]
43) [rfced] Section 5.8.1:  We found this sentence confusing;
should "t=" remain in this list of lines not used by this
specification?

Original:
 The "i=", "u=", "e=", "p=", "t=", "r=", "z=", and "k=" lines are
 not used by this specification; they MUST be checked for syntax
 but their values are not used.

We ask because we see (for example):

o  A "t=" line MUST be added, as specified in [RFC4566], Section 5.9;
    both <start-time> and <stop-time> SHOULD be set to zero, e.g. "t=0
    0".
...
 o  The "s=" and "t=" lines MUST stay the same.
...
 t=0 0

**Comment by juberti** [comment]
The text you mention refers to the "parsing" context present in S 5.8.1, where said lines are largely ignored. However, as you point out, these lines are generated in the "creation" sections (for spec compatibility).

Please advise if you have thoughts on what text might help clarify the situation. @ajeanmahoney input needed

**Comment by ajeanmahoney** [comment]
Perhaps dropping the phrase "not used by this specification":

   The "i=", "u=", "e=", "p=", "t=", "r=", "z=", and "k=" lines MUST be 
   checked for syntax, but their values are not otherwise used.

**Comment by juberti** [comment]
LGTM
