### ISSUE TITLE
46) [rfced] Section 5.10:  For ease of the reader, we suggest

### ISSUE THREAD

**Issue by juberti** [rtcweb-wg/jsep#916]
46) [rfced] Section 5.10:  For ease of the reader, we suggest
adding a citation that provides the definition of "AS."  Please let us
know if we may update as follows.

Original:
 o  Any "AS" bandwidth value MUST be ignored, as the meaning of this
    construct at the session level is not well defined.

Suggested:
 *  Any "AS" bandwidth value ([RFC4566], Section 5.8) MUST be
    ignored, as the meaning of this construct at the session level is
    not well defined.

**Comment by ajeanmahoney** [comment]
Is the suggested text okay?

**Comment by juberti** [comment]
LGTM
