### ISSUE TITLE
49) [rfced] Section 5.11:  As it appears that "is also enabled"

### ISSUE THREAD

**Issue by juberti** [rtcweb-wg/jsep#919]
49) [rfced] Section 5.11:  As it appears that "is also enabled"
refers to silence suppression, we updated this sentence as follows.
Please let us know if this is incorrect.

Original:
 *  If the m= section is of type audio, and silence suppression was
    configured for the send media format as a result of processing
    the remote description, and is also enabled for that format in
    the local description, use silence suppression for outgoing
    media, in accordance with the guidance in Section 5.2.3.2.

Currently:
 -  If (1) the "m=" section is of type "audio" and (2) silence
    suppression was configured for the send media format as a
    result of processing the remote description and is also enabled
    for that format in the local description, use silence
    suppression for outgoing media, in accordance with the guidance
    in Section 5.2.3.2.

**Comment by juberti** [comment]
perhaps make it a 3-step:

> If (1) the "m=" section is of type "audio" and (2) silence
> suppression was configured for the send media format as a
> result of processing the remote description and (3) silence suppression is also enabled
> for that format in the local description, use silence
> suppression for outgoing media, in accordance with the guidance
> in Section 5.2.3.2.

**Comment by juberti** [comment]
@ajeanmahoney input needed

**Comment by ajeanmahoney** [comment]
How about the following? (not sure about verb tense since it was mixed (was configured ... is also enabled)): 

If the "m=" section is of type "audio", and silence suppression is (1) configured for the send media format as a result of processing the remote description and (2) also enabled for that format in the local description, then use silence suppression for outgoing media, in accordance with the guidance in Section 5.2.3.2.

**Comment by juberti** [comment]
I think we want past tense here because 5.11 talks about actions done after the existing local and remote description processing has been performed. (See the related bullet in S 5.10).
