### ISSUE TITLE
50) [rfced] Section 5.11:  Please (1) confirm that Section 6.2.2

### ISSUE THREAD

**Issue by juberti** [rtcweb-wg/jsep#920]
50) [rfced] Section 5.11:  Please (1) confirm that Section 6.2.2
of RFC 8853 [I-D.ietf-mmusic-sdp-simulcast] (with version -14 being
the latest for this draft) is the correct section to cite here and (2)
clarify the meaning of "send the number of Source RTP Streams as
specified in" (perhaps "... the specified number of ..." or "... the
appropriate number of ..."?).

Original:
 *  If simulcast has been negotiated, send the number of Source RTP
    Streams as specified in [I-D.ietf-mmusic-sdp-simulcast],
    Section 6.2.2.

**Comment by juberti** [comment]
need to check the simulcast section

"... the appropriate number ..." LGTM

**Comment by fluffy** [comment]
6.2.2 does not seem like the right section. I think 5.3 would be a better section to reference.

**Comment by juberti** [comment]
Since we're talking about handling an answer in this part of JSEP, 5.3.3 is probably the ideal section to refer to in -simulcast.
