### ISSUE TITLE
55) [rfced] Throughout: RFC 4566, which will be obsoleted by

### ISSUE THREAD

**Issue by juberti** [rtcweb-wg/jsep#925]
55) [rfced] Throughout: RFC 4566, which will be obsoleted by
RFC-to-be 8866 (soon to be released to AUTH48) as part of this
cluster, is heavily cited in this document.  Should the text instead
refer to RFC 8866?

**Comment by fluffy** [comment]
I tend to lean towards no give we reviewed again 4566 and 8866 has normative refs to stuff like MSRP but I have not looked at the details.

**Comment by juberti** [comment]
I also lean towards no because there could be a lot of section updates, but needs further investigation,

**Comment by fluffy** [comment]
I looked at this more and I think 8866 is just wrong. This is all relative to 4566 - I think we have to stay with that.

**Comment by fluffy** [comment]
I took a look at all the changes needed. Given the odds of messing this up and we reviewed as is, I think it is more risk than harm. I think we should just close this.

**Comment by juberti** [comment]
I'm good with that if @mskucherawy is on board.

**Comment by ajeanmahoney** [comment]
Note that @mskucherawy has not been receiving notifications for mentions because he hasn't been a Watcher. He should be signing up for notifications shortly.

**Comment by ajeanmahoney** [comment]
It's okay to keep the refs to RFC 4566 as-is. Most of C238 points to RFC 4566.

**Comment by juberti** [comment]
OK, that's enough for me. I'm going to close this out accordingly.
