### ISSUE TITLE
56) [rfced] Informative References:  RFC 6544 is not cited

### ISSUE THREAD

**Issue by juberti** [rtcweb-wg/jsep#926]
56) [rfced] Informative References:  RFC 6544 is not cited
anywhere in this document.  Please let us know where it should be
cited.

Original:
 [RFC6544]  Rosenberg, J., Keranen, A., Lowekamp, B., and A. Roach,
            "TCP Candidates with Interactive Connectivity
            Establishment (ICE)", RFC 6544, DOI 10.17487/RFC6544,
            March 2012, <https://www.rfc-editor.org/info/rfc6544>.

**Comment by fluffy** [comment]
I seem to recall this was par of the MTI stuff. We may need to add a sentence to point to transports drafts and ref.

**Comment by juberti** [comment]
This reference is obsolete and can be removed.
