### ISSUE TITLE
57) [rfced] Informative References:  The provided URL for

### ISSUE THREAD

**Issue by juberti** [rtcweb-wg/jsep#927]
57) [rfced] Informative References:  The provided URL for
[W3C.webrtc] steers to a page with a red window that says
"This version is outdated!"  Because the latest version
(September 2018) also discusses the RTCPeerConnection interface,
may we update this listing as suggested below?

Also, if you agree to this update, should Jan-Ivar Bruaroey be
added to the second sentence of the Acknowledgements section
(after Adam Bergkvist)?

Original:
 [W3C.webrtc]
            Bergkvist, A., Burnett, D., Jennings, C., Narayanan, A.,
            Aboba, B., and T. Brandstetter, "WebRTC 1.0: Real-time
            Communication Between Browsers", World Wide Web Consortium
            WD WD-webrtc-20170515, May 2017,
            <https://www.w3.org/TR/2017/WD-webrtc-20170515/>.

Suggested:
 [W3C.webrtc]
            Bergkvist, A., Burnett, D., Jennings, C., Narayanan, A.,
            Aboba, B., Brandstetter, T., and J-I. Bruaroey, "WebRTC
            1.0: Real-time Communication Between Browsers", World
            Wide Web Consortium Candidate Recommendation, September
            2018, <https://www.w3.org/TR/webrtc/>.

**Comment by fluffy** [comment]
The suggested change is not OK. This has to stable reference. The reference in the Original text may not be correct but we do need this to point at a table version.

**Comment by juberti** [comment]
How about we use the 2019 stable CR: https://www.w3.org/TR/2019/CR-webrtc-20191213/?

**Comment by fluffy** [comment]
yes, I think that would be correct as that is the latest stable published version.

**Comment by fluffy** [comment]
The RFC Editor database seems out of date for this so I manually created the patch

**Comment by juberti** [comment]
@fluffy, @ajeanmahoney, how should we proceed here?

**Comment by fluffy** [comment]
You OK with changing it to 
https://www.w3.org/TR/2020/CRD-webrtc-20201203/ 

( and yes on lets yes, lets add Jan-Ivar to acknowledgements )

**Comment by fluffy** [comment]
There is a PR at https://github.com/rtcweb-wg/jsep/pull/988 to add Jan-Ivar

**Comment by fluffy** [comment]
I just heard back the CRD would be inappropriate to use. So think that puts up back to the latest CR

**Comment by fluffy** [comment]
There is a PR at https://github.com/rtcweb-wg/jsep/pull/989 to update the reference to what Justin suggested on July 27 on in this issue.

**Comment by fluffy** [comment]
If we get Proposed Rec or REC version of this soon, we can switch to that. We should have a Proposed Rec now - there was consensus on that transition.

**Comment by fluffy** [comment]
I am proposing  https://github.com/rtcweb-wg/jsep/pull/991 as the fix for this. I am also think we should watch what happens at W3C because they are just about to have a proposed REC and if they get to that before we publish, we should switch to that.
