### ISSUE TITLE
61) [rfced] Other documents in this cluster spell "checklist" as one word.  May we change "check list" in this document to "checklist"?

### ISSUE THREAD

**Issue by juberti** [rtcweb-wg/jsep#931]
61) [rfced] Other documents in this cluster spell "checklist" as one word.  May we change "check list" in this document to "checklist"?

**Comment by juberti** [comment]
Sgtm

**Comment by juberti** [comment]
@ajeanmahoney please close this issue once you consider it resolved.

**Comment by fluffy** [comment]
+1

**Comment by ajeanmahoney** [comment]
Who will be making this update?  Do I make the update on my copy at the RPC? Do you or I make the update here?

**Comment by juberti** [comment]
@ajeanmahoney I'm working on that now. What I had in mind would be that for each issue, as you close it out, you would send over (or point me at) the latest copy of the XML with the changes needed for that particular issue applied. I will then update the pending copy in this repo (https://github.com/rtcweb-wg/jsep/pull/932/files) with what you provide.

For example, on this issue, once you make the changes regarding 'check list', remove the XML comment for this issue and send over the updated XML.

Email me at juberti@google.com if you'd prefer to discuss more directly, we can set up a quick call if needed.

**Comment by juberti** [comment]
[reopening until the XML edits are applied]

**Comment by juberti** [comment]
Fixed in commit 8364c8fd582030b23e0d0af52f09cea3574b6911

**Comment by juberti** [comment]
Reopening as we are migrating to an individual-PR workflow.

**Comment by juberti** [comment]
Reopening as we are going to be working on the rfced branch.
