### ISSUE TITLE
Should the ladder diagrams be done in SVG ?

### ISSUE THREAD

**Issue by fluffy** [rtcweb-wg/jsep#949]

**Comment by fluffy** [comment]
It would mean the HTML version of the spec would look like an actually figure instead of ascii art. That is a purely cosmetic benefit so I don't feel strongly one way or the other.

**Comment by juberti** [comment]
I tend to think that we're sticking with ascii-art unless someone wants to take on the work for this. @fluffy please advise.

**Comment by fluffy** [comment]
Given that we can't use any normal SVG tools to do this, not worth the effort. I'm going to close this
