### ISSUE TITLE
60.2) Term consistency - zero

### ISSUE THREAD

**Issue by ajeanmahoney** [rtcweb-wg/jsep#963]
>set to zero / set to 0 
>(May we use the latter, because of '"dummy" port value of 9' in Sections 5.2.1 and 5.3.1?)

Justin: What's the IETF style guide say on this sort of thing? 'zero' looks more natural to me, and matches RFC 3264's usage of 'zero'.

**Comment by ajeanmahoney** [comment]
From our style guide:  "In general text, we follow the CMOS guidance that numbers under 10 are written out and those above are represented using digits.  However, if a value is followed by a unit of measure (e.g., 8 bytes, 3 octets), it should be in digit form regardless of value."
  
There is one instance of "set to 0" in this document vs four instances of "set to zero".  I can change that one instance to match the other four.

**Comment by juberti** [comment]
LGTM
