### ISSUE TITLE
60.2) Term consistency - fmt/media/port/porto

### ISSUE THREAD

**Issue by ajeanmahoney** [rtcweb-wg/jsep#965]
>fmt value / "fmt" value

Justin:  Would we also do media, port, and proto? This one needs more discusison.

**Comment by ajeanmahoney** [comment]
RFC 4566 (SDP) was inconsistent in the formatting of fmt (`<fmt>`, "fmt"), proto ("proto", `<proto>`), and port (port, `<port>`). For the most part, media was just formatted media.  

RFC 8866 (SDP), which obsoletes RFC 4566, consistently formats these "m=" line subfields as `<media>`, `<port>`, `<proto>`, and `<fmt>`.

This document uses the following formats:

- fmt (3 instances) vs `<fmt>` (2 instances)
- proto (7 instances) vs `<proto>` (5 instances)
- port (31) vs `<port>` (0 instances)  -- most are not referring specifically to the `<port>` subfield, though

I suggest using angle brackets (but not `code` formatting -- I was just working around GitHub's markdown with that) for these terms when discussing "m=" line subfields.

**Comment by juberti** [comment]
SGTM, let's align with 8866 usage when an instance of these words refers specifically to a m= line subfield.
