### ISSUE TITLE
2119/8174 Keywords

### ISSUE THREAD

**Issue by ajeanmahoney** [rtcweb-wg/jsep#977]
During EDIT, we modified the following paragraph:

Original:

   The key words "MUST", "MUST NOT", "REQUIRED", "SHALL", "SHALL NOT",
   "SHOULD", "SHOULD NOT", "RECOMMENDED", "MAY", and "OPTIONAL" in this
   document are to be interpreted as described in [RFC2119].

Current:

   The key words "MUST", "MUST NOT", "REQUIRED", "SHALL", "SHALL NOT",
   "SHOULD", "SHOULD NOT", "RECOMMENDED", "NOT RECOMMENDED", "MAY", and
   "OPTIONAL" in this document are to be interpreted as described in
   BCP 14 [RFC2119] [RFC8174] when, and only when, they appear in all
   capitals, as shown here.

This document uses at least one instance of a 2119 keyword in lowercase. 
Please review and let us know if the paragraph about keywords should refer to RFC 2119 (only).

For background: https://www.rfc-editor.org/pipermail/c238/2020-July/000504.html

**Comment by juberti** [comment]
This seems fine. @fluffy?

**Comment by juberti** [comment]
We're just talking about referencing 8174 here, I assume, not changing the lowercase words.

**Comment by ajeanmahoney** [comment]
@fluffy Cullen, you responded on the c238@rfc-editor.org list with the following: "For the draft I wrote, I do my best not to use the lower case version of the 2119 words.  If I did user the lower case,  I probably did not mean the 2119 meaning and instead meant just the plain english version. I would want to review any changes to those carefully but I think we should move to 8174."  Have you had a chance to look this over? Thanks!

**Comment by juberti** [comment]
I took a quick look and there are many instances of lowercase "may" and a few "must". In some cases I would say that swapping in an uppercase version is warranted, will try to compile a list.

**Comment by juberti** [comment]
I'd argue that all the lowercase "must" usages in Sections 4 and 5 (20 or so) should be converted to MUSTs. There are also 55 "may" usages, of which perhaps 10 might be worth converting to MAY. @ajeanmahoney do you want to propose a PR?

**Comment by fluffy** [comment]
tag me to review the PR when it gets done ....

**Comment by ajeanmahoney** [comment]
@juberti, I am not comfortable determining which of the 55 "may"s should be converted to MAY.  I believe that you should propose the PR for changes to normative text and let @fluffy and @ekr review it. Then the ADs need to review it. Thanks!

**Comment by fluffy** [comment]
I just greped all the should / must and it was more of a mess than I remembered.

**Comment by juberti** [comment]
Understood. I'll make a PR here.
