### ISSUE TITLE
59.1) Change to Appendix A heading

### ISSUE THREAD

**Issue by ajeanmahoney** [rtcweb-wg/jsep#978]
We changed the title of Appendix A from "Appendix A" to "ABNF Definitions." If this is not correct, please provide an appropriately descriptive title.

Justin:  I suggest either "SDP ABNF References" or "SDP ABNF Syntax".

Jean:  I'll change it to "SDP ABNF Syntax".  If the heading says "References" readers may expect an actual list of references.

**Comment by fluffy** [comment]
I don't care

**Comment by juberti** [comment]
LGTM
