### ISSUE TITLE
59.3)  Unused attributes

### ISSUE THREAD

**Issue by ajeanmahoney** [rtcweb-wg/jsep#980]
We do not see the attributes "framerate," "quality," or "connection" listed anywhere else in this document. Do they need to
be included here?

Fluffy:  One comment on (C). Yes I think they should stay in the ABNF.

Justin:  Yes, these parameters need to match the specified syntax but are otherwise ignored by this spec.

Justin:  We should get rid of a=connection, it's not used by JSEP.

**Comment by ajeanmahoney** [comment]
Note there is inconsistent guidance on this issue. Please confirm that the attributes mentioned should remain.

**Comment by juberti** [comment]
I would recommend removing these three lines from Appendix A. None of them are referenced anywhere else in the text.
