### ISSUE TITLE
59.6) simulcast reference

### ISSUE THREAD

**Issue by ajeanmahoney** [rtcweb-wg/jsep#982]
Please confirm that Section 6.1 of RFC 8853
[I-D.ietf-mmusic-sdp-simulcast] is the correct section to cite here.
(We ask because we could not see a relationship, other than the
mention of "simulcast" mostly in terms of simulcast streams, and also
because we see ABNF for the "a=simulcast" attribute in Section 5.1 of
RFC 8853 [I-D.ietf-mmusic-sdp-simulcast].)

Original:

    Appendix A. Appendix A
    ...
    | simulcast | [I-D.ietf-mmusic-sdp-simulcast] Section 6.1 |

Currently:

    Appendix A. ABNF Definitions
    ...
    | simulcast | Section 6.1 of [RFC8853] |

Justin:  For a=simulcast, S 5.1 looks like the right reference.

**Comment by fluffy** [comment]
Yes, agree with the off by one

**Comment by juberti** [comment]
Does S 5.1 look right to you? If so, please proceed.
