### ISSUE TITLE
59.5) off-by-one section xrefs

### ISSUE THREAD

**Issue by ajeanmahoney** [rtcweb-wg/jsep#983]
As noted previously, it appears that most of the listed section
numbers for RFC 8839 [I-D.ietf-mmusic-ice-sip-sdp] are "off by one" (i.e.,
that "4.1" should be "5.1," "4.2" should be "5.2," etc. We have
updated the section references accordingly; please review and let us
know if any corrections are needed.

Justin:  For RFC 8839, the off-by-one diagnosis and recommended solution LGTM.

**Comment by fluffy** [comment]
Yes, agree with the off by one
