### ISSUE TITLE
ICE Version 

### ISSUE THREAD

**Issue by fluffy** [rtcweb-wg/jsep#990]
The text in the ICE version section merge from Oct 22 seems wrong to me.

**Comment by fluffy** [comment]
I think is should read more like "While this specification allows for the use of [RFC8445], it only requires [RFC5245]" and then much of the rest of the para. 8445 should be an information ref while 5245 should be a normative ref

**Comment by fluffy** [comment]
@adamroach @juberti - thoughts ?

**Comment by adamroach** [comment]
> @adamroach @juberti - thoughts ?

I've laid out my position on this topic [as a comment in issue 874](https://github.com/rtcweb-wg/jsep/issues/874#issuecomment-743807397), and think it would be a subversion of the IETF consensus process to relitigate the outcome of IETF mailing list discussion on github.

**Comment by fluffy** [comment]
I think adam is correct in this - closing this.
